import {validateCanvasProtectedBatchBinding,validateNativePrintFinalFrame,type CanvasProtectedBatchBinding,type CanvasProtectedSource} from './nativePrintFinalFrame';
import {protectedImageDigest,protectedImageSaveRequestId} from './protectedImageEditContract';
import {materializeMaterialPng,composeMappedOpenAICandidate,type ProtectedMaterialComposite} from './materialProtectedComposite';
import {findWorkspaceArtifactPersisted,saveWorkspaceArtifactPersisted,type WorkspaceArtifact} from './localWorkspaceArtifacts';
import type {PreparedProtectedCloudflareEdit,ProtectedEditLifecycle,ProtectedEditLifecycleContext,ProtectedEditSaveInput} from './cloudflareProtectedImageEdit';
import type {ImageReceipt} from './cloudflareImageAI';
import type {Json} from '../types/database';
export type {CanvasProtectedBatchBinding} from './nativePrintFinalFrame';
type Png={dataUrl:string;digest:string;width:number;height:number};
type Batch={binding:CanvasProtectedBatchBinding;original:Png;mask:Png;candidateLocators:string[];prepared?:PreparedProtectedCloudflareEdit;receipt?:ImageReceipt;sourceProof?:CanvasObjectSourceProof;preparationSignature?:string};
type Candidate={index:number;requestId:string;rawIdentity:Record<string,unknown>;rawDigest:string;stage:'candidate-ready'|'composed'|'saved';finalId?:string;finalDigest?:string;saveInput?:Omit<ProtectedEditSaveInput,'imageUrl'>;savedImage?:Record<string,unknown>};
const json=(v:unknown):Json=>JSON.parse(JSON.stringify(v)) as Json;
const equal=(a:unknown,b:unknown)=>JSON.stringify(a)===JSON.stringify(b);
function fail(s:string):never{throw new Error(`canvas_protected_${s}`);}
const locator=(b:CanvasProtectedBatchBinding,i:number)=>`canvas-protected-candidate-${b.requestId}-${i}`;
function read(b:CanvasProtectedBatchBinding,id:string):WorkspaceArtifact {const r=findWorkspaceArtifactPersisted(b.brandId,id,b.scopeId);if(!r.ok)throw r.error;if(!r.artifact)fail('local_artifact_missing');return r.artifact;}
function write(b:CanvasProtectedBatchBinding,id:string,imageUrl:string,key:string,value:unknown):WorkspaceArtifact {const r=saveWorkspaceArtifactPersisted({id,brandId:b.brandId,scopeId:b.scopeId,featureType:b.featureType,title:'Canvas範囲編集の保存状態',prompt:null,imageUrl,metadata:{[key]:json(value)}});if(!r.ok)throw r.error;const proof=read(b,id);if(proof.imageUrl!==imageUrl||!equal(proof.metadata[key],json(value)))fail('local_readback_failed');return proof;}
async function png(url:string):Promise<Png>{const p=await materializeMaterialPng(url);return {...p,digest:await protectedImageDigest(p.dataUrl)};}
async function verifyPng(p:Png){const actual=await png(p.dataUrl);if(!equal(actual,p))fail('local_png_identity_mismatch');}
export async function prepareCanvasProtectedBatch(input:{sourceImageUrl:string;maskDataUrl:string;requestId?:string;featureType:CanvasProtectedBatchBinding['featureType'];brandId:string;scopeId:string;canvasProjectId:string|null;parentObjectId:string|null;generation:number;inputSignature:unknown;source?:CanvasProtectedSource;sourceIdentity?:unknown;sourceImageId?:string;verifiedObjectSource?:VerifiedCanvasObjectSource;assertCurrent():void|Promise<void>}):Promise<CanvasProtectedBatchBinding>{
 await input.assertCurrent();const original=await png(input.sourceImageUrl),mask=await png(input.maskDataUrl);await input.assertCurrent();if(original.width!==mask.width||original.height!==mask.height)fail('mask_dimensions_mismatch');const requestId=input.requestId??crypto.randomUUID();
 if(input.parentObjectId){const verified=input.verifiedObjectSource;if(!verified||!equal(verified.objectDescriptor,input.sourceIdentity)||verified.originalPngDataUrl!==original.dataUrl||verified.originalPngDigest!==original.digest||verified.width!==original.width||verified.height!==original.height)fail('verified_object_source_required');await assertObjectProof(verified,original);}
 const source:CanvasProtectedSource=input.source??(input.parentObjectId?{kind:'object',objectId:input.parentObjectId,identityDigest:await protectedImageDigest(JSON.stringify(input.sourceIdentity??input.inputSignature))}:{kind:'retained-generated',sourceArtifactId:`canvas-protected-source-${requestId}`,sourceKey:await protectedImageDigest(JSON.stringify([input.canvasProjectId,requestId,original.digest,input.sourceImageId??null])),pngDigest:original.digest,...(input.sourceImageId?{sourceImageId:input.sourceImageId}:{})});
 const preparationSignature=await protectedImageDigest(JSON.stringify([input.inputSignature,original.digest,mask.digest,input.featureType,input.canvasProjectId,input.parentObjectId,input.generation]));
 const generationInputSignature=input.verifiedObjectSource?await protectedImageDigest(JSON.stringify([preparationSignature,objectProof(input.verifiedObjectSource)])):preparationSignature;
 const binding=validateCanvasProtectedBatchBinding({version:1,requestId,batchStateArtifactId:`canvas-protected-batch-${requestId}`,requestedCandidateCount:4,source,featureType:input.featureType,brandId:input.brandId,scopeId:input.scopeId,canvasProjectId:input.canvasProjectId,parentObjectId:input.parentObjectId,generation:input.generation,generationInputSignature});
 if(source.kind==='retained-generated')write(binding,source.sourceArtifactId,original.dataUrl,'canvasProtectedSource',binding.source);
 const batch:Batch={binding,original,mask,candidateLocators:Array.from({length:4},(_,i)=>locator(binding,i)),...(input.verifiedObjectSource?{sourceProof:objectProof(input.verifiedObjectSource),preparationSignature}:{})};write(binding,binding.batchStateArtifactId,original.dataUrl,'canvasProtectedBatch',batch);await loadCanvasProtectedBatch(binding);await input.assertCurrent();return binding;
}
export async function loadCanvasProtectedBatch(value:CanvasProtectedBatchBinding):Promise<Batch>{const b=validateCanvasProtectedBatchBinding(value),batch=read(b,b.batchStateArtifactId).metadata.canvasProtectedBatch as unknown as Batch;if(!batch||!equal(batch.binding,b)||!equal(batch.candidateLocators,Array.from({length:4},(_,i)=>locator(b,i))))fail('batch_identity_mismatch');await verifyPng(batch.original);await verifyPng(batch.mask);if(b.source.kind==='object'){if(!batch.sourceProof)fail('object_source_proof_required');await assertObjectProof(batch.sourceProof,batch.original);if(!batch.preparationSignature||await protectedImageDigest(JSON.stringify([batch.preparationSignature,batch.sourceProof]))!==b.generationInputSignature)fail('object_source_proof_mismatch');if(batch.sourceProof.objectDescriptorDigest!==b.source.identityDigest||batch.sourceProof.objectDescriptor.objectId!==b.source.objectId)fail('object_source_proof_mismatch');}if(b.source.kind==='retained-generated'){const source=read(b,b.source.sourceArtifactId);if(!equal(source.metadata.canvasProtectedSource,b.source)||source.imageUrl!==batch.original.dataUrl||b.source.pngDigest!==batch.original.digest||b.source.sourceKey!==await protectedImageDigest(JSON.stringify([b.canvasProjectId,b.requestId,batch.original.digest,b.source.sourceImageId??null])))fail('retained_source_identity_mismatch');}if(batch.original.width!==batch.mask.width||batch.original.height!==batch.mask.height)fail('mask_dimensions_mismatch');return batch;}
export async function bindCanvasProtectedPreparation(binding:CanvasProtectedBatchBinding,prepared:PreparedProtectedCloudflareEdit,assertCurrent:()=>Promise<void>){
 await assertCurrent();const batch=await loadCanvasProtectedBatch(binding);const native=validateNativePrintFinalFrame(prepared.body.nativePrintFinalFrame,prepared.plan);if(native.version!=='canvas-protected-openai-contain-v1'||!equal(native.canvasBatch,binding)||native.original.digest!==batch.original.digest||prepared.plan.sourceWidth!==batch.original.width||prepared.plan.sourceHeight!==batch.original.height||prepared.plan.maskSha256!==batch.mask.digest||binding.featureType!==prepared.body.featureType||Number(prepared.body.count)!==4||(prepared.body.canvasProjectId??null)!==binding.canvasProjectId||(prepared.body.parentObjectId??null)!==binding.parentObjectId||prepared.body.generation!==binding.generation)fail('prepared_identity_mismatch');
 if(batch.prepared&&!equal(batch.prepared,prepared))fail('prepared_identity_mismatch');batch.prepared=prepared;write(binding,binding.batchStateArtifactId,batch.original.dataUrl,'canvasProtectedBatch',batch);await assertCurrent();
}
export function canvasCompletedReceiptIdentity(receipt:ImageReceipt){const {imageUrl:_url,images,...rest}=receipt;return {...rest,images:Array.isArray(images)?images.map(image=>{const {imageUrl:_candidateUrl,...identity}=image;return identity;}):images};}
export async function canvasBatchHasAllRaw(binding:CanvasProtectedBatchBinding){for(let i=0;i<4;i++){const r=findWorkspaceArtifactPersisted(binding.brandId,locator(binding,i),binding.scopeId);if(!r.ok)throw r.error;if(!r.artifact)return false;}return true;}
const rawIdentity=(c:ProtectedEditLifecycleContext)=>({requestId:c.receipt.requestId,jobId:c.receipt.jobId,index:c.candidateIndex,imageId:c.candidate.imageId,storagePath:c.candidate.storagePath,provider:c.candidate.provider,model:c.candidate.providerModel,width:c.candidate.width,height:c.candidate.height});
async function candidate(binding:CanvasProtectedBatchBinding,c:ProtectedEditLifecycleContext):Promise<{artifact:WorkspaceArtifact;state:Candidate}|undefined>{const r=findWorkspaceArtifactPersisted(binding.brandId,locator(binding,c.candidateIndex),binding.scopeId);if(!r.ok)throw r.error;if(!r.artifact)return;const state=r.artifact.metadata.canvasProtectedCandidate as unknown as Candidate;if(!state||!['candidate-ready','composed','saved'].includes(state.stage)||state.index!==c.candidateIndex||state.requestId!==binding.requestId||!equal(state.rawIdentity,rawIdentity(c))||state.rawDigest!==await protectedImageDigest(r.artifact.imageUrl))fail('candidate_identity_mismatch');return {artifact:r.artifact,state};}
function resolvedProviderModel(c:ProtectedEditLifecycleContext){const resolved=c.receipt.resolvedProvider;return resolved&&typeof resolved==='object'&&!Array.isArray(resolved)&&'model'in resolved?resolved.model:undefined;}
function assertSavedProvider(c:ProtectedEditLifecycleContext,saved:Record<string,unknown>|undefined){const authority=c.verifiedProvider;if(!saved||authority?.provider!=='openai'||saved.provider!==authority.provider||saved.providerModel!==authority.model||saved.modelUsed!==authority.model||c.receipt.provider!=='openai'||c.receipt.providerModel!==authority.model||resolvedProviderModel(c)!==authority.model)fail('saved_identity_mismatch');}
async function final(binding:CanvasProtectedBatchBinding,c:ProtectedEditLifecycleContext,state:Candidate){const id=`wa-${await protectedImageSaveRequestId(binding.requestId,c.candidateIndex)}`;if(state.finalId!==id||!state.saveInput||state.saveInput.requestId!==c.saveRequestId)fail('final_identity_mismatch');const a=read(binding,id);if(state.finalDigest!==await protectedImageDigest(a.imageUrl))fail('final_identity_mismatch');return a;}
export async function createCanvasProtectedBatchLifecycle(binding:CanvasProtectedBatchBinding,prepared:PreparedProtectedCloudflareEdit,scope:{brandId:string;userId:string},assertCurrent:()=>Promise<void>):Promise<ProtectedEditLifecycle>{
 if(binding.brandId!==scope.brandId||binding.scopeId!==scope.userId||binding.requestId!==prepared.canvasProtectedBatchBinding?.requestId)fail('scope_mismatch');await bindCanvasProtectedPreparation(binding,prepared,assertCurrent);
 const check=async(c:ProtectedEditLifecycleContext)=>{await assertCurrent();if(c.receipt.requestId!==binding.requestId||c.prepared!==prepared||c.candidateIndex<0||c.candidateIndex>3)fail('context_identity_mismatch');return loadCanvasProtectedBatch(binding);};
 return {
  async onCompletedReceipt(receipt){await assertCurrent();const batch=await loadCanvasProtectedBatch(binding);if(batch.receipt&&!equal(canvasCompletedReceiptIdentity(batch.receipt),canvasCompletedReceiptIdentity(receipt)))fail('completed_receipt_identity_mismatch');batch.receipt??=receipt;write(binding,binding.batchStateArtifactId,batch.original.dataUrl,'canvasProtectedBatch',batch);await assertCurrent();},
  async onCandidate(c){await check(c);const retained=await candidate(binding,c);if(retained)return {dataUrl:retained.artifact.imageUrl};const raw=await png(String(c.candidate.imageUrl));await assertCurrent();if(raw.width!==c.candidate.width||raw.height!==c.candidate.height)fail('candidate_geometry_mismatch');const state:Candidate={index:c.candidateIndex,requestId:binding.requestId,rawIdentity:rawIdentity(c),rawDigest:raw.digest,stage:'candidate-ready'};write(binding,locator(binding,c.candidateIndex),raw.dataUrl,'canvasProtectedCandidate',state);await check(c);return {dataUrl:raw.dataUrl};},
  async getPersistedComposite(c){await check(c);const retained=await candidate(binding,c);if(!retained||retained.state.stage==='candidate-ready')return;const a=await final(binding,c,retained.state);const batch=await loadCanvasProtectedBatch(binding);return {dataUrl:a.imageUrl,width:batch.original.width,height:batch.original.height,sourceFramePlacement:{x:0,y:0,width:batch.original.width,height:batch.original.height},mode:'source-protected-native-frame-v1'};},
  async composeCandidate(c,dataUrl){const batch=await check(c);return composeMappedOpenAICandidate({version:1,requestId:binding.requestId,candidateIndex:c.candidateIndex,stage:'candidate-ready',original:batch.original,mask:batch.mask,openAIProjection:validateNativePrintFinalFrame(prepared.body.nativePrintFinalFrame,prepared.plan).mapping} as ProtectedMaterialComposite,dataUrl);},
  async onComposed(c,composite,input){await check(c);const retained=await candidate(binding,c);if(!retained)fail('candidate_missing');const finalDigest=await protectedImageDigest(composite.dataUrl);const projection={version:1,digestScheme:'sha256-data-url-utf8-v1',binding,index:c.candidateIndex,rawIdentity:retained.state.rawIdentity,rawDigest:retained.state.rawDigest,finalDigest,finalId:`wa-${c.saveRequestId}`,width:composite.width,height:composite.height};const proof={canvasProtectedComposite:json(projection)};
   input.metadata={...proof,...input.metadata};const {imageUrl,...core}=input;if(retained.state.saveInput){if(!equal(retained.state.saveInput,core)||retained.state.finalDigest!==finalDigest)fail('save_input_identity_mismatch');Object.assign(input,retained.state.saveInput,{imageUrl});}else{retained.state.saveInput=core;retained.state.finalDigest=finalDigest;retained.state.finalId=`wa-${c.saveRequestId}`;retained.state.stage='composed';write(binding,retained.state.finalId,composite.dataUrl,'canvasProtectedComposite',projection);write(binding,locator(binding,c.candidateIndex),retained.artifact.imageUrl,'canvasProtectedCandidate',retained.state);}await final(binding,c,retained.state);await assertCurrent();return proof;},
  async refreshVerifiedSavedCandidate(c,imageUrl){await check(c);const retained=await candidate(binding,c);if(!retained||retained.state.stage!=='saved'||!retained.state.savedImage)fail('saved_identity_mismatch');assertSavedProvider(c,retained.state.savedImage);const a=await final(binding,c,retained.state);await verifyCanvasSavedPng(a.imageUrl,imageUrl,assertCurrent);retained.state.savedImage.imageUrl=imageUrl;write(binding,locator(binding,c.candidateIndex),retained.artifact.imageUrl,'canvasProtectedCandidate',retained.state);await assertCurrent();},
  async getVerifiedSavedCandidate(c){await check(c);const retained=await candidate(binding,c);if(retained?.state.stage!=='saved')return;const saved=retained.state.savedImage;assertSavedProvider(c,saved);await final(binding,c,retained.state);const batch=await loadCanvasProtectedBatch(binding);if(!saved||saved.imageId!==retained.state.finalId||saved.jobId!==saved.imageId||saved.id!==saved.imageId||saved.storagePath!==`generated-images/${saved.imageId}`||saved.candidateIndex!==c.candidateIndex||saved.providerImageId!==c.candidate.imageId||saved.providerJobId!==c.receipt.jobId||saved.providerStoragePath!==c.candidate.storagePath||saved.width!==batch.original.width||saved.height!==batch.original.height||saved.protectedRegionComposited!==true||typeof saved.imageUrl!=='string'||!saved.imageUrl.startsWith('https://'))fail('saved_identity_mismatch');return saved;},
  async onSavedCandidate(c,saved,imageUrl){await check(c);const retained=await candidate(binding,c);if(!retained)fail('candidate_missing');const a=await final(binding,c,retained.state);const projection=(a.metadata.canvasProtectedComposite as unknown as Record<string,unknown>);const authority=c.verifiedProvider;if(authority?.provider!=='openai'||c.receipt.providerModel!==authority.model||resolvedProviderModel(c)!==authority.model)fail('saved_identity_mismatch');if(!equal(saved.metadata?.canvasProtectedComposite,projection))fail('saved_identity_mismatch');
   await verifyCanvasSavedPng(a.imageUrl,imageUrl,assertCurrent);await assertCurrent();retained.state.stage='saved';retained.state.savedImage={...c.candidate,provider:authority.provider,providerModel:authority.model,modelUsed:authority.model,backendProvider:authority.backendProvider,id:a.id,imageId:a.id,jobId:a.id,storagePath:saved.remote.storagePath,imageUrl,width:projection.width,height:projection.height,candidateIndex:c.candidateIndex,providerJobId:c.receipt.jobId,providerImageId:c.candidate.imageId,providerStoragePath:c.candidate.storagePath,protectedRegionComposited:true};write(binding,locator(binding,c.candidateIndex),retained.artifact.imageUrl,'canvasProtectedCandidate',retained.state);await assertCurrent();}
 };
}
export async function verifyCanvasSavedPng(canonical:string,url:string,assertCurrent:()=>Promise<void>){await assertCurrent();if(!url.startsWith('https://'))fail('saved_png_read_failed');const response=await fetch(url,{credentials:'omit'});await assertCurrent();if(!response.ok)fail('saved_png_read_failed');const raw=new Uint8Array(await response.arrayBuffer()),expected=Uint8Array.from(atob(canonical.split(',')[1]),c=>c.charCodeAt(0));await assertCurrent();if(raw.length!==expected.length||raw.some((v,i)=>v!==expected[i]))fail('saved_png_bytes_mismatch');}
export async function completedCanvasProtectedBatch(binding:CanvasProtectedBatchBinding):Promise<boolean>{const batch=await loadCanvasProtectedBatch(binding);if(!batch.receipt)return false;for(let i=0;i<4;i++){const c={prepared:batch.prepared!,receipt:batch.receipt,candidate:(batch.receipt.images as Record<string,unknown>[])[i],candidateIndex:i,saveRequestId:await protectedImageSaveRequestId(binding.requestId,i)} as ProtectedEditLifecycleContext;const retained=await candidate(binding,c);if(!retained||retained.state.stage!=='saved')return false;await final(binding,c,retained.state);}return true;}
export function assertCanvasCanonicalBatchResult(value:unknown){const receipt=value as ImageReceipt;if(!receipt||!receipt.success||receipt.requiresProtectedComposite!==false||receipt.requestedCandidateCount!==4||receipt.persistedCandidateCount!==4||receipt.persistenceStatus!=='completed'||Array.isArray(receipt.failedCandidates)&&receipt.failedCandidates.length||!Array.isArray(receipt.images)||receipt.images.length!==4||new Set(receipt.images.map(c=>c.imageId)).size!==4||receipt.images.some((c,i)=>c.candidateIndex!==i||c.protectedRegionComposited!==true||typeof c.imageId!=='string'||!c.imageId.startsWith('wa-')))fail('batch_final_proof_required');}

export async function canAcknowledgeCanvasProtectedBatch(binding:CanvasProtectedBatchBinding,objects:Array<{metadata?:unknown}>){
 const b=validateCanvasProtectedBatchBinding(binding);const placed=objects.map(o=>o.metadata as {imageId?:string;parentObjectId?:string|null;generation?:number;parameters?:{candidateIndex?:number;imageAICompletion?:{requestId?:string}}}|undefined).filter(m=>m?.parameters?.imageAICompletion?.requestId===b.requestId);
 if(placed.length!==4||new Set(placed.map(m=>m?.parameters?.candidateIndex)).size!==4)return false;
 for(let i=0;i<4;i++){const metadata=placed.find(m=>m?.parameters?.candidateIndex===i);if(metadata?.imageId!==`wa-${await protectedImageSaveRequestId(b.requestId,i)}`||(metadata.parentObjectId??null)!==b.parentObjectId||metadata.generation!==b.generation)return false;}
 return completedCanvasProtectedBatch(b);
}

export type CanvasSourceObject={id:string;src?:string;metadata?:{storagePath?:string|null;galleryStoragePath?:string;galleryImageId?:unknown;galleryImageUrl?:unknown;imageId?:string|null;generation?:number;sourceIdentity?:unknown;sourceRevision?:unknown;parameters?:unknown}};
const sourceFields=['galleryStoragePath','storagePath','remoteStoragePath','sourceStoragePath','backendStoragePath'] as const;
const canonicalValue=(value:unknown):unknown=>value===undefined?null:Array.isArray(value)?value.map(canonicalValue):value&&typeof value==='object'?Object.fromEntries(Object.entries(value).sort(([a],[b])=>a.localeCompare(b)).map(([key,v])=>[key,canonicalValue(v)])):value;
export function canvasObjectSourceCandidates(object:CanvasSourceObject):string[]{
 const metadata=object.metadata??{},parameters=metadata.parameters&&typeof metadata.parameters==='object'?metadata.parameters as Record<string,unknown>:{};
 const imagePath=(v:unknown)=>typeof v==='string'&&/^[A-Za-z0-9][A-Za-z0-9_-]{0,127}$/.test(v.trim())?`generated-images/${v.trim()}`:undefined;
 return Array.from(new Set([metadata.galleryStoragePath,metadata.storagePath,...sourceFields.map(key=>parameters[key]),imagePath(metadata.galleryImageId),imagePath(metadata.imageId),imagePath(parameters.imageId),object.src,metadata.galleryImageUrl].filter((v):v is string=>typeof v==='string'&&Boolean(v.trim()))));
}
export function canvasObjectProtectedIdentity(object:CanvasSourceObject){
 const metadata=object.metadata??{},parameters=metadata.parameters&&typeof metadata.parameters==='object'?metadata.parameters as Record<string,unknown>:{};
 return {version:'canvas-object-descriptor-v1' as const,objectId:object.id,imageId:metadata.imageId??null,generation:metadata.generation??null,sourceRevision:canonicalValue(metadata.sourceRevision),galleryStoragePath:metadata.galleryStoragePath??null,storagePath:metadata.storagePath??null,galleryImageId:canonicalValue(metadata.galleryImageId),galleryImageUrl:canonicalValue(metadata.galleryImageUrl),src:object.src??null,parameters:Object.fromEntries([...sourceFields,'imageId'].map(key=>[key,canonicalValue(parameters[key])])),candidates:canvasObjectSourceCandidates(object)};
}
export type CanvasObjectSourceProof={version:'canvas-object-source-v1';objectDescriptor:ReturnType<typeof canvasObjectProtectedIdentity>;objectDescriptorDigest:string;selectedSource:string;originalPngDigest:string;width:number;height:number};
export type VerifiedCanvasObjectSource=CanvasObjectSourceProof&{originalPngDataUrl:string};
function objectProof(value:VerifiedCanvasObjectSource):CanvasObjectSourceProof{const {originalPngDataUrl:_bytes,...proof}=value;return proof;}
async function assertObjectProof(proof:CanvasObjectSourceProof,original:Png){if(proof.version!=='canvas-object-source-v1'||proof.objectDescriptor?.version!=='canvas-object-descriptor-v1'||!proof.objectDescriptor.candidates.includes(proof.selectedSource)||proof.objectDescriptorDigest!==await protectedImageDigest(JSON.stringify(proof.objectDescriptor))||proof.originalPngDigest!==original.digest||proof.width!==original.width||proof.height!==original.height)fail('object_source_proof_mismatch');}
/** A verified promotion supplies bytes for the immutable proof view. Reuse the
 * same PNG/digest/dimension gate; the bridge owns the current descriptor gate. */
export async function verifyCanvasObjectProofPng(proof:CanvasObjectSourceProof,dataUrl:string):Promise<VerifiedCanvasObjectSource>{
 const original=await png(dataUrl);await assertObjectProof(proof,original);return {...proof,originalPngDataUrl:original.dataUrl};
}
export async function resolveCanvasProtectedObjectSource(object:CanvasSourceObject,resolve:(source:string)=>Promise<string>,assertCurrent:()=>void|Promise<void>,readCurrent:()=>CanvasSourceObject|null|undefined=()=>object):Promise<VerifiedCanvasObjectSource>{
 const descriptor=canvasObjectProtectedIdentity(object),digest=await protectedImageDigest(JSON.stringify(descriptor));
 const check=async()=>{await assertCurrent();const current=readCurrent();if(!current||!equal(canvasObjectProtectedIdentity(current),descriptor))fail('object_source_changed');};
 await check();let lastError:unknown;
 for(const selectedSource of descriptor.candidates){let original:Png;try{const url=await resolve(selectedSource);await check();original=await png(url);}catch(error){await check();lastError=error;continue;}await check();return {version:'canvas-object-source-v1',objectDescriptor:descriptor,objectDescriptorDigest:digest,selectedSource,originalPngDataUrl:original.dataUrl,originalPngDigest:original.digest,width:original.width,height:original.height};}
 throw lastError??new Error('canvas_protected_object_source_unavailable');
}
export async function assertCanvasBatchObjectSource(binding:CanvasProtectedBatchBinding,object:CanvasSourceObject|null|undefined){if(binding.source.kind!=='object')return;if(!object||object.id!==binding.source.objectId||await protectedImageDigest(JSON.stringify(canvasObjectProtectedIdentity(object)))!==binding.source.identityDigest)fail('object_source_changed');const batch=await loadCanvasProtectedBatch(binding);if(!batch.sourceProof||!equal(batch.sourceProof.objectDescriptor,canvasObjectProtectedIdentity(object)))fail('object_source_changed');}
export async function verifyCanvasPinnedObjectSource(binding:CanvasProtectedBatchBinding,object:CanvasSourceObject,resolve:(source:string)=>Promise<string>,assertCurrent:()=>void|Promise<void>,readCurrent:()=>CanvasSourceObject|null|undefined=()=>object):Promise<VerifiedCanvasObjectSource>{
 await assertCurrent();await assertCanvasBatchObjectSource(binding,object);const batch=await loadCanvasProtectedBatch(binding),proof=batch.sourceProof!;
 const check=async()=>{await assertCurrent();await assertCanvasBatchObjectSource(binding,readCurrent());};await check();
 // Only the bound locator may be resolved; an unavailable pinned source cannot select a fallback.
 const url=await resolve(proof.selectedSource);await check();const original=await png(url);await check();await assertObjectProof(proof,original);
 return {...proof,originalPngDataUrl:original.dataUrl};
}
export async function loadCanvasProtectedBatchForRequest(brandId:string,scopeId:string,requestId:string){const r=findWorkspaceArtifactPersisted(brandId,`canvas-protected-batch-${requestId}`,scopeId);if(!r.ok)throw r.error;const binding=(r.artifact?.metadata.canvasProtectedBatch as unknown as Batch|undefined)?.binding;if(!binding||binding.brandId!==brandId||binding.scopeId!==scopeId||binding.requestId!==requestId)fail('batch_identity_mismatch');return loadCanvasProtectedBatch(binding);}
