import type { LightchainFeature } from './lightchainParityCatalog';
import {
  GOAL_CANDIDATE_ROW_IDS,
  type GoalCandidateRowId,
} from '../features/lightchain/parityContract.ts';

type NonVideoGoalCandidateRowId = Exclude<GoalCandidateRowId, 'video-workstation' | 'video-detail'>;

/**
 * The unified workspace library is the explicit non-video compatibility
 * inventory. The homepage catalog intentionally stays card-oriented, while
 * this list keeps every deep Lightchain workflow reachable from one shell.
 */
const entries: Record<NonVideoGoalCandidateRowId, Omit<LightchainFeature, 'id' | 'route'>> = {
  'marketing-home': {
    title: 'マーケティングワークスペース',
    lightchainName: 'GenerateMarketing',
    description: '商品画像から販促素材、コピー、EC/SNS向けの案をまとめます。',
    category: 'recommended',
    status: 'workspace',
    capability: '依頼文、参考素材、シーン、保存',
    evidence: 'non-video compatibility route contract; generation pending',
    tags: ['EC', 'SNS', '販促'],
  },
  'marketing-detail': {
    title: 'マーケティング詳細キャンバス',
    lightchainName: 'GenerateMarketing.detail',
    description: 'AIアシスタントとレイヤーを使って販促ビジュアルを詰めます。',
    category: 'planning',
    status: 'workspace',
    capability: '商品画像、AI指示、レイヤー、用途',
    evidence: 'non-video compatibility route contract; generation pending',
    tags: ['レイヤー', 'アシスタント', 'ポスター'],
  },
  'ai-fitting': {
    title: 'AIフィッティング',
    lightchainName: 'VirtualFittingV2',
    description: '衣服、モデル、背景、ポーズを選び、着用画像へ進みます。',
    category: 'fitting',
    status: 'workspace',
    capability: '衣服画像、説明、モデル、ポーズ、背景',
    evidence: 'priority route; production generation pending',
    tags: ['着用画像', 'モデル', 'EC'],
  },
  'ai-fitting-reference': {
    title: 'AIフィッティング・参考画像',
    lightchainName: 'VirtualFitting.reference',
    description: 'モデル、ポーズ、背景の参考素材を保った着用画像フローです。',
    category: 'fitting',
    status: 'workspace',
    capability: '衣服、モデル参照、ポーズ参照、背景参照',
    evidence: 'non-video compatibility route contract; generation pending',
    tags: ['参考画像', 'ポーズ', '背景'],
  },
  'fitting-clothing-reference': {
    title: '衣服参考ライブラリ',
    lightchainName: 'VirtualFitting.clothingReference',
    description: '衣服画像をフィッティング用の参照素材として整理します。',
    category: 'fitting',
    status: 'workspace',
    capability: '衣服画像、カテゴリ、説明、再利用',
    evidence: 'non-video compatibility route contract; generation pending',
    tags: ['衣服', 'ライブラリ', '参照'],
  },
  'fitting-background-reference': {
    title: '背景参考ライブラリ',
    lightchainName: 'VirtualFitting.backgroundReference',
    description: '背景参考画像を撮影シーンの条件として管理します。',
    category: 'fitting',
    status: 'workspace',
    capability: '背景画像、背景説明、用途、再利用',
    evidence: 'non-video compatibility route contract; generation pending',
    tags: ['背景', '撮影', '参照'],
  },
  'wear-design-lab': {
    title: 'ウェアデザインラボ',
    lightchainName: 'ChangeDetail',
    description: '服のディテール変更を候補比較し、生成条件へ渡します。',
    category: 'recommended',
    status: 'workspace',
    capability: '対象箇所、変更説明、候補、保存',
    evidence: 'non-video compatibility route contract; generation pending',
    tags: ['ディテール', '企画', '比較'],
  },
  'wear-design-detail': {
    title: 'ウェアデザイン詳細',
    lightchainName: 'ChangeDetail.detail',
    description: '対象画像と変更範囲を確認して部分編集へ進みます。',
    category: 'planning',
    status: 'workspace',
    capability: '対象画像、変更範囲、変更説明、履歴',
    evidence: 'non-video compatibility route contract; generation pending',
    tags: ['部分編集', '変更範囲', '履歴'],
  },
  'model-library': {
    title: 'モデル企画ライブラリ',
    lightchainName: 'FittingModelLibrary',
    description: '顔、体型、サイズ、ポーズ、背景、アングルの条件を整理します。',
    category: 'fitting',
    status: 'workspace',
    capability: 'モデル候補、条件、model-matrix、保存',
    evidence: 'non-video compatibility route contract; generation pending',
    tags: ['モデル', '条件', 'ライブラリ'],
  },
  'fashion-studio': {
    title: 'ファッションスタジオ',
    lightchainName: 'OneClickIntegration',
    description: '服、モデル、背景、小物を一つの撮影セットにまとめます。',
    category: 'recommended',
    status: 'workspace',
    capability: '服、モデル、ポーズ、背景、小物、保存',
    evidence: 'non-video compatibility route contract; generation pending',
    tags: ['撮影', '背景', '小物'],
  },
  'design-agent': {
    title: 'デザインエージェント',
    lightchainName: 'ClothingDesignFlux',
    description: 'トレンドやテーマからシリーズ案を比較します。',
    category: 'recommended',
    status: 'workspace',
    capability: '企画条件、複数案、比較、保存',
    evidence: 'non-video compatibility route contract; generation pending',
    tags: ['トレンド', 'シリーズ', '企画'],
  },
  lab: {
    title: 'Heavy Chain Lab',
    lightchainName: 'laboratory',
    description: '生成前の仮説、素材、店舗・キャンペーン適性を確認します。',
    category: 'planning',
    status: 'workspace',
    capability: '実験、評価、候補、再開、保存',
    evidence: 'non-video compatibility route contract; generation pending',
    tags: ['実験', '評価', '検証'],
  },
  'print-design-project': {
    title: '柄・グラフィック',
    lightchainName: 'FlowerShapedDesign',
    description: '新規ファイル、最近の案件、事例からプリント制作を始めます。',
    category: 'graphics',
    status: 'workspace',
    capability: '新規ファイル、案件、事例、保存',
    evidence: 'non-video compatibility route contract; generation pending',
    tags: ['柄', 'グラフィック', '案件'],
  },
  'print-design-detail': {
    title: '柄・グラフィック詳細',
    lightchainName: 'FlowerShapedDesign.detail',
    description: '柄、配置、プリント範囲を確認して制作を進めます。',
    category: 'graphics',
    status: 'workspace',
    capability: '柄、配置、範囲、生成履歴',
    evidence: 'non-video compatibility route contract; generation pending',
    tags: ['配置', 'プリント', '履歴'],
  },
  'fabric-image': {
    title: '生地イメージ',
    lightchainName: 'FabricBody',
    description: 'モデル・デザイン画像と生地を組み合わせ、質感を確認します。',
    category: 'graphics',
    status: 'workspace',
    capability: '衣服、デザイン、生地、キーワード、保存',
    evidence: 'priority route; production generation pending',
    tags: ['生地', '質感', '試着'],
  },
  'line-generation': {
    title: '平絵生成',
    lightchainName: 'GenerateSketch',
    description: '参考画像から平絵や線画の生成条件を作ります。',
    category: 'graphics',
    status: 'workspace',
    capability: '参考画像、画像タイプ、生成種類、保存',
    evidence: 'non-video compatibility route contract; generation pending',
    tags: ['平絵', '線画', '参考画像'],
  },
  'line-to-real': {
    title: '線画の実写化',
    lightchainName: 'LineArtToReal',
    description: '線画を実写風の商品画像へつなぐ条件を保持します。',
    category: 'graphics',
    status: 'workspace',
    capability: '線画、タイプ、出力種類、source provenance',
    evidence: 'non-video compatibility route contract; generation pending',
    tags: ['線画', '実写化', '下絵'],
  },
  'pattern-vector': {
    title: 'パターンをベクター化',
    lightchainName: 'PatternToVector',
    description: '総柄をベクター化し、繰り返しと配色の方針を残します。',
    category: 'graphics',
    status: 'workspace',
    capability: 'パターン、リピート、ベクター、保存',
    evidence: 'non-video compatibility route contract; generation pending',
    tags: ['パターン', 'リピート', 'ベクター'],
  },
  'pattern-vector-pro': {
    title: 'パターンをベクター化 Pro',
    lightchainName: 'PatternToVectorPro',
    description: '量産向けの高度なベクター化方針を確認します。',
    category: 'graphics',
    status: 'workspace',
    capability: 'Pro変換、repeatSignature、保存',
    evidence: 'non-video compatibility route contract; generation pending',
    tags: ['Pro', '量産', 'ベクター'],
  },
  'printing-image': {
    title: 'プリントイメージ',
    lightchainName: 'PrintingImage',
    description: '服画像にプリントを配置し、スポット・全体の仕上がりを確認します。',
    category: 'graphics',
    status: 'workspace',
    capability: '服、プリント、配置範囲、出力解像度、保存',
    evidence: 'priority route; production generation pending',
    tags: ['プリント', '配置', '印刷'],
  },
  'image-repair': {
    title: '画像修正',
    lightchainName: 'FixDeformities',
    description: '画像の気になる部分を修正し、再利用できる素材にします。',
    category: 'fitting',
    status: 'workspace',
    capability: '対象画像、修正範囲、指示、保存',
    evidence: 'non-video compatibility route contract; generation pending',
    tags: ['修正', '補正', '再利用'],
  },
  'svg-convert': {
    title: '平絵をベクター化',
    lightchainName: 'SVGConvert',
    description: '平絵をSVGや生産向けのベクター素材へ変換します。',
    category: 'graphics',
    status: 'workspace',
    capability: '平絵、SVG、パス、保存',
    evidence: 'non-video compatibility route contract; generation pending',
    tags: ['SVG', '平絵', '生産'],
  },
  'model-face': {
    title: '顔変更',
    lightchainName: 'FittingModelCustomize.face',
    description: '衣服とポーズを保ち、モデルの顔条件だけを変更します。',
    category: 'fitting',
    status: 'workspace',
    capability: '元画像、顔参考画像、保存',
    evidence: 'non-video compatibility route contract; generation pending',
    tags: ['顔', 'モデル', '参照'],
  },
  'model-change': {
    title: 'モデル変更',
    lightchainName: 'ChangeModel',
    description: '衣服のサイズ感を保ちながら、メインモデルを変更します。',
    category: 'fitting',
    status: 'workspace',
    capability: '元画像、モデル参照、サイズ保持、保存',
    evidence: 'non-video compatibility route contract; generation pending',
    tags: ['モデル変更', 'サイズ', '着用'],
  },
  'body-shape': {
    title: '体型',
    lightchainName: 'FittingModelChangeBodyShape',
    description: '服装を保ち、モデルの体型だけを調整します。',
    category: 'fitting',
    status: 'workspace',
    capability: '元画像、性別、体型、保存',
    evidence: 'non-video compatibility route contract; generation pending',
    tags: ['体型', 'モデル', '差分'],
  },
  'clothing-size': {
    title: '服のサイズ',
    lightchainName: 'FittingModelChangeBigSize',
    description: '衣服のサイズ条件を変えた着用画像へ進みます。',
    category: 'fitting',
    status: 'workspace',
    capability: '元画像、元サイズ、変更サイズ、保存',
    evidence: 'non-video compatibility route contract; generation pending',
    tags: ['サイズ', '着用', '比較'],
  },
  'pose-change': {
    title: 'ポーズ',
    lightchainName: 'ChangePosture',
    description: '衣服とモデルを保ち、ポーズだけを変更します。',
    category: 'fitting',
    status: 'workspace',
    capability: '元画像、ポーズ、参考画像、保存',
    evidence: 'non-video compatibility route contract; generation pending',
    tags: ['ポーズ', 'モデル', '撮影'],
  },
  'background-change': {
    title: '背景',
    lightchainName: 'ChangeBackground',
    description: 'モデルと衣服を保ち、撮影背景だけを変更します。',
    category: 'fitting',
    status: 'workspace',
    capability: '元画像、背景、説明、保存',
    evidence: 'non-video compatibility route contract; generation pending',
    tags: ['背景', '撮影', '差分'],
  },
  'angle-change': {
    title: 'アングル',
    lightchainName: 'ChangePerspective',
    description: '衣服とモデルを保ち、カメラアングルを変更します。',
    category: 'fitting',
    status: 'workspace',
    capability: '元画像、水平、垂直、ズーム、保存',
    evidence: 'non-video compatibility route contract; generation pending',
    tags: ['アングル', 'カメラ', '比較'],
  },
  'model-custom': {
    title: 'モデルカスタマイズ',
    lightchainName: 'FittingModelCustomize',
    description: '年齢、国籍、肌色、体型などから専用モデル条件を作ります。',
    category: 'fitting',
    status: 'workspace',
    capability: '性別、年齢、国籍、肌色、体型、保存',
    evidence: 'non-video compatibility route contract; generation pending',
    tags: ['カスタム', 'モデル', '条件'],
  },
  'custom-style': {
    title: 'カスタムスタイル',
    lightchainName: 'CustomStyle',
    description: 'ブランドのトーンやターゲットを生成条件へつなぎます。',
    category: 'planning',
    status: 'workspace',
    capability: 'ブランド、トーン、ターゲット、保存',
    evidence: 'non-video compatibility route contract; generation pending',
    tags: ['ブランド', 'トーン', 'スタイル'],
  },
};

const routeAliases: Partial<Record<NonVideoGoalCandidateRowId, readonly string[]>> = {
  'marketing-home': ['/marketing'],
  'ai-fitting': ['/model', '/fitting'],
  'wear-design-lab': ['/flow/orientedDesign'],
  'model-library': ['/model-library/model-custom-form', '/models'],
  'fashion-studio': ['/flow/integration', '/studio'],
  'design-agent': ['/agent', '/creator'],
  lab: ['/flow/laboratory', '/lab'],
  'print-design-project': ['/editor/patternDesign', '/printing'],
  'fabric-image': ['/tools/fabric', '/lightchain/fabric-image'],
  'line-to-real': ['/tools/line-draft-to-tile'],
  'pattern-vector-pro': ['/tools/vector-special'],
  'printing-image': ['/tools/printing', '/lightchain/printing-image'],
  'image-repair': ['/tools/reactor'],
  'svg-convert': ['/tools/svg-convert'],
  'custom-style': ['/model-base/style', '/brand/settings'],
};

export const lightchainUnifiedFeatureCatalog: readonly LightchainFeature[] = Object.freeze(
  GOAL_CANDIDATE_ROW_IDS
    .filter((id): id is NonVideoGoalCandidateRowId => id !== 'video-workstation' && id !== 'video-detail')
    .map((id) => ({
      id,
      route: `/lightchain/${id}`,
      ...entries[id],
      betaIncluded: true,
    })),
);

export const lightchainUnifiedFeatureCount = lightchainUnifiedFeatureCatalog.length;

export const getLightchainUnifiedRouteAliases = (id: string): readonly string[] => (
  routeAliases[id as NonVideoGoalCandidateRowId] ?? []
);

export const buildLightchainUnifiedFeatureHref = (feature: LightchainFeature): string => {
  const aliases = getLightchainUnifiedRouteAliases(feature.id);
  return aliases[0] ?? feature.route;
};
