import React from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter,Routes,Route} from 'react-router-dom';
import {Toaster} from 'react-hot-toast';
// No product module is imported until fail-closed transport + controlled HTTPS
// native image decoding have been proved. Product functions are never replaced.
const nativeFetch=globalThis.fetch.bind(globalThis),runKey='canvas-react-probe-run';
const runId=new URL(location.href).searchParams.get('run')||sessionStorage.getItem(runKey)||crypto.randomUUID();
if(!/^[0-9a-f-]{36}$/.test(runId))throw new Error('fixture_run_invalid');sessionStorage.setItem(runKey,runId);
const prefix='/__canvas-react/'+runId,apiOrigin='https://canvas-protected-api.invalid',mediaOrigin='https://canvas-protected-media.invalid';
let mounted=false,negativeArmed=false,noteAdded=false,canvasStore:any,server:any,baseline:any,identityCheckpoint:any,ackObserved=0,hadPending=false;
const errors:string[]=[],networkBlocked:string[]=[];const nativeJSON=async(path:string,body?:unknown)=>{const response=await nativeFetch(prefix+path,{method:body===undefined?'GET':'POST',headers:{'content-type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});const result=await response.json();if(!response.ok)throw new Error(result.error);return result;};
const event=(type:string,info:unknown={})=>nativeJSON('/event',{type,info}).catch(error=>errors.push(String(error)));
const apiAllowed=(path:string,method:string)=>method==='POST'&&['/v1/provider-actions/edit-image','/v1/workspace-artifacts','/v1/canvas-documents'].includes(path)||method==='PATCH'&&/^\/v1\/canvas-documents\/[0-9a-f-]{36}$/.test(path)||method==='GET'&&(/^\/v1\/(workspace-artifacts|image-ai\/requests|canvas-documents)\/[0-9a-f-]{36}$/.test(path)||['/v1/media/read','/v1/generated-images','/v1/folders','/v1/image-folders','/v1/tags','/v1/style-presets','/v1/brands','/v1/profile','/v1/canvas-documents','/v1/workspace-execution-steps'].includes(path));
const addConcurrentNote=()=>{if(noteAdded||!canvasStore)return;noteAdded=true;canvasStore.getState().addObject({type:'text',text:'保存応答待ち中の同時注記 '+runId.slice(0,8),x:100,y:335,width:360,height:45,rotation:0,scaleX:1,scaleY:1,opacity:1,visible:true,locked:false,label:'同時 fixture 注記',fontSize:20,fill:'#f7db7b'});void event('note-added');};
globalThis.fetch=(async(input:RequestInfo|URL,init?:RequestInit)=>{
 const request=new Request(typeof input==='string'&&!/^[a-z]+:/i.test(input)?new URL(input,location.origin):input,init),url=new URL(request.url);
 if(url.protocol==='data:'||url.protocol==='blob:'&&url.origin===location.origin)return nativeFetch(input,init);
 if(url.origin===mediaOrigin&&new RegExp('^/'+runId+'/[A-Za-z0-9_-]+\\.png$').test(url.pathname))return nativeFetch(input,init); // SW, never the public network.
 let target:string;
 if(url.origin===apiOrigin&&apiAllowed(url.pathname,request.method))target=prefix+url.pathname+url.search;
 else if(url.origin===location.origin&&['/api/auth/get-session','/api/auth/ok'].includes(url.pathname)&&request.method==='GET')target=url.pathname;
 else if(url.origin===location.origin&&url.pathname.startsWith(prefix+'/'))target=url.pathname+url.search;
 else{networkBlocked.push(url.toString());void event('network-blocked',{url:url.toString()});throw new Error('fixture_undeclared_network:'+url.toString());}
 const headers=new Headers(request.headers);headers.set('x-fixture-run',runId);
 if(url.pathname==='/v1/provider-actions/edit-image'){const body=await request.clone().json(),geometry=body.protectedOpenAIProjection?.candidate;if(!geometry)throw new Error('fixture_actual_prepared_geometry_missing');const pngs=Array.from({length:4},(_,index)=>{const canvas=document.createElement('canvas');canvas.width=geometry.width;canvas.height=geometry.height;const ctx=canvas.getContext('2d')!;ctx.fillStyle=`rgb(${40+index*45},${80+index*25},${180-index*35})`;ctx.fillRect(0,0,canvas.width,canvas.height);return canvas.toDataURL('image/png');});await nativeJSON('/candidate-pngs',{requestId:headers.get('idempotency-key'),geometry,pngs});}
 if(url.pathname==='/v1/provider-actions/edit-image'&&negativeArmed){negativeArmed=false;setTimeout(()=>{const source=canvasStore?.getState().objects.find((o:any)=>o.id==='probe-source');if(source){canvasStore.getState().updateObject(source.id,{metadata:{...source.metadata,sourceRevision:{...source.metadata.sourceRevision,revision:'changed-'+runId}}});void event('source-mutated');}},500);}
 const response=await nativeFetch(target,{method:request.method,headers,signal:request.signal,credentials:'omit',...(request.method==='GET'||request.method==='HEAD'?{}:{body:await request.clone().text()})});
 if(response.status===503){const payload=await response.clone().json().catch(()=>null);if(payload?.concurrentFixtureNote)addConcurrentNote();}return response;
}) as typeof fetch;
navigator.serviceWorker?.addEventListener('message',e=>{if(e.data?.type==='fixture-network-blocked'){networkBlocked.push(e.data.url);void event('network-blocked',{url:e.data.url});}});
window.addEventListener('error',e=>{errors.push(e.message);void event('error',{message:e.message});});window.addEventListener('unhandledrejection',e=>{errors.push(String(e.reason));void event('error',{message:String(e.reason)});});
const makeOriginal=()=>{const canvas=document.createElement('canvas');canvas.width=160;canvas.height=120;const ctx=canvas.getContext('2d')!,data=ctx.createImageData(160,120);for(let y=0;y<120;y++)for(let x=0;x<160;x++){const at=(y*160+x)*4;data.data.set([20+x,30+y,180-(x%90),x<8?128:255],at);}ctx.putImageData(data,0,0);return canvas.toDataURL('image/png');};
const nativePixels=async(url:string)=>{const image=new Image();image.crossOrigin='anonymous';await new Promise<void>((resolve,reject)=>{image.onload=()=>resolve();image.onerror=()=>reject(new Error('fixture_https_media_unavailable'));image.src=url;});const canvas=document.createElement('canvas');canvas.width=image.naturalWidth;canvas.height=image.naturalHeight;const ctx=canvas.getContext('2d')!;ctx.drawImage(image,0,0);return{width:canvas.width,height:canvas.height,pixels:ctx.getImageData(0,0,canvas.width,canvas.height).data};};
const checkpoint=document.querySelector('#checkpoint')!,resultNode=document.querySelector('#probe-result')!;
try{
 server=await nativeJSON('/bootstrap',{originalPng:makeOriginal()});
 if(!('serviceWorker'in navigator))throw new Error('fixture_https_media_unavailable');await navigator.serviceWorker.register('/__canvas-react-sw.js',{scope:'/'});await navigator.serviceWorker.ready;
 if(!navigator.serviceWorker.controller)await new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('fixture_https_media_unavailable')),8000);navigator.serviceWorker.addEventListener('controllerchange',()=>{clearTimeout(timer);resolve();},{once:true});});
 const decoded=await nativePixels(`${mediaOrigin}/${runId}/original.png`);if(decoded.width!==160||decoded.height!==120)throw new Error('fixture_https_media_unavailable');const proofResponse=await fetch(`${mediaOrigin}/${runId}/original.png`);if(!proofResponse.ok||await proofResponse.blob().then(b=>b.type)!=='image/png')throw new Error('fixture_https_media_unavailable');
 checkpoint.textContent='HTTPS SW controller/native PNG decode confirmed. Seed the unsaved draft, then use actual Canvas UI.';await event('ready',{controller:!!navigator.serviceWorker.controller,nativeGeometry:[decoded.width,decoded.height]});
 const [{CanvasEditorPage},{useAuthStore},{useCanvasStore},authModule,assets,apiModule,batchCore,local,contract,pending,saveRecovery,promotionBridge]=await Promise.all([import('../../src/pages/CanvasEditorPage'),import('../../src/stores/authStore'),import('../../src/stores/canvasStore'),import('../../src/lib/auth'),import('../../src/lib/canvasLocalAssets'),import('../../src/lib/cloudflareApi'),import('../../src/lib/canvasProtectedBatchComposite'),import('../../src/lib/localWorkspaceArtifacts'),import('../../src/lib/protectedImageEditContract'),import('../../src/lib/cloudflareImagePendingStore'),import('../../src/lib/canvasDocumentSaveRecovery'),import('../../src/lib/canvasProtectedSourcePromotionBridge')]);await import('../../src/index.css');
 canvasStore=useCanvasStore;const api=apiModule.cloudflareDataPlane;if(!api||api.origin!==apiOrigin)throw new Error('fixture_api_origin_unbound');const session=await authModule.auth.getSession();const fixtureSession=session.data.session;if(session.error||!fixtureSession||fixtureSession.user.id!==server.userId)throw new Error('fixture_auth_unbound');
 const brand={id:server.brandId,owner_id:server.userId,name:'Heavy Chain Workspace',brand_colors:[],logo_url:null,tone_description:null,target_audience:null,created_at:server.createdAt,updated_at:server.createdAt};
 useAuthStore.setState({user:fixtureSession.user,currentBrand:brand,accessibleBrands:[brand],isInitialized:true,isLoading:false,authRecoveryRequired:false,authServiceUnavailable:false,brandState:{status:'success_nonempty',userId:server.userId,requestGeneration:1,confirmedBrandIds:[server.brandId],error:null}});
 localStorage.setItem('heavy_chain_canvas_guide_completed:'+server.userId,'true');const sourceKey='canvas-react-native-'+runId,sourceReference=assets.buildLocalCanvasAssetReference(sourceKey);
 const stateFields=(s:any)=>({objects:structuredClone(s.objects),history:structuredClone(s.history),historyIndex:s.historyIndex,selectedIds:[...s.selectedIds],name:s.currentProjectName,view:{zoom:s.zoom,panX:s.panX,panY:s.panY,gridVisible:s.gridVisible,snapToGrid:s.snapToGrid,gridSize:s.gridSize}});
 const mount=()=>{if(mounted)return;mounted=true;void event('product-mount',{bootstrapCount:server.mounts});createRoot(document.querySelector('#root')!).render(<BrowserRouter><Routes><Route path="/canvas/:projectId" element={<CanvasEditorPage/>}/></Routes><Toaster/></BrowserRouter>);};
 const seed=async()=>{if(mounted)throw new Error('fixture_already_mounted');if(server.events.some((e:any)=>e.type==='baseline'))throw new Error('fixture_cannot_reseed_existing_baseline');const sourceBlob=await(await nativeFetch(server.originalPng)).blob();await assets.putLocalCanvasAsset(sourceKey,sourceBlob);const sourceMetadata=await import('../../src/features/canvasSourceMetadata').then(m=>m.buildLocalUploadSourceMetadata(sourceBlob,{width:160,height:120}));
  const base={rotation:0,scaleX:1,scaleY:1,opacity:1,locked:false,visible:true},source={...base,id:'probe-source',type:'image' as const,x:100,y:110,width:240,height:180,zIndex:1,src:sourceReference,label:'原寸 native 元画像',metadata:{feature:'local-upload',generation:0,...sourceMetadata}},ordinary={...base,id:'probe-ordinary',type:'text' as const,x:100,y:300,width:360,height:38,zIndex:2,text:'元の通常コンテンツは保持 '+runId.slice(0,8),label:'通常テキスト',fontSize:20,fill:'#fff'};
  useCanvasStore.setState({currentProjectId:null,currentProjectName:'Native四候補保存復旧',projects:[],objects:[source,ordinary],history:[[ordinary],[source,ordinary]],historyIndex:1,selectedIds:['probe-source'],zoom:.8,panX:35,panY:20,gridVisible:false,snapToGrid:false,gridSize:24});baseline=stateFields(useCanvasStore.getState());sessionStorage.setItem('canvas-react-baseline',JSON.stringify(baseline));await event('baseline',baseline);history.replaceState(null,'','/canvas/new');mount();checkpoint.textContent='Mounted real unsaved Canvas. Use source image partial-edit menu, paint a mask, enter prompt and submit.';};
 useCanvasStore.subscribe(s=>{if(!identityCheckpoint&&baseline&&s.currentProjectId?.startsWith('local-')){identityCheckpoint={localId:s.currentProjectId,preserved:JSON.stringify(stateFields(s))===JSON.stringify(baseline),actual:stateFields(s)};sessionStorage.setItem('canvas-react-identity',JSON.stringify(identityCheckpoint));void event('identity',identityCheckpoint);}});
 baseline=JSON.parse(sessionStorage.getItem('canvas-react-baseline')||'null');identityCheckpoint=JSON.parse(sessionStorage.getItem('canvas-react-identity')||'null');
 if(server.events.some((e:any)=>e.type==='baseline')){noteAdded=useCanvasStore.getState().objects.some(o=>o.type==='text'&&o.text?.includes('同時注記'));mount();checkpoint.textContent='Reloaded persisted actual bookmark. Use actual「このCanvasへ復旧」, verify dedup, then manual「保存」.';}
 let busy=false,lastSnapshot:any=null;
 const read=async()=>{server=await nativeJSON('/state');const s=useCanvasStore.getState(),ids=Object.keys(server.requests),requestId=ids[0],request=requestId?server.requests[requestId]:null;let batch:any,proofError:string|null=null,finals:any[]=[];if(request){try{batch=await batchCore.loadCanvasProtectedBatch(request.body.canvasProtectedBatchBinding);const original=await nativePixels(batch.original.dataUrl),mask=await nativePixels(batch.mask.dataUrl);for(let index=0;index<4;index++){const id='wa-'+await contract.protectedImageSaveRequestId(requestId,index),artifact=local.findWorkspaceArtifactPersisted(server.brandId,id,server.userId);if(!artifact.ok||!artifact.artifact){finals.push({index,id,missing:true});continue;}const pixels=await nativePixels(artifact.artifact.imageUrl);let outside=0,mismatch=0;for(let at=0;at<original.pixels.length;at+=4)if(mask.pixels[at+3]===255){outside++;for(let channel=0;channel<4;channel++)if(original.pixels[at+channel]!==pixels.pixels[at+channel])mismatch++;}const candidate=local.findWorkspaceArtifactPersisted(server.brandId,`canvas-protected-candidate-${requestId}-${index}`,server.userId);finals.push({index,id,nativeDigest:await contract.protectedImageDigest(artifact.artifact.imageUrl),width:pixels.width,height:pixels.height,protectedPixels:outside,protectedRgbaMismatches:mismatch,proofState:candidate.ok?(candidate.artifact?.metadata.canvasProtectedCandidate as any)?.stage:null});}}catch(error){proofError=String(error);}}
  const candidates=s.objects.filter(o=>(o.metadata?.parameters?.imageAICompletion as any)?.requestId===requestId),pendingEntries=await api.listPendingProtectedImageEdits(server.brandId),key=request?await import('../../src/lib/cloudflareImageAI').then(m=>m.durableImageRecoveryKey(api.origin,server.userId,'edit-image',request.body)):undefined,pendingIdentity=key?await pending.readPendingIdentity(key):null;
  if(pendingIdentity?.state==='present')hadPending=true;if(!hadPending&&request&&server.events.some((e:any)=>e.type==='record'&&e.info?.pendingIdentity?.state==='present'))hadPending=true;
  if(hadPending&&pendingIdentity?.state==='absent'&&pendingEntries.length===0&&ackObserved===0){ackObserved=1;await event('ack-cleanup-observed',{requestId,serverDoc:server.document?.id,revision:server.document?.revision});}
  const productMountEvents=server.events.filter((e:any)=>e.type==='product-mount'),reloadBootstrapIndex=productMountEvents[1]?.info?.bootstrapCount;const generationAfterProductReload=Number.isInteger(reloadBootstrapIndex)?server.generationAdmissions-server.mountWrites[reloadBootstrapIndex-1].generationAdmissions:0;
  const document=s.currentProjectId,cache=document&&/^[0-9a-f-]{36}$/.test(document)?saveRecovery.readCanvasSaveRecovery({origin:api.origin,userId:server.userId,brandId:server.brandId},document):null;
  // Compare complete originals inside the read-only bridge inspector, then
  // project for display. No signed-media/provider reads or recovery are made.
  const safeDiagnostic=(value:unknown)=>{
    const record=(v:unknown):Record<string,unknown>=>v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,unknown>:{};
    const v=record(value),id=(x:unknown)=>typeof x==='string'&&/^[a-zA-Z0-9_-]{1,160}$/.test(x)?x:null;
    const digest=(x:unknown)=>typeof x==='string'&&/^[a-f0-9]{64}$/.test(x)?x:null;
    const integer=(x:unknown)=>typeof x==='number'&&Number.isSafeInteger(x)&&x>=0?x:null;
    const locator=(x:unknown)=>{
      if(typeof x!=='string')return null;
      if(/^(generated-images\/[a-zA-Z0-9_-]{1,128}|local-canvas-asset:\/\/[a-zA-Z0-9_-]{1,160})$/.test(x))return x;
      try{const url=new URL(x);return ['https:','http:'].includes(url.protocol)&&!url.username&&!url.password?url.origin+url.pathname:null;}catch{return null;}
    };
    const revision=(x:unknown)=>{const r=record(x);return {algorithm:r.algorithm==='sha-256'?'sha-256':null,hash:digest(r.hash),revision:typeof r.revision==='string'&&/^sha256:[a-f0-9]{64}$/.test(r.revision)?r.revision:null,width:integer(r.width),height:integer(r.height),sizeBytes:integer(r.sizeBytes),mimeType:r.mimeType==='image/png'?'image/png':null};};
    const descriptor=(x:unknown)=>{
      const d=record(x),p=record(d.parameters),paths=['galleryStoragePath','storagePath','remoteStoragePath','sourceStoragePath','backendStoragePath'];
      return {version:d.version==='canvas-object-descriptor-v1'?d.version:null,objectId:id(d.objectId),imageId:id(d.imageId),generation:integer(d.generation),sourceRevision:revision(d.sourceRevision),galleryStoragePath:locator(d.galleryStoragePath),storagePath:locator(d.storagePath),galleryImageId:id(d.galleryImageId),galleryImageUrl:locator(d.galleryImageUrl),src:locator(d.src),
        parameters:Object.fromEntries([...paths.map(key=>[key,locator(p[key])]),['imageId',id(p.imageId)]]),
        parameterKinds:Object.fromEntries([...paths,'imageId'].map(key=>[key,p[key]===null?'null':Array.isArray(p[key])?'array':typeof p[key]])),
        candidates:Array.isArray(d.candidates)?d.candidates.map(locator).filter((item):item is string=>item!==null):[]};
    };
    const proof=(x:unknown)=>{const p=record(x);return {version:p.version==='canvas-object-source-v1'?p.version:null,objectDescriptor:descriptor(p.objectDescriptor),objectDescriptorDigest:digest(p.objectDescriptorDigest),selectedSource:locator(p.selectedSource),originalPngDigest:digest(p.originalPngDigest),width:integer(p.width),height:integer(p.height)};};
    const safeScope=(x:unknown)=>{const s=record(x);return {origin:locator(s.origin),userId:id(s.userId),brandId:id(s.brandId)};};
    const promotion=record(v.promotion),binding=record(promotion.binding),remote=record(promotion.remote),sourceIdentity=record(binding.sourceIdentity);
    // Complete originals are compared before projection. Arbitrary nested
    // metadata is never copied into the reporter, even under known path keys.
    const matches=(a:unknown,b:unknown)=>a!==undefined&&b!==undefined&&a!==null&&b!==null?JSON.stringify(a)===JSON.stringify(b):null;
    const immutable=record(v.immutableSourceProof);
    const comparisons={currentMatchesOriginal:matches(v.currentDescriptor,immutable.objectDescriptor),currentMatchesExpected:matches(v.currentDescriptor,v.expectedDescriptor),returnedProofMatchesImmutable:matches(v.proof,v.immutableSourceProof),promotionMatchesScope:matches(binding.scope,v.scope),selectedSourceMatchesLocalReference:matches(immutable.selectedSource,binding.localReference)};
    const reason=typeof v.reason==='string'&&(/^(canvas_protected_|canvas_source_promotion_|image_input_|image_pending_|canvas_save_)[a-z0-9_]+$/.test(v.reason)||['batch_source_or_pending_missing','raw_and_materialized_png_checks_unperformed'].includes(v.reason))?v.reason:'diagnostic_unavailable';
    return {status:v.status==='unproven_pixels'?'unproven_pixels':'unproven',reason,comparisons,currentDescriptor:descriptor(v.currentDescriptor),immutableSourceProof:proof(v.immutableSourceProof),proof:proof(v.proof),expectedDescriptor:descriptor(v.expectedDescriptor),
      promotion:{stage:promotion.stage==='verified'?'verified':promotion.stage==='dispatched'?'dispatched':null,requestId:id(binding.requestId),scope:safeScope(binding.scope),localReference:locator(binding.localReference),sourceIdentity:{kind:sourceIdentity.kind==='local-upload'?'local-upload':null,hash:digest(sourceIdentity.hash)},sourceRevision:revision(binding.sourceRevision),rawSha256:digest(binding.rawSha256),sizeBytes:integer(binding.sizeBytes),width:integer(binding.width),height:integer(binding.height),mimeType:binding.mimeType==='image/png'?'image/png':null,remote:{jobId:id(remote.jobId),imageId:id(remote.imageId),storagePath:locator(remote.storagePath)}},scope:safeScope(v.scope),rawPngVerification:'unperformed',materializedPngVerification:'unperformed'};
  };
  let promotedSourceDiagnostic:unknown={status:'unproven',reason:'batch_source_or_pending_missing',rawPngVerification:'unperformed',materializedPngVerification:'unperformed'};
  const sourceObject=batch?.binding.source.kind==='object'?s.objects.find(o=>o.id===batch.binding.source.objectId):undefined,entry=pendingEntries.find(e=>e.requestId===requestId),auth=useAuthStore.getState();
  if(batch&&sourceObject&&entry&&auth.user?.id&&auth.currentBrand?.id){const inspection=await promotionBridge.inspectCanvasProtectedSourcePromotionBridge({binding:batch.binding,object:sourceObject,scope:{origin:api.origin,userId:auth.user.id,brandId:auth.currentBrand.id},canvasProjectId:document,canvasProjectAliases:cache?.snapshot.sourceProjectIds??[],pending:entry});promotedSourceDiagnostic=safeDiagnostic({...inspection,currentDescriptor:batchCore.canvasObjectProtectedIdentity(sourceObject),immutableSourceProof:batch.sourceProof,scope:{origin:api.origin,userId:auth.user.id,brandId:auth.currentBrand.id}});}
  return{runId,route:location.pathname,bootstrapCount:server.mounts,productMountCount:productMountEvents.length,currentDoc:document,localDoc:identityCheckpoint?.localId??null,identityPreserved:identityCheckpoint?.preserved??null,objects:s.objects.map(o=>({id:o.id,type:o.type,label:o.label,text:o.text,imageId:o.metadata?.imageId,candidateIndex:o.metadata?.parameters?.candidateIndex})),view:{zoom:s.zoom,panX:s.panX,panY:s.panY},historyIndex:s.historyIndex,selection:s.selectedIds,promotedSourceDiagnostic,originalDigest:batch?.original.digest,originalDimensions:batch?[batch.original.width,batch.original.height]:null,finals,proofError,placements:candidates.length,uniquePlacements:new Set(candidates.map(o=>o.metadata?.imageId)).size,pendingEntries:pendingEntries.map(e=>({requestId:e.requestId,canvasProjectId:e.canvasProjectId})),pendingIdentity,cache:cache?{revision:cache.revision,pending:!!cache.pending,sourceProjectIds:cache.snapshot.sourceProjectIds}:null,ackCleanupObserved:ackObserved,sourceIndexedDB:!!await assets.getLocalCanvasAsset(sourceReference),generationAdmissions:server.generationAdmissions,generationPosts:server.generationPosts,generationAfterReload:generationAfterProductReload,requestReads:server.requestReads,finalSavePosts:server.savePostsByIndex,savedPostRepeats:Object.values(server.savePostsByIndex as Record<string,number>).some(n=>n>1),recoveryUIAttempts:server.events.filter((e:any)=>e.type==='recovery-ui').length,documentLogicalWrites:server.documentLogicalWrites,documentHTTPAttempts:server.documentAttempts,documentRevision:server.document?.revision,documentNote:server.document?.snapshot.objects.some((o:any)=>o.text?.includes('同時注記')),mountWrites:server.mountWrites,readHold:server.controls.readHold,persistence:document&&window.document.querySelector('[data-testid="canvas-persistence-status"]')?.textContent,networkBlocked,errors};};
 const refresh=async()=>{if(busy)return;busy=true;try{lastSnapshot=await read();resultNode.textContent=JSON.stringify(lastSnapshot,null,2);}catch(error){errors.push(String(error));}finally{busy=false;}};
 document.querySelector('#seed')!.addEventListener('click',()=>void seed().catch(e=>{checkpoint.textContent=String(e);}));
 document.querySelector('#fault')!.addEventListener('click',()=>void nativeJSON('/control',{kind:'document-loss'}).then(()=>{checkpoint.textContent='Fault armed. Click actual Canvas「保存」; response and immediate readback fail, concurrent note is added.';}));
 document.querySelector('#negative')!.addEventListener('click',()=>{if(server.generationAdmissions||server.documentLogicalWrites)throw new Error('fixture_negative_requires_fresh_origin_run');negativeArmed=true;void nativeJSON('/control',{kind:'negative-pause'}).then(()=>{checkpoint.textContent='Negative source fence armed: actual provider service pauses; source metadata changes while awaiting it. Actual fence must prevent saves/placement.';});});
 document.querySelector('#reload')!.addEventListener('click',()=>void(async()=>{await refresh();await event('reload',lastSnapshot);location.reload();})());
 document.querySelector('#record')!.addEventListener('click',()=>void(async()=>{await refresh();await event('record',lastSnapshot);checkpoint.textContent='Readonly checkpoint recorded; this is evidence, not an automatic acceptance verdict.';})());
 document.addEventListener('click',e=>{const button=(e.target as Element)?.closest('button');if(button?.textContent?.trim()==='このCanvasへ復旧')void event('recovery-ui',{mount:server.mounts});});
 setInterval(()=>void refresh(),1600);await refresh();
}catch(error){const message=String(error);errors.push(message);checkpoint.textContent=message.includes('fixture_https_media_unavailable')?'fixture_https_media_unavailable: no product page mounted':message;resultNode.textContent=JSON.stringify({runId,mounted,errors,networkBlocked},null,2);await event('error',{message});}
