import test,{after} from 'node:test';
import assert from 'node:assert/strict';
import {createHash,randomUUID} from 'node:crypto';
import {createServer} from 'vite';
import sharp from 'sharp';
import fs from 'node:fs/promises';
import ts from 'typescript';
import vm from 'node:vm';
const vite=await createServer({configFile:false,envFile:false,server:{middlewareMode:true},appType:'custom',logLevel:'silent',optimizeDeps:{noDiscovery:true,include:[]}});
const promotion=await vite.ssrLoadModule('/src/lib/canvasSourcePromotion.ts'),metadata=await vite.ssrLoadModule('/src/features/canvasSourceMetadata.ts');
const old={localStorage:globalThis.localStorage,navigator:Object.getOwnPropertyDescriptor(globalThis,'navigator')};after(async()=>{globalThis.localStorage=old.localStorage;if(old.navigator)Object.defineProperty(globalThis,'navigator',old.navigator);else delete globalThis.navigator;await vite.close();});
const hash=v=>createHash('sha256').update(v).digest('hex');
function store(){const map=new Map();return{map,getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)};}
function browserLockService(){const tails=new Map(),active=new Map(),events=[];return{events,context(owner){return{request:async(name,options,callback)=>{assert.equal(options.mode,'exclusive');events.push(['request',owner,name]);const before=tails.get(name)??Promise.resolve();let release;const gate=new Promise(r=>release=r);tails.set(name,gate);await before;assert.equal(active.get(name)??0,0);active.set(name,1);events.push(['acquire',owner,name]);try{return await callback({name,mode:'exclusive'});}finally{active.set(name,0);events.push(['release',owner,name]);release();}}};}};}
async function fixture(){globalThis.localStorage=store();Object.defineProperty(globalThis,'navigator',{value:{locks:browserLockService().context('default-test-tab')},configurable:true});const bytes=await sharp({create:{width:160,height:120,channels:4,background:{r:23,g:41,b:77,alpha:.75}}}).png().toBuffer(),blob=new Blob([bytes],{type:'image/png'}),key='canvas-react-native-'+randomUUID(),sourceMetadata=await metadata.buildLocalUploadSourceMetadata(blob,{width:160,height:120});const object={id:'original',type:'image',src:'local-canvas-asset://'+key,x:15,y:23,width:160,height:120,rotation:3,scaleX:1,scaleY:1,opacity:.8,locked:false,visible:true,zIndex:0,metadata:{feature:'local-upload',generation:0,...sourceMetadata}};const scope={origin:'https://source-api.test',userId:'alice',brandId:'brand'};let current=object;const remotes=new Map(),raw=new Map(),inputs=[],gets=[],refs=[];let failure=false;
 const options={scope,object,readCurrentObject:()=>current,assertCurrent:()=>{},getBlob:async reference=>{refs.push(reference);return reference===object.src?blob:null;},readDimensions:async value=>{const m=await sharp(Buffer.from(await value.arrayBuffer())).metadata();return{width:m.width,height:m.height};},blobDataUrl:async value=>'data:image/png;base64,'+Buffer.from(await value.arrayBuffer()).toString('base64'),readRemote:async id=>{gets.push(id);if(remotes.has(id))return remotes.get(id);throw new Error('cloudflare_api_404_workspace_artifact_not_found');},saveRemote:async input=>{inputs.push(structuredClone(input));const id='wa-'+input.requestId,result={success:true,remote:{jobId:id,imageId:id,storagePath:'generated-images/'+id}};if(failure)throw new Error('upload_response_unknown');remotes.set(input.requestId,result);raw.set(result.remote.storagePath,Buffer.from(input.imageUrl.split(',')[1],'base64'));return result;},signedRead:async path=>'https://source-media.test/'+path,fetchBytes:async url=>{const b=raw.get(url.replace('https://source-media.test/',''));assert(b,'unknown media forbidden');return Uint8Array.from(b).buffer;}};
 return{object,scope,options,bytes,blob,key,remotes,raw,inputs,gets,refs,setCurrent:o=>current=o,setFailure:v=>failure=v};
}
test('exact actual local key differs from digest: upload one raw PNG; canonical no-metadata GET and actual bytes prove alias; subsequent document failure retry has POST0',async()=>{
 const f=await fixture(),proof=await promotion.promoteCanvasLocalSource(f.options);assert.notEqual(f.key,f.object.metadata.sourceRevision.revision);assert.deepEqual(f.refs,[f.object.src]);assert.equal(f.inputs.length,1);assert.equal(f.inputs[0].featureType,'canvas-source-upload');assert.equal(f.inputs[0].sourceStoragePath,null);assert.equal(f.inputs[0].imageAI,undefined);assert.deepEqual(Buffer.from(f.inputs[0].imageUrl.split(',')[1],'base64'),f.bytes);assert.equal(proof.stage,'verified');assert.equal(proof.binding.rawSha256,hash(f.bytes));assert.equal(proof.remote.imageId,'wa-'+proof.binding.requestId);assert.equal(f.remotes.get(proof.binding.requestId).metadata,undefined);
 const alias=promotion.applyCanvasSourcePromotionAlias(f.object,proof);f.setCurrent(alias);assert.equal(alias.src,f.object.src);assert.deepEqual(alias.metadata.sourceIdentity,f.object.metadata.sourceIdentity);assert.deepEqual(alias.metadata.sourceRevision,f.object.metadata.sourceRevision);
 const before={objects:[f.object,{...f.object,id:'ordinary',type:'text',text:'keep me'}],history:[[f.object]],historyIndex:0,selectedIds:['original'],zoom:.81,panX:7,panY:29};const state={...before,objects:[alias,before.objects[1]]};for(const key of ['history','historyIndex','selectedIds','zoom','panX','panY'])assert.deepEqual(state[key],before[key]);
 const saved=promotion.canvasSaveObjectsWithPromotedSources(state.objects,f.scope);assert.equal(saved[0].metadata.parameters.remoteStoragePath,proof.remote.storagePath);assert.equal(saved[0].metadata.parameters.canvasSourcePromotion,undefined);assert.equal(saved[1],state.objects[1]);assert.equal(saved[0].src,f.object.src);assert.deepEqual(saved[0].metadata.sourceRevision,f.object.metadata.sourceRevision);
 const beforePosts=f.inputs.length;await promotion.promoteCanvasLocalSource({...f.options,object:alias});assert.equal(f.inputs.length,beforePosts);assert.equal(f.gets.length,3);assert.deepEqual(f.gets,[proof.binding.requestId,proof.binding.requestId,proof.binding.requestId]);assert.equal(proof.binding.requestId,(await promotion.promoteCanvasLocalSource({...f.options,object:alias})).binding.requestId);
});
test('unknown dispatch survives reload and confirmed404 remains GET-only, never another POST',async()=>{
 const f=await fixture();f.setFailure(true);await assert.rejects(promotion.promoteCanvasLocalSource(f.options),/upload_response_unknown/);assert.equal(f.inputs.length,1);const retained=[...localStorage.map.values()];assert.equal(JSON.parse(retained[0]).stage,'dispatched');f.setFailure(false);const reloaded=store();for(const[k,v]of localStorage.map)reloaded.setItem(k,v);globalThis.localStorage=reloaded;await assert.rejects(promotion.promoteCanvasLocalSource(f.options),/dispatch_unknown_get_only/);assert.equal(f.inputs.length,1);assert.equal(f.gets.length,3);
 const input=f.inputs[0],id='wa-'+input.requestId;f.remotes.set(input.requestId,{success:true,remote:{jobId:id,imageId:id,storagePath:'generated-images/'+id}});f.raw.set('generated-images/'+id,f.bytes);const proof=await promotion.promoteCanvasLocalSource(f.options);assert.equal(proof.stage,'verified');assert.equal(f.inputs.length,1);
});
for(const kind of ['uncertain-get','missing-blob','wrong-blob','wrong-size','wrong-dimensions','wrong-upload-data','source-src','source-revision','source-identity','source-remote-alias','scope','auth'])test(`${kind} prevents dispatch and alias`,async()=>{
 const f=await fixture(),options={...f.options};let asserted=0;
 if(kind==='uncertain-get')options.readRemote=async()=>{throw new Error('workspace_read_unknown');};
 if(kind==='missing-blob')options.getBlob=async()=>null;
 if(kind==='wrong-blob')options.getBlob=async()=>new Blob([f.bytes.subarray(0,-1)],{type:'image/png'});
 if(kind==='wrong-size')options.getBlob=async()=>({type:'image/png',size:f.bytes.length+1,arrayBuffer:async()=>Uint8Array.from(f.bytes).buffer});
 if(kind==='wrong-dimensions')options.readDimensions=async()=>({width:159,height:120});
 if(kind==='wrong-upload-data')options.blobDataUrl=async()=> 'data:image/png;base64,'+Buffer.from('wrong').toString('base64');
 if(kind.startsWith('source-'))options.getBlob=async()=>{const next=structuredClone(f.object);if(kind==='source-src')next.src+='changed';if(kind==='source-revision')next.metadata.sourceRevision.hash='f'.repeat(64);if(kind==='source-identity')next.metadata.sourceIdentity.hash='f'.repeat(64);if(kind==='source-remote-alias')next.metadata.galleryStoragePath='generated-images/foreign';f.setCurrent(next);return f.blob;};
 if(kind==='scope'||kind==='auth')options.assertCurrent=()=>{if(++asserted===3)throw new Error(kind==='scope'?'brand_changed':'session_changed');};
 await assert.rejects(promotion.promoteCanvasLocalSource(options));assert.equal(f.inputs.length,0);assert.equal(localStorage.map.size,0);
});
for(const kind of ['foreign-id','foreign-path','wrong-media','media-unavailable','post-source-change'])test(`${kind} cannot verify or apply alias; dispatch remains retained`,async()=>{
 const f=await fixture(),options={...f.options},save=options.saveRemote;
 if(kind==='foreign-id')options.saveRemote=async input=>{const r=await save(input);r.remote.imageId='wa-foreign';return r;};
 if(kind==='foreign-path')options.saveRemote=async input=>{const r=await save(input);r.remote.storagePath='generated-images/foreign';return r;};
 if(kind==='wrong-media')options.fetchBytes=async()=>new Uint8Array([1,2,3]).buffer;
 if(kind==='media-unavailable')options.fetchBytes=async()=>{throw new Error('read_failed');};
 if(kind==='post-source-change')options.saveRemote=async input=>{const r=await save(input);f.setCurrent({...f.object,src:f.object.src+'changed'});return r;};
 await assert.rejects(promotion.promoteCanvasLocalSource(options));assert.equal(f.inputs.length,1);assert.equal(JSON.parse([...localStorage.map.values()][0]).stage,'dispatched');assert.equal(f.object.metadata.parameters,undefined);
});
test('same local bytes in another authenticated scope get a distinct UUID; forged durable binding and alias rejected',async()=>{
 const f=await fixture(),first=await promotion.promoteCanvasLocalSource(f.options),other=await promotion.promoteCanvasLocalSource({...f.options,scope:{...f.scope,userId:'bob'}});assert.notEqual(first.binding.requestId,other.binding.requestId);assert.equal(f.inputs.length,2);
 const alias=promotion.applyCanvasSourcePromotionAlias(f.object,first);assert.throws(()=>promotion.canvasSaveObjectsWithPromotedSources([alias],{...f.scope,brandId:'foreign'}),/alias_unverified/);
 const recordKey=[...localStorage.map.keys()].find(k=>k.includes(first.binding.requestId)),stored=JSON.parse(localStorage.getItem(recordKey));stored.binding.rawSha256='f'.repeat(64);localStorage.setItem(recordKey,JSON.stringify(stored));await assert.rejects(promotion.promoteCanvasLocalSource(f.options),/record_identity_mismatch/);assert.equal(f.inputs.length,2);
});
test('concurrent helper calls cannot race a durable dispatch marker into a second POST',async()=>{
 const f=await fixture();let unblock;const gate=new Promise(resolve=>unblock=resolve),save=f.options.saveRemote;let started;const dispatched=new Promise(resolve=>started=resolve);const first=promotion.promoteCanvasLocalSource({...f.options,saveRemote:async input=>{started();await gate;return save(input);}});await dispatched;await assert.rejects(promotion.promoteCanvasLocalSource(f.options),/dispatch_unknown_get_only/);assert.equal(f.inputs.length,0);unblock();await first;assert.equal(f.inputs.length,1);
});
async function pageFunction(name,bindings){const source=await fs.readFile(new URL('../src/pages/CanvasEditorPage.tsx',import.meta.url),'utf8'),ast=ts.createSourceFile('page.tsx',source,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);let found;const walk=n=>{if(ts.isVariableDeclaration(n)&&n.name.getText(ast)===name)found=n.initializer;ts.forEachChild(n,walk);};walk(ast);assert(found,name);const code=ts.transpile('return '+found.getText(ast),{target:ts.ScriptTarget.ES2022});return new Function(...Object.keys(bindings),code)(...Object.values(bindings));}
test('actual page whole-save single flight: overlapping same-render saves neither duplicate POST nor release busy early; alias preserves active draft/history/view/four finals',async()=>{
 const f=await fixture();let release,entered;const gate=new Promise(r=>release=r),began=new Promise(r=>entered=r),proofs=[];const finals=Array.from({length:4},(_,i)=>({id:'final-'+i,type:'image',src:'generated-images/wa-final-'+i,metadata:{feature:'canvas-partial-edit',generation:1,imageId:'wa-final-'+i}}));const state={objects:[f.object,{id:'ordinary',type:'text',text:'concurrent note'},...finals],currentProjectId:'local-doc',currentProjectName:'keep draft',selectedIds:['original'],history:[[f.object]],historyIndex:0,zoom:.81,panX:17,panY:28};const baseline=structuredClone(state),flight={current:false},busy={current:false},events=[],fakeStore={getState:()=>state,setState:patch=>Object.assign(state,patch)};
 const client={origin:f.scope.origin,captureArtifactPersistenceContext:async({assertContext})=>({assertCurrent:async()=>assertContext()}),readWorkspaceArtifact:f.options.readRemote,saveWorkspaceArtifact:f.options.saveRemote};
 const assertContext=Object.assign(()=>{}, {readMismatchFlags:()=>({})});
 const bindings={canvasSaveFlightRef:flight,sourcePromotionBusyRef:busy,currentBrand:{id:'brand'},user:{id:'alice'},activeCanvasSaveRef:{current:null},canvasPersistenceStatus:'unsaved',setCanvasPersistenceStatus:s=>events.push(s),toast:{error:()=>{}},useCanvasStore:fakeStore,remoteDocumentIdRef:{current:null},projectId:'local-doc',CANVAS_DOCUMENT_ID_PATTERN:/^remote-/,remoteRevisionRef:{current:null},clearCanvasSaveDiagnosticReceipt:()=>{},recordCanvasSaveDiagnosticReceipt:()=>{},buildCanvasSaveDiagnosticReceipt:()=>{},setCanvasSaveDiagnosticVersion:()=>{},CANVAS_SAVE_DIAGNOSTIC_LOG_PREFIX:'fixture',captureCanvasImageEditContext:()=>assertContext,currentProjectName:state.currentProjectName,currentProjectId:state.currentProjectId,objects:state.objects,zoom:state.zoom,panX:state.panX,panY:state.panY,canvasSourceProjectIdsRef:{current:[]},buildCanvasDocumentSnapshot:v=>v,cloudflareDataPlane:client,canvasGeneratingRef:{current:false},canvasImageTaskCountRef:{current:0},isMountedRef:{current:true},isLocalCanvasAssetReference:v=>typeof v==='string'&&v.startsWith('local-canvas-asset://'),resolveGeneratedImageUrl:f.options.signedRead,promoteCanvasLocalSource:async options=>{entered();await gate;const p=await promotion.promoteCanvasLocalSource({...options,getBlob:f.options.getBlob,readDimensions:f.options.readDimensions,blobDataUrl:f.options.blobDataUrl,fetchBytes:f.options.fetchBytes});proofs.push(p);return p;},applyCanvasSourcePromotionAlias:promotion.applyCanvasSourcePromotionAlias,currentCanvasSaveContent:()=>({title:state.currentProjectName,snapshot:{objects:promotion.canvasSaveObjectsWithPromotedSources(state.objects,f.scope)}}),validateCanvasDocumentSnapshot:()=>{throw new Error('doc_fixture_failure_after_verified_promotion');},canvasDocumentValidationMessage:()=>''};
 const save=await pageFunction('handleSave',bindings),first=save();await began;assert.equal(flight.current,true);assert.equal(busy.current,true);await save();assert.equal(flight.current,true);assert.equal(busy.current,true);assert.equal(f.inputs.length,0);release();await first;assert.equal(flight.current,false);assert.equal(busy.current,false);assert.equal(f.inputs.length,1);assert.equal(proofs.length,1);assert.equal(events.at(-1),'failed');for(const key of ['selectedIds','history','historyIndex','zoom','panX','panY','currentProjectId'])assert.deepEqual(state[key],baseline[key]);assert.deepEqual(state.objects.slice(1),baseline.objects.slice(1));assert.equal(state.objects[0].src,baseline.objects[0].src);assert.deepEqual(state.objects[0].metadata.sourceRevision,baseline.objects[0].metadata.sourceRevision);await save();assert.equal(f.inputs.length,1);assert.equal(proofs.length,2);
});

test('real IndexedDB getter uses captured actual local reference; verified alias passes unchanged production document validator',async()=>{
 const f=await fixture(),assets=await vite.ssrLoadModule('/src/lib/canvasLocalAssets.ts'),documents=await vite.ssrLoadModule('/src/lib/canvasDocumentPersistence.ts'),{createPendingIndexedDbHarness}=await import('./verify-cloudflare-image-pending-store.test.mjs'),prior=Object.getOwnPropertyDescriptor(globalThis,'indexedDB'),db=createPendingIndexedDbHarness();Object.defineProperty(globalThis,'indexedDB',{value:db,writable:true,configurable:true});
 try{await assets.putLocalCanvasAsset(f.key,f.blob);const options={...f.options};delete options.getBlob;const proof=await promotion.promoteCanvasLocalSource(options);assert(db.log.some(e=>e.database==='heavy-chain-canvas-assets'&&e.operation==='get'&&e.key===f.key));assert(!db.log.some(e=>e.operation==='get'&&e.key===f.object.metadata.sourceRevision.revision));const objects=promotion.canvasSaveObjectsWithPromotedSources([promotion.applyCanvasSourcePromotionAlias(f.object,proof)],f.scope),snapshot=documents.buildCanvasDocumentSnapshot({projectId:'doc',name:'Native source',objects,view:{zoom:.7,panX:3,panY:4}});assert.equal(snapshot.objects[0].src,proof.remote.storagePath);assert.equal(snapshot.objects[0].id,f.object.id);assert.deepEqual(snapshot.objects[0].metadata.sourceIdentity,f.object.metadata.sourceIdentity);assert.deepEqual(snapshot.objects[0].metadata.sourceRevision,f.object.metadata.sourceRevision);documents.validateCanvasDocumentSnapshot(snapshot);}finally{if(prior)Object.defineProperty(globalThis,'indexedDB',prior);else delete globalThis.indexedDB;}
});
test('failed durable dispatch-marker write prevents POST; first GET auth/conflict/mismatch cannot become absence',async()=>{
 const f=await fixture();const set=localStorage.setItem;localStorage.setItem=()=>{throw new Error('quota_exceeded');};await assert.rejects(promotion.promoteCanvasLocalSource(f.options),/quota_exceeded/);assert.equal(f.inputs.length,0);localStorage.setItem=set;
 for(const message of ['cloudflare_api_409_workspace_artifact_idempotency_conflict','cloudflare_api_401_unauthorized','workspace_content_identity_mismatch','workspace_save_pending'])await assert.rejects(promotion.promoteCanvasLocalSource({...f.options,readRemote:async()=>{throw new Error(message);}}),new RegExp(message));assert.equal(f.inputs.length,0);
});


async function independentContext(name,sharedStorage,service){
 const src=await fs.readFile(new URL('../src/lib/canvasSourcePromotion.ts',import.meta.url),'utf8');
 // Separate VM globals/module state model independent tabs sharing the browser
 // storage and origin-wide Web Locks service. The actual helper source runs in each.
 const code=ts.transpile(src.replace(/^import .*;$/gm,''),{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}).replace(/export /g,'')+'\n globalThis.actualPromote=promoteCanvasLocalSource;';
 const trace=[];const storage={getItem:key=>{trace.push(['read',key]);return sharedStorage.getItem(key);},setItem:(key,value)=>{trace.push(['retain',key]);sharedStorage.setItem(key,value);},removeItem:()=>assert.fail('dispatch record may never be cleared')};
 const realm=vm.createContext({localStorage:storage,navigator:{locks:service.context(name)},sha256Hex:metadata.sha256Hex,isLocalCanvasAssetReference:v=>typeof v==='string'&&v.startsWith('local-canvas-asset://'),getLocalCanvasAsset:()=>assert.fail('fixture provides actual retained Blob boundary'),Blob,TextEncoder,Uint8Array,atob,structuredClone,Error,URL,console});new vm.Script(code,{filename:'actual-canvasSourcePromotion-'+name+'.js'}).runInContext(realm);return{promote:realm.actualPromote,trace,realm};
}
test('simultaneous independent tab globals: shared atomic ownership produces exactly one POST and same UUID/canonical bytes',async()=>{
 const f=await fixture(),shared=localStorage,service=browserLockService(),one=await independentContext('tab-A',shared,service),two=await independentContext('tab-B',shared,service);assert.notEqual(one.realm,two.realm);let entered=0,release;const both=new Promise(r=>release=r),read=f.options.readRemote;
 const readRemote=async id=>{if(++entered<=2){if(entered===2)release();await both;throw new Error('cloudflare_api_404_workspace_artifact_not_found');}return read(id);};
 const results=await Promise.all([one.promote({...f.options,readRemote}),two.promote({...f.options,readRemote})]);assert.equal(f.inputs.length,1);assert.equal(results[0].binding.requestId,results[1].binding.requestId);assert.equal(results[0].remote.imageId,results[1].remote.imageId);assert.deepEqual(Buffer.from(f.inputs[0].imageUrl.split(',')[1],'base64'),f.bytes);assert.equal(service.events.filter(e=>e[0]==='acquire').length,2);assert(service.events.some(e=>e[0]==='acquire'&&e[1]==='tab-A'));assert(service.events.some(e=>e[0]==='acquire'&&e[1]==='tab-B'));assert.equal(JSON.parse([...shared.map.values()][0]).stage,'verified');
});
test('independent tab unknown dispatch plus fresh reload are GET-only, durable marker never expires or clears',async()=>{
 const f=await fixture(),shared=localStorage,service=browserLockService(),one=await independentContext('tab-A',shared,service),two=await independentContext('tab-B',shared,service);let entered=0,release;const both=new Promise(r=>release=r),read=f.options.readRemote;
 const readRemote=async id=>{if(++entered<=2){if(entered===2)release();await both;throw new Error('cloudflare_api_404_workspace_artifact_not_found');}return read(id);};f.setFailure(true);
 const outcomes=await Promise.allSettled([one.promote({...f.options,readRemote}),two.promote({...f.options,readRemote})]);assert(outcomes.every(v=>v.status==='rejected'));assert(outcomes.some(v=>v.reason.message==='upload_response_unknown'));assert(outcomes.some(v=>/dispatch_unknown_get_only/.test(v.reason.message)));assert.equal(f.inputs.length,1);const retained=[...shared.map.values()][0],marker=JSON.parse(retained);assert.equal(marker.stage,'dispatched');
 const reload=await independentContext('reloaded-tab',shared,service);f.setFailure(false);await assert.rejects(reload.promote(f.options),/dispatch_unknown_get_only/);assert.equal(f.inputs.length,1);assert.equal([...shared.map.values()][0],retained);assert.equal(service.events.filter(e=>e[0]==='acquire'&&e[1]==='reloaded-tab').length,0);
 const input=f.inputs[0],id='wa-'+input.requestId;f.remotes.set(input.requestId,{success:true,remote:{jobId:id,imageId:id,storagePath:'generated-images/'+id}});f.raw.set('generated-images/'+id,f.bytes);const completed=await reload.promote(f.options);assert.equal(completed.stage,'verified');assert.equal(completed.binding.requestId,marker.binding.requestId);assert.equal(f.inputs.length,1);
});
for(const kind of ['missing-lock-manager','request-failure','null-lock','wrong-lock-identity'])test(kind+' fails closed with no marker or POST',async()=>{
 const f=await fixture();const locks=kind==='missing-lock-manager'?undefined:{request:async(name,_options,callback)=>{if(kind==='request-failure')throw new Error('lock_service_failed');return callback(kind==='null-lock'?null:{name:name+'foreign',mode:'exclusive'});}};Object.defineProperty(globalThis,'navigator',{value:{locks},configurable:true});await assert.rejects(promotion.promoteCanvasLocalSource(f.options));assert.equal(f.inputs.length,0);assert.equal(localStorage.map.size,0);
});
for(const value of [undefined,null,false])test('falsy remote receipt '+String(value)+' never proves404 absence or dispatch eligibility',async()=>{const f=await fixture();await assert.rejects(promotion.promoteCanvasLocalSource({...f.options,readRemote:async()=>value}),/remote_receipt_invalid/);assert.equal(f.inputs.length,0);assert.equal(localStorage.map.size,0);});
