import assert from 'node:assert/strict';
import test, { after } from 'node:test';
import React, { act } from 'react';
import Reconciler from 'react-reconciler';
import * as existingHostConfig from 'react-konva/lib/ReactKonvaHostConfig.js';
import { ConcurrentRoot } from 'react-reconciler/constants.js';
import { createServer } from 'vite';

// Existing UI suites launch Chromium. This accepted package forbids browser
// operations/installations, so use the already installed React renderer stack
// with a local host adapter. React hooks, commits, callbacks and refs are real;
// host keyboard bubbling/focus is the isolated boundary, not native-browser proof.
type Host = { type: string; props: Record<string, any>; children: Host[]; parent: Host | null; text?: string; focus(): void };
let activeElement: Host | null = null;
let focusCalls = 0;
const link = (parent: Host, child: Host, before?: Host) => {
  if (child.parent) child.parent.children.splice(child.parent.children.indexOf(child), 1);
  child.parent = parent;
  const at = before ? parent.children.indexOf(before) : -1;
  if (at < 0) parent.children.push(child); else parent.children.splice(at, 0, child);
};
const remove = (parent: Host, child: Host) => { parent.children.splice(parent.children.indexOf(child), 1); child.parent = null; };
const host = (type: string, props: Record<string, any> = {}): Host => ({ type, props, children: [], parent: null, focus() { activeElement = this; focusCalls++; } });
const renderer = Reconciler({
  ...existingHostConfig,
  createInstance: (type: string, props: Record<string, any>) => host(type, props),
  createTextInstance: (text: string) => ({ ...host('#text'), text }),
  appendInitialChild: link, appendChild: link, appendChildToContainer: link,
  insertBefore: link, insertInContainerBefore: link, removeChild: remove, removeChildFromContainer: remove,
  commitUpdate: (instance: Host, _type: string, _oldProps: unknown, newProps: Record<string, any>) => { instance.props = newProps; },
  commitTextUpdate: (instance: Host, _old: string, text: string) => { instance.text = text; },
  getPublicInstance: (instance: Host) => instance,
  prepareForCommit: () => null, resetAfterCommit() {}, finalizeInitialChildren: () => false,
  clearContainer: (container: Host) => { container.children.length = 0; }, resetTextContent: (instance: Host) => { instance.children.length = 0; },
  hideInstance() {}, hideTextInstance() {}, unhideInstance() {}, unhideTextInstance() {},
});
const originalAct = (globalThis as any).IS_REACT_ACT_ENVIRONMENT;
(globalThis as any).IS_REACT_ACT_ENVIRONMENT = true;

import { MemoryRouter } from 'react-router-dom';
const priorFetch=globalThis.fetch,priorStorage=(globalThis as any).sessionStorage,priorImage=(globalThis as any).Image;
const session=new Map<string,string>();(globalThis as any).sessionStorage={getItem:(key:string)=>session.get(key)??null,setItem:(key:string,value:string)=>session.set(key,value),removeItem:(key:string)=>session.delete(key)};
(globalThis as any).Image=class{naturalWidth=120;naturalHeight=160;onload:any;onerror:any;set src(value:string){if(value)queueMicrotask(()=>{if((globalThis as any).__modelSettings?.imageLoadError)this.onerror?.();else this.onload?.();});}};
globalThis.fetch=async()=>{throw new Error('model_settings_network_forbidden');};
const mocks:Record<string,string>={
 '../stores/authStore':`export const useAuthStore=Object.assign(()=>globalThis.__modelSettings.auth,{getState:()=>globalThis.__modelSettings.auth});`,
 '../lib/localWorkspaceArtifacts':`export const listWorkspaceArtifacts=(brand,owner)=>globalThis.__modelSettings.artifacts.filter(a=>a.brandId===brand&&a.scopeId===owner);export const saveWorkspaceArtifactPersisted=()=>{throw new Error('candidate_write_not_requested');};`,
 '../lib/storage':`export const withSignedImageUrls=async rows=>{const f=globalThis.__modelSettings;f.signCalls.push(structuredClone(rows));if(f.holdSigning)await new Promise(resolve=>{f.releaseSigning=resolve;});return rows.map(r=>({...r,image_url:f.signFailure?null:'https://fixture.invalid/'+r.storage_path}));};`,
 '../lib/canvasLocalAssets':`export{buildLocalCanvasAssetReference,isLocalCanvasAssetReference}from'/src/lib/canvasLocalAssets.ts';export const putLocalCanvasAsset=async(key,blob)=>{const f=globalThis.__modelSettings;if(f.assetPersistFailure)throw new Error('local_asset_write_failed');f.localWrites.push({key,bytes:await blob.text(),type:blob.type});};export const resolveLocalCanvasAsset=async ref=>{const f=globalThis.__modelSettings;f.sourceReads.push(ref);return f.missingSources.includes(ref)?null:{source:'blob:retained-'+ref,release(){}};};`,
 '../lib/workspaceArtifactImageReadback':`export const readWorkspaceArtifactImage=()=>{throw new Error('library_handoff_followon_not_requested');};`,
 '../lib/providerResultPersistence':`export const persistProviderResultArtifact=async input=>{const f=globalThis.__modelSettings;f.persists.push(structuredClone(input));const imageId=input.metadata.imageId;const artifact={...input,id:imageId,imageUrl:'',createdAt:'2026-10-06T00:00:00Z',metadata:{...input.metadata,providerResultArtifact:true,storagePath:input.storagePath}};f.artifacts.push(artifact);return{artifact,remote:{jobId:input.sourceJobId,imageId,storagePath:input.storagePath}};};`,
};
const cloudflare=`export const cloudflareDataPlane={invokeProviderAction:async(action,body,options)=>{const f=globalThis.__modelSettings;await options.assertContext();const pending=JSON.parse([...globalThis.sessionStorageKeys()].map(k=>sessionStorage.getItem(k)).find(Boolean)||'null');f.calls.push({action,body:structuredClone(body),requestId:options.idempotencyKey,pending});if(f.hold)await new Promise(resolve=>{f.release=resolve;});await options.assertContext();const pairs=(body.bodyTypes||['regular']).flatMap(bodyType=>(body.ageGroups||['20s']).map(ageGroup=>({bodyType,ageGroup})));const jobId='ai-'+options.idempotencyKey;const matrix=pairs.map((pair,candidateIndex)=>{const imageId=crypto.randomUUID();return{...pair,candidateIndex,imageId,storagePath:'generated-images/'+imageId,imageUrl:'https://fixture.invalid/'+imageId,persistenceStatus:'completed',provider:'workers_ai',jobId};});return{success:true,requestId:options.idempotencyKey,state:'completed',jobId,provider:'workers_ai',persistenceStatus:'completed',matrix,requestedCandidateCount:matrix.length,persistedCandidateCount:matrix.length,clientRecoveryKey:'fixture'};},captureArtifactPersistenceContext:async()=>({}),acknowledgeImageAction:async r=>{globalThis.__modelSettings.acks.push(r.requestId);},listGeneratedImages:async()=>[],readImageAIRequest:async()=>{const f=globalThis.__modelSettings;f.reads++;if(!f.readReceipt)throw new Error('no_unknown_replay');return f.readReceipt;}};`;
(globalThis as any).sessionStorageKeys=()=>[...session.keys()];
const vite=await createServer({configFile:false,envFile:false,appType:'custom',logLevel:'silent',server:{middlewareMode:true,hmr:false,watch:null},optimizeDeps:{noDiscovery:true,include:[]},plugins:[{name:'model-settings-service-boundaries',enforce:'pre',resolveId(source,importer){if((importer?.endsWith('/useCanonicalImageWorkspace.ts')||importer?.endsWith('/imageApi.ts'))&&source.endsWith('/cloudflareApi'))return '\0model-settings:cloudflare';if(importer?.endsWith('/useCanonicalImageWorkspace.ts')&&mocks[source])return '\0model-settings:'+source;},load(id){if(id==='\0model-settings:cloudflare')return cloudflare;if(id.startsWith('\0model-settings:'))return mocks[id.slice('\0model-settings:'.length)];}}]});
const{useCanonicalImageWorkspace}=await vite.ssrLoadModule('/src/hooks/useCanonicalImageWorkspace.ts');
const{MODEL_TOOL_FEATURES,defaultModelToolSettings,readModelToolSettings,readLegacyModelDescriptionSettings,readLegacyModelToolSettings,chooseModelCustomBody,modelToolSettingsPrompt,MODEL_TOOL_FIELDS}=await vite.ssrLoadModule('/src/lib/modelToolSettings.ts');
after(async()=>{globalThis.fetch=priorFetch;(globalThis as any).sessionStorage=priorStorage;(globalThis as any).Image=priorImage;(globalThis as any).IS_REACT_ACT_ENVIRONMENT=originalAct;delete(globalThis as any).__modelSettings;delete(globalThis as any).sessionStorageKeys;await vite.close();});
const auth=(owner='owner',brand='brand')=>({user:{id:owner},currentBrand:{id:brand},brandState:{status:'success_nonempty',userId:owner,requestGeneration:1,confirmedBrandIds:[brand],error:null}});
async function mount(feature:string,options:{artifact?:any;job?:string;hold?:boolean;pending?:any;missingSources?:string[];authState?:any;libraryArtifactId?:string}={}){
 session.clear();if(options.pending)session.set('heavy:canonical-image-workspace:v1:owner:brand:'+feature+':'+(options.job||'fresh'),JSON.stringify(options.pending));const f={auth:options.authState??auth(),artifacts:options.artifact?[options.artifact]:[],calls:[] as any[],persists:[] as any[],acks:[] as string[],current:null as any,hold:options.hold,release:null as any,readReceipt:null as any,reads:0,sourceReads:[] as string[],missingSources:options.missingSources??[],signCalls:[] as any[],signFailure:false,holdSigning:false,releaseSigning:null as any,imageLoadError:false,assetPersistFailure:false,localWrites:[] as any[]};(globalThis as any).__modelSettings=f;
 const container=host('root');const root=renderer.createContainer(container,ConcurrentRoot,null,false,null,'',(e:Error)=>{throw e;},(e:Error)=>{throw e;},(e:Error)=>{throw e;},null);
 const initial=MODEL_TOOL_FEATURES.includes(feature)?defaultModelToolSettings(feature):{bodyTypes:['slim','regular'],ageGroups:['20s'],gender:'女性'};
 function Hook(){f.current=useCanonicalImageWorkspace(feature,{requiredSources:1,title:feature,initialInputState:initial});return React.createElement('span');}
 const query=new URLSearchParams();if(options.job)query.set('resumeJob',options.job);if(options.libraryArtifactId)query.set('libraryArtifactId',options.libraryArtifactId);
 const render=async()=>{await act(async()=>{renderer.updateContainer(React.createElement(MemoryRouter,{initialEntries:['/model/'+feature+(query.size?'?'+query.toString():'')]},React.createElement(Hook)),root,null,null);});};
 const settle=async()=>{for(let i=0;i<3;i++)await act(async()=>{await new Promise(r=>setTimeout(r,0));});};await render();await settle();
 const call=async(fn:()=>any)=>{await act(async()=>{await fn();});await settle();};
 const sources=async()=>{await call(()=>f.current.upload('primary',new File(['<svg/>'],'primary.svg',{type:'image/svg+xml'})));await call(()=>f.current.upload('secondary',new File(['<svg/>'],'secondary.svg',{type:'image/svg+xml'})));};
 return{f,call,settle,sources,render,close:async()=>{await act(async()=>{renderer.updateContainer(null,root,null,null);});}};
}
for(const feature of MODEL_TOOL_FEATURES)test(`${feature}: actual hook+generateModelMatrix adapter snapshot/prompt/persistence/hydrate/reuse keep exact settings and identity`,async()=>{
 const t=await mount(feature);let artifact:any,settings:any,job:string;try{
 assert.deepEqual(t.f.current.inputState,defaultModelToolSettings(feature));await t.sources();settings={...defaultModelToolSettings(feature),aspectRatio:'9:16',resolution:'4K'};for(const field of MODEL_TOOL_FIELDS[feature]||[])settings[field.key]=field.options.at(-1);if(feature==='model-change')settings.keepApparelSize=true;
 await t.call(()=>t.f.current.setInputState(settings));await t.call(()=>t.f.current.generate({brief:'observed input request'}));assert.equal(t.f.calls.length,1);const call=t.f.calls[0];assert.equal(call.action,'model-matrix');assert.equal(call.body.featureType,'lightchain-'+feature);assert.equal(call.body.lightchainCompat.lightchainFeatureId,feature);assert.equal(call.body.brandId,'brand');assert.deepEqual(call.pending.inputState,settings);assert.equal(call.pending.requestId,call.requestId);assert(call.body.productDescription.includes(modelToolSettingsPrompt(feature,settings)));assert.equal(call.body.imageUrl.startsWith('blob:'),true);assert.equal(call.body.modelReferenceFileName,'secondary.svg');assert.equal(call.body.materialReferences[0].key,'primary');assert.equal(call.body.materialReferences[1].key,'secondary');assert.equal(call.body.maskWidth,undefined);assert.equal(call.body.maskHeight,undefined);
 assert.deepEqual(t.f.persists[0].metadata.inputState,settings);assert.equal(t.f.persists[0].metadata.toolId,feature);assert.equal(t.f.current.status,'saved');artifact=structuredClone(t.f.artifacts[0]);job=artifact.sourceJobId;assert.equal(t.f.current.result.jobId,job);assert.equal(t.f.current.result.imageId,artifact.metadata.imageId);assert.equal(t.f.current.result.storagePath,artifact.metadata.storagePath);assert.equal(t.f.acks.length,1);assert.equal(session.size,0);
 }finally{await t.close();}
 const u=await mount(feature,{artifact,job});try{assert.equal(u.f.current.status,'saved');assert.deepEqual(u.f.current.inputState,settings);assert.equal(u.f.current.result.jobId,job);assert.equal(u.f.current.result.imageId,artifact.metadata.imageId);assert.equal(u.f.current.result.storagePath,artifact.metadata.storagePath);await u.call(()=>u.f.current.generate({brief:'deliberate reuse'}));assert.equal(u.f.calls.length,1);assert.deepEqual(u.f.persists[0].metadata.inputState,settings);}finally{await u.close();}
});
const unconfirmedAuth=()=>({...auth(),brandState:{...auth().brandState,status:'loading',confirmedBrandIds:[]}});
const observedFreshSettings:Record<string,Record<string,string|boolean>>={
 'model-face':{},'model-change':{keepApparelSize:false},'body-shape':{gender:'男性',bodyShape:'正常',customBody:false},
 'clothing-size':{clothingType:'トップス',originalSize:'L',targetSize:'XXL'},'pose-change':{inputMode:'reference',customDescription:''},'background-change':{inputMode:'reference',customDescription:''},
 'angle-change':{backView:false,horizontalAngle:'変更なし',verticalAngle:'変更なし',zoom:'変更なし'},
};
for(const feature of MODEL_TOOL_FEATURES)test(`${feature}: unfenced fresh route has editable observed defaults; source/provider authority remains unconfirmed`,async()=>{
 const t=await mount(feature,{authState:unconfirmedAuth()});try{const expected={aspectRatio:'スマート',resolution:'1K',...observedFreshSettings[feature]};assert.deepEqual(t.f.current.inputState,expected);assert.equal(t.f.current.status,'empty');assert.equal(t.f.current.pendingId,null);assert.equal(t.f.current.inputsAvailable,false);assert.equal(t.f.current.originalInputsAvailable,false);await t.call(()=>t.f.current.setInputState({...expected,aspectRatio:'4:5'}));assert.equal(t.f.current.inputState.aspectRatio,'4:5');await t.call(()=>t.f.current.upload('primary',new File(['<svg/>'],'unconfirmed.svg',{type:'image/svg+xml'})));await t.call(()=>t.f.current.selectModelReference({imageUrl:'https://fixture.invalid/preview',imageId:'unconfirmed-reference',storagePath:'generated-images/unconfirmed-reference'}));await t.call(()=>t.f.current.generate({brief:'Unconfirmed authority'}));assert.equal(t.f.current.slots.primary,null);assert.equal(t.f.current.slots.secondary,null);assert.equal(t.f.calls.length,0);assert.equal(t.f.persists.length,0);assert.equal(t.f.acks.length,0);assert.equal(t.f.signCalls.length,0);assert.equal(t.f.localWrites.length,0);assert.equal(session.size,0);assert.equal(t.f.current.originalInputsAvailable,false);}finally{await t.close();}
});
test('fresh defaults do not require user/brand presence and do not change generic unfenced workspaces',async()=>{
 for(const state of [{...unconfirmedAuth(),user:null},{...unconfirmedAuth(),currentBrand:null}]){const t=await mount('body-shape',{authState:state});try{assert.deepEqual(t.f.current.inputState,{aspectRatio:'スマート',resolution:'1K',gender:'男性',bodyShape:'正常',customBody:false});assert.equal(t.f.current.slots.primary,null);assert.equal(t.f.calls.length,0);}finally{await t.close();}}
 const u=await mount('lab',{authState:unconfirmedAuth()});try{assert.deepEqual(u.f.current.inputState,{});assert.equal(u.f.calls.length,0);}finally{await u.close();}
});
test('unfenced saved-job and Library routes never fill missing original settings or resolve sources',async()=>{
 for(const options of [{job:'saved-unconfirmed'},{libraryArtifactId:'library-unconfirmed'}]){const t=await mount('body-shape',{...options,authState:unconfirmedAuth()});try{assert.deepEqual(t.f.current.inputState,{});assert.equal(t.f.current.status,'unavailable');assert.equal(t.f.current.originalInputsAvailable,false);assert.equal(t.f.current.result,null);assert.equal(t.f.sourceReads.length,0);assert.equal(t.f.signCalls.length,0);assert.equal(t.f.calls.length,0);assert.equal(t.f.persists.length,0);}finally{await t.close();}}
});
test('unfenced existing pending settings keep exact known values and request; no default fill, edit, reconcile read or dispatch',async()=>{
 for(const feature of ['body-shape','pose-change']){const legacy=feature==='body-shape'?{aspectRatio:'4:5',resolution:'2K',gender:'女性',bodyShape:'筋肉質'}:{aspectRatio:'4:5',resolution:'2K'},pending={requestId:crypto.randomUUID(),originJob:null,brief:'Original pending',referenceNote:'',inputState:legacy,materialSlots:[]},t=await mount(feature,{pending,authState:unconfirmedAuth()});try{const raw=[...session.entries()];assert.equal(t.f.current.status,'unknown');assert.equal(t.f.current.pendingId,pending.requestId);assert.deepEqual(t.f.current.inputState,legacy);await t.call(()=>t.f.current.setInputState(defaultModelToolSettings(feature)));assert.deepEqual(t.f.current.inputState,legacy);await t.call(()=>t.f.current.generate({brief:'Blocked edit'}));await t.call(()=>t.f.current.reconcile());assert.deepEqual([...session.entries()],raw);assert.equal(t.f.reads,0);assert.equal(t.f.calls.length,0);assert.equal(t.f.persists.length,0);assert.equal(t.f.acks.length,0);}finally{await t.close();}}
});

test('codec rejects missing/enumeration/foreign/internal fields without default filling',()=>{for(const feature of MODEL_TOOL_FEATURES){const initial=defaultModelToolSettings(feature);assert.equal(readModelToolSettings(feature,{}),null);assert.equal(readModelToolSettings(feature,{...initial,aspectRatio:'unobserved'}),null);assert.equal(readModelToolSettings(feature,{...initial,customBody:{height:170}}),null);assert.equal(readModelToolSettings(feature,{...initial,resolution:4096}),null);assert.deepEqual(readModelToolSettings(feature,initial),initial);}});
for(const reason of ['missing','wrongfeature','owner','brand'])test(`hydrate ${reason} settings: no inferred replacement/generation; matching result identity retained only when scoped`,async()=>{
 const feature='body-shape',job='saved-job',imageId='saved-image';const a={id:imageId,brandId:reason==='brand'?'other':'brand',scopeId:reason==='owner'?'other':'owner',featureType:'lightchain-'+(reason==='wrongfeature'?'clothing-size':feature)+'-provider-result',sourceJobId:job,createdAt:'2026-10-06',title:'Saved',imageUrl:'',metadata:{toolId:reason==='wrongfeature'?'clothing-size':feature,providerResultArtifact:true,imageId,storagePath:'generated-images/'+imageId,brief:'saved',materialSlots:[{key:'primary',fileName:'source',materialKind:'primary',imageUrl:'local-canvas-asset://original'}],...(reason==='missing'?{}:{inputState:defaultModelToolSettings(feature)})}};
 const t=await mount(feature,{artifact:a,job});try{assert.equal(t.f.current.status,'unavailable');assert.deepEqual(t.f.current.inputState,{});assert.equal(t.f.calls.length,0);assert.equal(t.f.persists.length,0);assert.equal(t.f.acks.length,0);if(reason==='missing'){assert.equal(t.f.current.result.jobId,job);assert.equal(t.f.current.result.imageId,imageId);}else assert.equal(t.f.current.result,null);}finally{await t.close();}
});
test('held provider freezes request settings; auth fence change prevents persistence/ACK and no replay',async()=>{const t=await mount('model-change',{hold:true});try{await t.sources();const settings={...defaultModelToolSettings('model-change'),keepApparelSize:true};await t.call(()=>t.f.current.setInputState(settings));let operation:Promise<any>;await act(async()=>{operation=t.f.current.generate({brief:'held'});await Promise.resolve();});await t.settle();assert.equal(t.f.calls.length,1);await t.call(()=>t.f.current.setInputState({...settings,keepApparelSize:false}));assert.deepEqual(t.f.current.inputState,settings);t.f.auth=auth('other-owner');await t.render();t.f.release();await t.call(()=>operation!);assert.equal(t.f.persists.length,0);assert.equal(t.f.acks.length,0);assert.equal(t.f.calls.length,1);}finally{await t.close();}});
test('unrelated model-library matrix codec/body-age pairs remain unchanged',async()=>{const t=await mount('model-library');try{await t.sources();const values={bodyTypes:['slim','regular'],ageGroups:['20s'],gender:'女性'};await t.call(()=>t.f.current.setInputState(values));await t.call(()=>t.f.current.generate({brief:'existing matrix'}));assert.equal(t.f.calls[0].action,'model-matrix');assert.deepEqual(t.f.calls[0].body.bodyTypes,values.bodyTypes);assert.deepEqual(t.f.calls[0].body.ageGroups,values.ageGroups);assert.equal(t.f.calls[0].body.gender,'female');assert.deepEqual(t.f.persists[0].metadata.inputState,values);assert.equal(t.f.current.candidates.length,2);}finally{await t.close();}});

test('unrelated lab retains existing safe generic inputs without model enum/default injection',async()=>{const t=await mount('lab');try{await t.call(()=>t.f.current.setInputState({coverage:'full',layerModes:['split'],gender:'女性',aspectRatio:'16:9',customBody:{height:170}}));assert.deepEqual(t.f.current.inputState,{coverage:'full',layerModes:['split'],gender:'女性'});assert.equal(t.f.calls.length,0);assert.equal(t.f.current.inputsAvailable,true);}finally{await t.close();}});

test('legacy pending settings reconcile existing completed row only; no inferred originals or new dispatch',async()=>{
 const feature='model-face',requestId=crypto.randomUUID(),job='ai-existing',imageId=crypto.randomUUID();
 const pending={requestId,originJob:job,brief:'legacy',referenceNote:'',inputState:{bodyTypes:['regular'],ageGroups:['20s']},materialSlots:[]};
 const t=await mount(feature,{job,pending});try{assert.equal(t.f.current.status,'unknown');t.f.readReceipt={success:true,requestId,state:'completed',jobId:job,provider:'workers_ai',persistenceStatus:'completed',requestedCandidateCount:1,persistedCandidateCount:1,matrix:[{bodyType:'regular',ageGroup:'20s',imageId,storagePath:'generated-images/'+imageId,imageUrl:'https://fixture.invalid/'+imageId,jobId:job,persistenceStatus:'completed',provider:'workers_ai'}]};
 await t.call(()=>t.f.current.reconcile());assert.equal(t.f.reads,1);assert.equal(t.f.calls.length,0);assert.equal(t.f.current.result.jobId,job);assert.equal(t.f.current.result.imageId,imageId);assert.equal(t.f.current.status,'unavailable');assert.deepEqual(t.f.current.inputState,{});assert.deepEqual(t.f.persists[0].metadata.inputState,{});assert.equal(t.f.persists[0].metadata.originalInputsAvailable,undefined);assert.equal(session.size,0);
 }finally{await t.close();}
});

for(const missing of ['primary','secondary',null] as const)test(`settings-only update preserves ${missing??'available'} original-source truth and canonical result identity`,async()=>{
 const feature='body-shape',job='saved-source-job',imageId=crypto.randomUUID(),primary='local-canvas-asset://source-primary',secondary='local-canvas-asset://source-secondary';
 const artifact={id:imageId,brandId:'brand',scopeId:'owner',featureType:'lightchain-'+feature+'-provider-result',sourceJobId:job,createdAt:'2026-10-06',title:'Saved model',imageUrl:'',metadata:{toolId:feature,providerResultArtifact:true,imageId,storagePath:'generated-images/'+imageId,brief:'stored request',inputState:defaultModelToolSettings(feature),materialSlots:[{key:'primary',fileName:'primary',materialKind:'primary',imageUrl:primary},{key:'secondary',fileName:'reference',materialKind:'secondary',imageUrl:secondary}]}};
 const t=await mount(feature,{artifact,job,missingSources:missing?[missing==='primary'?primary:secondary]:[]});try{
 assert.equal(t.f.current.status,missing?'unavailable':'saved');assert.equal(t.f.current.inputsAvailable,!missing);assert.equal(t.f.current.originalInputsAvailable,!missing);assert.deepEqual(t.f.current.inputState,defaultModelToolSettings(feature));
 const result=structuredClone(t.f.current.result),slots=structuredClone(t.f.current.slots),sourceReads=t.f.sourceReads.length;
 const changed={...t.f.current.inputState,aspectRatio:'4:5',bodyShape:'筋肉質'};await t.call(()=>t.f.current.setInputState(changed));
 assert.deepEqual(t.f.current.inputState,changed);assert.equal(t.f.current.inputsAvailable,!missing);assert.equal(t.f.current.originalInputsAvailable,!missing);assert.equal(t.f.current.status,missing?'unavailable':'saved');assert.deepEqual(t.f.current.result,result);assert.equal(t.f.current.result.jobId,job);assert.equal(t.f.current.result.imageId,imageId);assert.equal(t.f.current.result.storagePath,'generated-images/'+imageId);assert.deepEqual(t.f.current.slots,slots);assert.equal(t.f.sourceReads.length,sourceReads);assert.equal(t.f.calls.length,0);assert.equal(t.f.persists.length,0);assert.equal(t.f.acks.length,0);
 }finally{await t.close();}
});

test('body codec distinguishes legacy4, current OFF5, initialized9; invalid/custom-required values never default-fill',()=>{
 const legacy={aspectRatio:'4:5',resolution:'2K',gender:'女性',bodyShape:'筋肉質'};assert.equal(readModelToolSettings('body-shape',legacy),null);assert.deepEqual(readLegacyModelToolSettings('body-shape',legacy),legacy);assert.equal(readLegacyModelToolSettings('body-shape',{...legacy,chest:'79'}),null);
 const current={...legacy,customBody:false};assert.deepEqual(readModelToolSettings('body-shape',current),current);const custom={...current,customBody:true,height:'165cm',chest:'79',waist:'26',hip:'90'};assert.deepEqual(readModelToolSettings('body-shape',custom),custom);
 for(const invalid of [{...current,customBody:true},{...custom,height:'155cm'},{...custom,chest:'78'},{...custom,waist:'105'},{...custom,hip:'89'},{...custom,chest:79},{...custom,chest:''},{...custom,hip:'Infinity'},{...custom,unknown:'x'},{...current,chest:'79'}])assert.equal(readModelToolSettings('body-shape',invalid),null);
 const hidden={...custom,customBody:false,gender:'女の子'};assert.deepEqual(readModelToolSettings('body-shape',hidden),hidden);const offPrompt=modelToolSettingsPrompt('body-shape',hidden);assert(offPrompt.includes('体型: 筋肉質'));assert(!offPrompt.includes('胸囲:'));assert(!offPrompt.includes('身長:'));const onPrompt=modelToolSettingsPrompt('body-shape',custom);assert(onPrompt.includes('カスタムボディ: オン'));assert(onPrompt.includes('身長: 165cm'));assert(onPrompt.includes('バスト/胸囲: 79cm'));assert(onPrompt.includes('ウエスト/腹囲: 26cm'));assert(onPrompt.includes('ヒップ: 90cm'));assert(!onPrompt.includes('体型: 筋肉質'));
});
for(const observed of [{gender:'男性',height:'190cm',chest:'143',waist:'145',hip:'132'},{gender:'男の子',height:'170cm',chest:'89',waist:'82',hip:'86'},{gender:'女性',height:'180cm',chest:'119',waist:'104',hip:'122'},{gender:'女の子',height:'160cm',chest:'96',waist:'84',hip:'92'}])test(`body ${observed.gender}: custom dimensions in actual request/pending/persistence reload and reuse, OFF retains but excludes dimensions from prompt`,async()=>{
 const feature='body-shape',settings={...defaultModelToolSettings(feature),...observed,customBody:true};const t=await mount(feature);let saved:any;try{await t.sources();await t.call(()=>t.f.current.setInputState(settings));await t.call(()=>t.f.current.generate({brief:'Custom body'}));assert.equal(t.f.calls.length,1);const c=t.f.calls[0];assert.equal(c.action,'model-matrix');assert.equal(c.body.featureType,'lightchain-body-shape');assert.deepEqual(c.pending.inputState,settings);assert(c.body.productDescription.includes('身長: '+observed.height));assert(c.body.productDescription.includes('バスト/胸囲: '+observed.chest+'cm'));assert(c.body.productDescription.includes('ウエスト/腹囲: '+observed.waist+'cm'));assert(c.body.productDescription.includes('ヒップ: '+observed.hip+'cm'));assert.deepEqual(t.f.persists[0].metadata.inputState,settings);assert.equal(t.f.acks.length,1);assert.equal(session.size,0);saved=structuredClone(t.f.artifacts.at(-1));}finally{await t.close();}
 const u=await mount(feature,{artifact:saved,job:saved.sourceJobId});try{assert.equal(u.f.current.status,'saved');assert.deepEqual(u.f.current.inputState,settings);assert.equal(u.f.current.result.imageId,saved.metadata.imageId);assert.equal(u.f.current.result.jobId,saved.sourceJobId);assert.equal(u.f.current.result.storagePath,saved.metadata.storagePath);await u.call(()=>u.f.current.setInputState(chooseModelCustomBody(u.f.current.inputState,false)));const off=structuredClone(u.f.current.inputState);assert.equal(off.chest,observed.chest);assert.equal(off.customBody,false);await u.call(()=>u.f.current.generate({brief:'Preset current draft'}));assert.equal(u.f.calls.length,1);assert(!u.f.calls[0].body.productDescription.includes('身長:'));assert(!u.f.calls[0].body.productDescription.includes('胸囲:'));assert.deepEqual(u.f.persists[0].metadata.inputState,off);await u.call(()=>u.f.current.setInputState(chooseModelCustomBody(u.f.current.inputState,true)));assert.deepEqual(u.f.current.inputState,settings);}finally{await u.close();}
});
test('body legacy artifact preserves prior values and identity; explicit custom draft does not recover unavailable-original truth',async()=>{
 const feature='body-shape',job='legacy-body-job',imageId=crypto.randomUUID(),legacy={aspectRatio:'4:5',resolution:'2K',gender:'女性',bodyShape:'筋肉質'},artifact={id:imageId,brandId:'brand',scopeId:'owner',featureType:'lightchain-body-shape-provider-result',sourceJobId:job,createdAt:'2026-10-06',title:'Legacy body',imageUrl:'',metadata:{toolId:feature,providerResultArtifact:true,imageId,storagePath:'generated-images/'+imageId,brief:'original body',inputState:legacy,materialSlots:[{key:'primary',fileName:'original',materialKind:'primary',imageUrl:'local-canvas-asset://original-body'}]}};const original=structuredClone(artifact);const t=await mount(feature,{artifact,job});try{assert.equal(t.f.current.status,'unavailable');assert.deepEqual(t.f.current.inputState,legacy);assert.equal(t.f.current.result.imageId,imageId);await t.call(()=>t.f.current.generate({brief:'Blocked old settings'}));assert.equal(t.f.calls.length,0);const draft=chooseModelCustomBody(legacy,true);await t.call(()=>t.f.current.setInputState(draft));assert.deepEqual(t.f.current.inputState,draft);assert.equal(t.f.current.inputsAvailable,false);assert.equal(t.f.current.originalInputsAvailable,false);assert.equal(t.f.current.result.imageId,imageId);assert.deepEqual(artifact,original);assert.equal(t.f.persists.length,0);await t.call(()=>t.f.current.generate({brief:'Explicit new draft'}));assert.equal(t.f.calls.length,1);assert.deepEqual(t.f.calls[0].pending.inputState,draft);}finally{await t.close();}
});
test('body old pending snapshot stays unchanged and reconciles once without inferred mode or a new request',async()=>{
 const feature='body-shape',requestId=crypto.randomUUID(),job='ai-old-body',imageId=crypto.randomUUID(),legacy={aspectRatio:'4:5',resolution:'2K',gender:'女性',bodyShape:'筋肉質'},pending={requestId,originJob:job,brief:'old body',referenceNote:'',inputState:legacy,materialSlots:[]};const t=await mount(feature,{job,pending});try{const raw=[...session.entries()];await t.call(()=>t.f.current.setInputState(chooseModelCustomBody(legacy,true)));assert.deepEqual([...session.entries()],raw);assert.deepEqual(t.f.current.inputState,legacy);t.f.readReceipt={success:true,requestId,state:'completed',jobId:job,provider:'workers_ai',persistenceStatus:'completed',requestedCandidateCount:1,persistedCandidateCount:1,matrix:[{bodyType:'regular',ageGroup:'20s',imageId,storagePath:'generated-images/'+imageId,imageUrl:'https://fixture.invalid/'+imageId,jobId:job,persistenceStatus:'completed',provider:'workers_ai'}]};await t.call(()=>t.f.current.reconcile());assert.equal(t.f.reads,1);assert.equal(t.f.calls.length,0);assert.equal(t.f.current.result.imageId,imageId);assert.equal(t.f.current.status,'unavailable');assert.deepEqual(t.f.current.inputState,legacy);assert.deepEqual(t.f.persists[0].metadata.inputState,legacy);assert.equal(session.size,0);}finally{await t.close();}
});

const modeArtifact=(feature:string,inputState:any,job='prior-mode-job')=>{const imageId=crypto.randomUUID(),primaryId=crypto.randomUUID(),secondaryId=crypto.randomUUID();return{id:imageId,brandId:'brand',scopeId:'owner',featureType:'lightchain-'+feature+'-provider-result',sourceJobId:job,createdAt:'2026-10-06',title:'Saved mode',imageUrl:'',metadata:{toolId:feature,providerResultArtifact:true,imageId,storagePath:'generated-images/'+imageId,brief:'saved mode',referenceNote:'REFERENCE_NOTE_CANARY',inputState,materialSlots:[{key:'primary',fileName:'primary',materialKind:'primary',sourceImageId:primaryId,sourceStoragePath:'generated-images/'+primaryId,imageUrl:''},{key:'secondary',fileName:'reference',materialKind:'secondary',sourceImageId:secondaryId,sourceStoragePath:'generated-images/'+secondaryId,imageUrl:''}]}};};
for(const feature of ['model-face','model-change','pose-change','background-change'])test(`${feature}: Library selection re-signs canonical source and preserves existing identity; actual request/save/reload/reuse retain exact reference`,async()=>{
 const seed=modeArtifact(feature,defaultModelToolSettings(feature)),t=await mount(feature,{artifact:seed,job:seed.sourceJobId});let saved:any;try{const identity=structuredClone(t.f.current.result),primary=structuredClone(t.f.current.slots.primary),available=t.f.current.inputsAvailable,original=t.f.current.originalInputsAvailable;await t.call(()=>t.f.current.selectModelReference({imageUrl:'https://expired.invalid/preview',imageId:'selected-reference',storagePath:'generated-images/selected-reference'}));const ref=t.f.current.slots.secondary;assert.equal(ref.sourceImageId,'selected-reference');assert.equal(ref.sourceStoragePath,'generated-images/selected-reference');assert.equal(ref.imageUrl,'https://fixture.invalid/generated-images/selected-reference');assert.deepEqual(t.f.current.slots.primary,primary);assert.deepEqual(t.f.current.result,identity);assert.equal(t.f.current.inputsAvailable,available);assert.equal(t.f.current.originalInputsAvailable,original);assert.equal(t.f.calls.length,0);assert.equal(t.f.persists.length,0);await t.call(()=>t.f.current.generate({brief:'Selected Library reference'}));assert.equal(t.f.calls.length,1);const c=t.f.calls[0];assert.equal(c.body.modelReferenceSourceImageId,ref.sourceImageId);assert.equal(c.body.modelReferenceSourceStoragePath,ref.sourceStoragePath);assert.equal(c.body.modelReferenceFileName,'参考画像');assert.equal(c.pending.materialSlots[1].sourceImageId,ref.sourceImageId);assert.equal(c.pending.materialSlots[1].sourceStoragePath,ref.sourceStoragePath);assert.equal(c.pending.materialSlots[1].imageUrl,'');assert.equal(t.f.persists[0].metadata.materialSlots[1].sourceImageId,ref.sourceImageId);saved=structuredClone(t.f.artifacts.at(-1));assert.equal(t.f.acks.length,1);assert.equal(session.size,0);}finally{await t.close();}
 const u=await mount(feature,{artifact:saved,job:saved.sourceJobId});try{assert.equal(u.f.current.status,'saved');assert.equal(u.f.current.slots.secondary.sourceImageId,'selected-reference');assert.equal(u.f.current.slots.secondary.sourceStoragePath,'generated-images/selected-reference');assert.equal(u.f.current.result.imageId,saved.metadata.imageId);assert.equal(u.f.current.result.jobId,saved.sourceJobId);await u.call(()=>u.f.current.generate({brief:'Reuse selected reference'}));assert.equal(u.f.calls.length,1);assert.equal(u.f.calls[0].body.modelReferenceSourceImageId,'selected-reference');assert.equal(u.f.calls[0].body.modelReferenceSourceStoragePath,'generated-images/selected-reference');}finally{await u.close();}
});
test('Library invalid identity, signing/load failure and unavailable original truth preserve existing source/result; unrelated features stay unchanged',async()=>{
 for(const reason of ['missingpath','mismatch','traversal','signing','load']){const feature='model-face',seed=modeArtifact(feature,defaultModelToolSettings(feature)),t=await mount(feature,{artifact:seed,job:seed.sourceJobId});try{const before=structuredClone({slots:t.f.current.slots,result:t.f.current.result,available:t.f.current.inputsAvailable,original:t.f.current.originalInputsAvailable});t.f.signFailure=reason==='signing';t.f.imageLoadError=reason==='load';const selection={imageUrl:'https://expired.invalid/untrusted',imageId:'new-reference',storagePath:reason==='missingpath'?undefined:reason==='mismatch'?'generated-images/other':reason==='traversal'?'generated-images/../other':'generated-images/new-reference'};await t.call(()=>t.f.current.selectModelReference(selection));assert.deepEqual(t.f.current.slots,before.slots);assert.deepEqual(t.f.current.result,before.result);assert.equal(t.f.current.inputsAvailable,before.available);assert.equal(t.f.current.originalInputsAvailable,before.original);assert(t.f.current.error.includes('元の入力は保持'));assert.equal(t.f.calls.length,0);assert.equal(t.f.persists.length,0);}finally{await t.close();}}
 const feature='pose-change',seed=modeArtifact(feature,defaultModelToolSettings(feature)),missing='local-canvas-asset://missing-library-primary';seed.metadata.materialSlots[0]={key:'primary',fileName:'missing',materialKind:'primary',imageUrl:missing} as any;const u=await mount(feature,{artifact:seed,job:seed.sourceJobId,missingSources:[missing]});try{await u.call(()=>u.f.current.selectModelReference({imageUrl:'https://expired.invalid',imageId:'reference-selected',storagePath:'generated-images/reference-selected'}));assert.equal(u.f.current.slots.secondary.sourceImageId,'reference-selected');assert.equal(u.f.current.slots.primary,null);assert.equal(u.f.current.inputsAvailable,false);assert.equal(u.f.current.originalInputsAvailable,false);await u.call(()=>u.f.current.generate({brief:'Missing original'}));assert.equal(u.f.calls.length,0);}finally{await u.close();}
 const v=await mount('body-shape');try{const before=structuredClone(v.f.current.inputState);await v.call(()=>v.f.current.selectModelReference({imageUrl:'https://expired.invalid',imageId:'not-body-reference',storagePath:'generated-images/not-body-reference'}));assert.equal(v.f.current.slots.secondary,null);assert.deepEqual(v.f.current.inputState,before);assert.equal(v.f.signCalls.length,0);assert.equal(v.f.calls.length,0);}finally{await v.close();}
});
test('Library stale callback/auth and custom-mode changes during signing cannot replace source or dispatch',async()=>{
 const old=await mount('model-face');try{await old.sources();const stale=old.f.current.selectModelReference;old.f.auth=auth('new-owner');await old.render();const after=structuredClone(old.f.current.slots),count=old.f.signCalls.length;await old.call(()=>stale({imageUrl:'https://expired.invalid',imageId:'old-owner-reference',storagePath:'generated-images/old-owner-reference'}));assert.deepEqual(old.f.current.slots,after);assert.equal(old.f.signCalls.length,count);assert.equal(old.f.calls.length,0);}finally{await old.close();}
 for(const reason of ['auth','custom']){const feature=reason==='custom'?'pose-change':'model-face',t=await mount(feature);try{await t.sources();const before=structuredClone(t.f.current.slots.secondary);t.f.holdSigning=true;let pick:Promise<void>;await act(async()=>{pick=t.f.current.selectModelReference({imageUrl:'https://expired.invalid',imageId:'inflight-reference',storagePath:'generated-images/inflight-reference'});await Promise.resolve();});assert.equal(typeof t.f.releaseSigning,'function');if(reason==='auth'){t.f.auth=auth('other-owner');await t.render();}else await t.call(()=>t.f.current.setInputState({...t.f.current.inputState,inputMode:'custom',customDescription:'Current draft'}));const after=structuredClone(t.f.current.slots);t.f.releaseSigning();await t.call(()=>pick!);assert.deepEqual(t.f.current.slots,after);if(reason==='custom')assert.deepEqual(t.f.current.slots.secondary,before);assert.equal(t.f.calls.length,0);assert.equal(t.f.persists.length,0);}finally{await t.close();}}
});
test('Library pending/running fences keep the original request and reference unchanged; no new signing or replay',async()=>{
 const feature='pose-change',pending={requestId:crypto.randomUUID(),originJob:null,brief:'pending reference',referenceNote:'',inputState:defaultModelToolSettings(feature),materialSlots:[]},t=await mount(feature,{pending});try{const raw=[...session.entries()];await t.call(()=>t.f.current.selectModelReference({imageUrl:'https://expired.invalid',imageId:'blocked-reference',storagePath:'generated-images/blocked-reference'}));assert.deepEqual([...session.entries()],raw);assert.equal(t.f.signCalls.length,0);assert.equal(t.f.current.slots.secondary,null);assert.equal(t.f.calls.length,0);}finally{await t.close();}
 const u=await mount('model-face',{hold:true});try{await u.sources();const before=structuredClone(u.f.current.slots.secondary);let operation:Promise<any>;await act(async()=>{operation=u.f.current.generate({brief:'Existing operation'});await Promise.resolve();});await u.settle();const count=u.f.signCalls.length;await u.call(()=>u.f.current.selectModelReference({imageUrl:'https://expired.invalid',imageId:'blocked-reference',storagePath:'generated-images/blocked-reference'}));assert.deepEqual(u.f.current.slots.secondary,before);assert.equal(u.f.signCalls.length,count);assert.equal(u.f.calls.length,1);u.f.release();await u.call(()=>operation!);assert.equal(u.f.calls[0].body.modelReferenceFileName,'secondary.svg');assert.equal(u.f.calls.length,1);}finally{await u.close();}
});
test('Library platform source persists original bytes in local asset storage and reloads without a fake generated identity; write failure preserves input',async()=>{
 const url='/assets/printing/blank-white-tshirt.svg',id='platform-blank-white-tshirt-v1',bytes='<svg xmlns="http://www.w3.org/2000/svg" width="120" height="160"/>',blockedFetch=globalThis.fetch;globalThis.fetch=async(input:any)=>{assert.equal(input,url);return new Response(new Blob([bytes],{type:'image/svg+xml'}));};let saved:any;
 const t=await mount('pose-change');try{await t.sources();const writes=t.f.localWrites.length;await t.call(()=>t.f.current.selectModelReference({imageUrl:url,imageId:id,storagePath:url}));const ref=t.f.current.slots.secondary;assert.equal(ref.name,'blank-white-tshirt.svg');assert.equal(ref.imageUrl,url);assert.equal(ref.sourceImageId,undefined);assert.equal(ref.sourceStoragePath,undefined);assert(ref.localAssetRef.startsWith('local-canvas-asset://'));assert.equal(t.f.localWrites.length,writes+1);assert.equal(t.f.localWrites.at(-1).key,ref.sourceMetadata.sourceRevision.revision);assert.equal(t.f.localWrites.at(-1).bytes,bytes);await t.call(()=>t.f.current.generate({brief:'Platform reference'}));assert.equal(t.f.calls.length,1);assert.equal(t.f.calls[0].body.modelReferenceSourceImageId,undefined);const stored=t.f.persists[0].metadata.materialSlots[1];assert.equal(stored.imageUrl,ref.localAssetRef);assert.equal(stored.sourceImageId,null);assert.equal(stored.persistenceStatus,'persistent');saved=structuredClone(t.f.artifacts.at(-1));}finally{await t.close();globalThis.fetch=blockedFetch;}
 const u=await mount('pose-change',{artifact:saved,job:saved.sourceJobId});try{assert.equal(u.f.current.status,'saved');assert.equal(u.f.current.slots.secondary.name,'blank-white-tshirt.svg');assert.equal(u.f.current.slots.secondary.localAssetRef,saved.metadata.materialSlots[1].imageUrl);assert.equal(u.f.current.slots.secondary.sourceImageId,undefined);assert.equal(u.f.current.result.imageId,saved.metadata.imageId);}finally{await u.close();}
 const v=await mount('pose-change');try{await v.sources();const before=structuredClone(v.f.current.slots.secondary);v.f.assetPersistFailure=true;globalThis.fetch=async(input:any)=>{assert.equal(input,url);return new Response(new Blob([bytes],{type:'image/svg+xml'}));};await v.call(()=>v.f.current.selectModelReference({imageUrl:url,imageId:id,storagePath:url}));assert.deepEqual(v.f.current.slots.secondary,before);assert.equal(v.f.calls.length,0);assert(v.f.current.error.includes('元の入力は保持'));}finally{await v.close();globalThis.fetch=blockedFetch;}
});

for(const feature of ['pose-change','background-change'])for(const mode of ['reference','custom'])test(`${feature}/${mode}: immutable mode partitions actual matrix dispatch, full saved inputs reload/reuse and return mode preserve identity`,async()=>{
 const settings={...defaultModelToolSettings(feature),inputMode:mode,customDescription:'CUSTOM_DESCRIPTION_CANARY'};const seed=modeArtifact(feature,defaultModelToolSettings(feature));const t=await mount(feature,{artifact:seed,job:seed.sourceJobId});let saved:any;try{
 const slots=structuredClone(t.f.current.slots);await t.call(()=>t.f.current.setInputState(settings));await t.call(()=>t.f.current.generate({brief:'Mode request'}));assert.equal(t.f.calls.length,1);const c=t.f.calls[0];assert.equal(c.action,'model-matrix');assert.equal(c.body.imageUrl,slots.primary.imageUrl);assert.deepEqual(c.pending.inputState,settings);assert.equal(c.pending.materialSlots.length,2);assert.equal(c.pending.referenceNote,'REFERENCE_NOTE_CANARY');
 const fields=['modelReferenceImageUrl','modelReferenceFileName','modelReferenceSourceImageId','modelReferenceSourceStoragePath'];if(mode==='custom'){for(const key of fields)assert.equal(Object.hasOwn(c.body,key),false);assert.equal(c.body.materialReferences.length,1);assert.equal(c.body.materialReferences[0].key,'primary');assert(c.body.productDescription.includes('CUSTOM_DESCRIPTION_CANARY'));assert(!c.body.productDescription.includes('REFERENCE_NOTE_CANARY'));}
 else{assert.equal(c.body.modelReferenceImageUrl,slots.secondary.imageUrl);assert.equal(c.body.modelReferenceFileName,slots.secondary.name);assert.equal(c.body.modelReferenceSourceImageId,slots.secondary.sourceImageId);assert.equal(c.body.modelReferenceSourceStoragePath,slots.secondary.sourceStoragePath);assert.equal(c.body.materialReferences.length,2);assert(c.body.productDescription.includes('REFERENCE_NOTE_CANARY'));assert(!c.body.productDescription.includes('CUSTOM_DESCRIPTION_CANARY'));}
 assert.deepEqual(t.f.persists[0].metadata.inputState,settings);assert.equal(t.f.persists[0].metadata.materialSlots.length,2);assert.equal(t.f.persists[0].metadata.materialSlots[1].sourceImageId,slots.secondary.sourceImageId);assert.equal(t.f.persists[0].metadata.referenceNote,'REFERENCE_NOTE_CANARY');saved=structuredClone(t.f.artifacts.at(-1));assert.equal(t.f.current.result.jobId,saved.sourceJobId);assert.equal(t.f.current.result.imageId,saved.metadata.imageId);assert.equal(t.f.current.result.storagePath,saved.metadata.storagePath);
 const result=structuredClone(t.f.current.result);await t.call(()=>t.f.current.setInputState({...settings,inputMode:mode==='custom'?'reference':'custom'}));assert.deepEqual(t.f.current.result,result);assert.equal(t.f.calls.length,1);assert.equal(t.f.current.slots.secondary.sourceImageId,slots.secondary.sourceImageId);
 }finally{await t.close();}
 const u=await mount(feature,{artifact:saved,job:saved.sourceJobId});try{assert.deepEqual(u.f.current.inputState,settings);assert.equal(u.f.current.result.jobId,saved.sourceJobId);assert.equal(u.f.current.result.imageId,saved.metadata.imageId);await u.call(()=>u.f.current.generate({brief:'Mode reuse'}));assert.equal(u.f.calls.length,1);assert.deepEqual(u.f.persists[0].metadata.inputState,settings);}finally{await u.close();}
});
for(const feature of ['pose-change','background-change'])test(`${feature}: exact4 and legacy2 codec, missing/invalid/foreign mode or description rejected; legacy draft does not restore sources or mutate artifact`,async()=>{
 const legacy={aspectRatio:'4:5',resolution:'2K'};assert.equal(readModelToolSettings(feature,legacy),null);assert.deepEqual(readLegacyModelDescriptionSettings(feature,legacy),legacy);assert.equal(readLegacyModelDescriptionSettings(feature,{...legacy,extra:true}),null);
 const valid={...legacy,inputMode:'custom',customDescription:''};assert.deepEqual(readModelToolSettings(feature,valid),valid);for(const bad of [{...valid,inputMode:'unknown'},{...valid,customDescription:'a'.repeat(801)},{...valid,customDescription:null},{...valid,unknownField:'x'},{...legacy,inputMode:'custom'}])assert.equal(readModelToolSettings(feature,bad),null);
 const artifact=modeArtifact(feature,legacy),original=structuredClone(artifact);const t=await mount(feature,{artifact,job:artifact.sourceJobId});try{assert.equal(t.f.current.status,'unavailable');assert.deepEqual(t.f.current.inputState,legacy);assert.equal(t.f.current.result.imageId,artifact.metadata.imageId);await t.call(()=>t.f.current.generate({brief:'Blocked legacy'}));assert.equal(t.f.calls.length,0);assert.equal(t.f.persists.length,0);await t.call(()=>t.f.current.setInputState(valid));assert.deepEqual(t.f.current.inputState,valid);assert.equal(t.f.current.inputsAvailable,false);assert.equal(t.f.current.originalInputsAvailable,false);assert.equal(t.f.current.status,'unavailable');assert.deepEqual(artifact,original);assert.equal(t.f.calls.length,0);assert.equal(t.f.persists.length,0);await t.call(()=>t.f.current.generate({brief:'Explicit current draft'}));assert.equal(t.f.calls.length,1);assert.deepEqual(t.f.persists[0].metadata.inputState,valid);}finally{await t.close();}
});
for(const feature of ['pose-change','background-change'])test(`${feature}: old pending snapshot never rewritten by explicit mode setter; no dispatch`,async()=>{const legacy={aspectRatio:'4:5',resolution:'2K'},pending={requestId:crypto.randomUUID(),originJob:null,brief:'old pending',referenceNote:'OLD_NOTE',inputState:legacy,materialSlots:[]};const t=await mount(feature,{pending});try{const raw=[...session.entries()];assert.deepEqual(t.f.current.inputState,legacy);await t.call(()=>t.f.current.setInputState({...legacy,inputMode:'custom',customDescription:'new draft'}));assert.deepEqual(t.f.current.inputState,legacy);assert.deepEqual([...session.entries()],raw);assert.equal(t.f.calls.length,0);assert.equal(t.f.persists.length,0);}finally{await t.close();}});
test('held custom request ignores live mode/description changes after async dispatch; pending and save use original snapshot',async()=>{const feature='pose-change',seed=modeArtifact(feature,defaultModelToolSettings(feature));const t=await mount(feature,{artifact:seed,job:seed.sourceJobId,hold:true});try{const settings={...defaultModelToolSettings(feature),inputMode:'custom',customDescription:'SNAPSHOT_DESCRIPTION'};await t.call(()=>t.f.current.setInputState(settings));let promise:Promise<any>;await act(async()=>{promise=t.f.current.generate({brief:'Snapshot'});await Promise.resolve();});await t.settle();assert.equal(t.f.calls.length,1);await t.call(()=>t.f.current.setInputState({...settings,inputMode:'reference',customDescription:'LIVE'}));t.f.current.inputState.inputMode='reference';t.f.current.inputState.customDescription='LIVE';t.f.release();await t.call(()=>promise!);assert(t.f.calls[0].body.productDescription.includes('SNAPSHOT_DESCRIPTION'));assert(!Object.hasOwn(t.f.calls[0].body,'modelReferenceImageUrl'));assert.deepEqual(t.f.persists[0].metadata.inputState,settings);assert.equal(t.f.persists[0].metadata.materialSlots.length,2);}finally{await t.close();}});
for(const feature of ['pose-change','background-change'])test(`${feature}: custom draft with missing primary never promotes availability or dispatches`,async()=>{
 const settings={...defaultModelToolSettings(feature),inputMode:'custom',customDescription:'current description'},artifact=modeArtifact(feature,settings),missing='local-canvas-asset://missing-custom-primary';artifact.metadata.materialSlots[0]={key:'primary',fileName:'primary',materialKind:'primary',imageUrl:missing} as any;
 const t=await mount(feature,{artifact,job:artifact.sourceJobId,missingSources:[missing]});try{const identity=structuredClone(t.f.current.result);assert.equal(t.f.current.slots.primary,null);assert.equal(t.f.current.inputsAvailable,false);await t.call(()=>t.f.current.setInputState({...settings,customDescription:'edited description'}));assert.equal(t.f.current.inputsAvailable,false);assert.equal(t.f.current.originalInputsAvailable,false);assert.equal(t.f.current.status,'unavailable');assert.deepEqual(t.f.current.result,identity);await t.call(()=>t.f.current.generate({brief:'missing primary'}));assert.equal(t.f.calls.length,0);assert.equal(t.f.persists.length,0);assert.equal(t.f.acks.length,0);}finally{await t.close();}
});
