import assert from 'node:assert/strict';
import test from 'node:test';
import fs from 'node:fs/promises';
import ts from 'typescript';
const source=await fs.readFile(process.env.HEAVY_BATCH_WORKBENCH_SOURCE??new URL('../src/pages/LightchainWorkbenchPage.tsx',import.meta.url),'utf8');
const ast=ts.createSourceFile('page.tsx',source,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX),nodes=[];const walk=n=>{nodes.push(n);ts.forEachChild(n,walk);};walk(ast);
const fn=nodes.find(n=>ts.isFunctionDeclaration(n)&&n.name?.text==='executeFittingBatch');
const evalFn=b=>new Function('bindings',`with(bindings){${ts.transpile(`return (${fn.getText(ast)});`,{target:ts.ScriptTarget.ES2022})}}`)(new Proxy(b,{has:()=>true,get:(o,k)=>k===Symbol.unscopables?undefined:k in o?o[k]:globalThis[k]}));
function fixture({injected=false,revoked=false,failCapture=false}={}){
 const events=[],scope={userId:'alice',brandId:'brand',featureId:'ai-fitting'},key=JSON.stringify(['alice','brand','ai-fitting']);let current=true;
 const execution={assertCurrent:async()=>{if(!current)throw Error('revoked');}};
 const b={fittingBatchCanExecute:true,fittingBatchReady:true,fittingBatchBusyRef:{current:false},user:{id:'alice'},currentBrand:{id:'brand'},selectedTool:{id:'ai-fitting'},fittingBatchScope:key,fittingBatchScopeRef:{current:key},fittingBatchExecution:injected?execution:undefined,cloudflareDataPlane:{origin:'local'},fittingBatchStorage:{},captureCurrentAuthBrandFence:brand=>{assert.equal(brand,'brand');return 'captured-fence';},assertCurrentAuthBrandFence:(fence)=>{assert.equal(fence,'captured-fence');if(!current)throw Error('revoked');},setFittingBatchBusy:v=>events.push('busy:'+v),setFittingBatchTasks:()=>events.push('ui-refresh'),readFittingBatch:async(_s,received)=>{assert.deepEqual(received,scope);events.push('read');return [{id:'ready-task',status:'ready'},{id:'unknown-task',status:'unknown'}];},runFittingBatchTask:async(_s,received,id,adapter)=>{await adapter.assertCurrent();assert.deepEqual(received,scope);events.push('run:'+id);},toast:{error:()=>events.push('error')},getErrorMessage:e=>e.message,
 getCanvasDocument:async(id,brand,context)=>{assert.equal(brand,'brand');assert.equal(context.userId,'alice');context.assertContext();events.push('canvas-get:'+id);},createCanvasDocument:async(input,context)=>{context.assertContext();assert.equal(input.brandId,'brand');assert.equal(context.userId,'alice');events.push('canvas-create:'+input.documentId);},updateCanvasDocument:async(input,context)=>{context.assertContext();assert.equal(input.expectedRevision,4);events.push('canvas-update:'+input.documentId);},
 createFittingBatchRuntime:async(client,received,transport,assertCurrent)=>{assert.equal(client,b.cloudflareDataPlane);assert.deepEqual(received,scope);events.push('capture');if(failCapture)throw Error('capture_failed');if(revoked)current=false;assertCurrent();await transport.get('own-doc');await transport.create('own-doc',{title:'title',snapshot:{}});await transport.update('own-doc',4,{title:'title',snapshot:{}});return execution;}};
 return {b,events,run:evalFn(b)};
}
test('actual page binds production runtime and owner context before running only ready tasks',async()=>{const f=fixture();await f.run();assert.ok(f.events.indexOf('capture')<f.events.indexOf('run:ready-task'));assert.ok(f.events.includes('canvas-get:own-doc'));assert.ok(f.events.includes('canvas-create:own-doc'));assert.ok(f.events.includes('canvas-update:own-doc'));assert.ok(!f.events.includes('run:unknown-task'));assert.equal(f.b.fittingBatchBusyRef.current,false);});
test('existing explicit adapter remains supported without assembling a production adapter',async()=>{const f=fixture({injected:true});await f.run('unknown-task');assert.ok(!f.events.includes('capture'));assert.ok(f.events.includes('run:unknown-task'));});
test('capture error or authentication revocation cannot enter task runner',async()=>{for(const flags of [{revoked:true},{failCapture:true}]){const f=fixture(flags);await f.run();assert.ok(f.events.includes('error'));assert.ok(!f.events.some(e=>e.startsWith('run:')));assert.ok(!f.events.some(e=>e.startsWith('canvas-')));assert.equal(f.b.fittingBatchBusyRef.current,false);}});
test('missing client/adapter, unloaded scope, or already busy cannot assemble or execute',async()=>{for(const key of ['fittingBatchCanExecute','fittingBatchReady','busy']){const f=fixture();if(key==='busy')f.b.fittingBatchBusyRef.current=true;else f.b[key]=false;await f.run();assert.deepEqual(f.events,[]);}});
