import assert from 'node:assert/strict';
import test, { after } from 'node:test';
import {deflateSync,inflateSync} from 'node:zlib';
import { createServer } from 'vite';
import fs from 'node:fs/promises';
const vite = await createServer({ configFile:false,envFile:false,appType:'custom',logLevel:'silent',server:{middlewareMode:true} });
const material = await vite.ssrLoadModule('/src/lib/materialProtectedComposite.ts');
const edit = await vite.ssrLoadModule('/src/lib/cloudflareProtectedImageEdit.ts');
const openai = await vite.ssrLoadModule('/src/lib/protectedOpenAIImageEdit.ts');
const projectionModule = await vite.ssrLoadModule('/src/lib/protectedOpenAIProjection.ts');
const projectionPreparation = await vite.ssrLoadModule('/src/lib/prepareProtectedOpenAIProjection.ts');
const canvasBatch=await vite.ssrLoadModule('/src/lib/canvasProtectedBatchComposite.ts');
const image=await vite.ssrLoadModule('/src/lib/cloudflareImageAI.ts');
const local = await vite.ssrLoadModule('/src/lib/localWorkspaceArtifacts.ts');
const contract = await vite.ssrLoadModule('/src/lib/protectedImageEditContract.ts');
const originalGlobals = { window:globalThis.window,Image:globalThis.Image,ImageData:globalThis.ImageData,document:globalThis.document,fetch:globalThis.fetch };
after(async()=>{Object.assign(globalThis,originalGlobals);await vite.close();});
const encode = (width,height,pixels) => {const header=Buffer.alloc(24);header.set([137,80,78,71,13,10,26,10]);header.write('IHDR',12);header.writeUInt32BE(width,16);header.writeUInt32BE(height,20);return 'data:image/png;base64,'+Buffer.concat([header,deflateSync(Buffer.from(JSON.stringify({width,height,pixels:[...pixels]})))]).toString('base64');};
const decode = url => JSON.parse(inflateSync(Buffer.from(url.split(',')[1],'base64').subarray(24)).toString());
let savedPng;const mediaPixels=new Map();
const readSavedImage=async()=> 'https://final.test/fixture';
let decodes = 0, encodes = 0;
function setup() {
 const store=new Map();
 globalThis.fetch=async url=>{assert(String(url).startsWith('https://final.test/'));savedPng=mediaPixels.get(String(url))??savedPng;if(!savedPng)throw new Error('missing_saved_png');return new Response(Buffer.from(savedPng.split(',')[1],'base64'),{headers:{'content-type':'image/png'}});};
 globalThis.window={localStorage:{getItem:key=>store.get(key)??null,setItem:(key,value)=>store.set(key,value),removeItem:key=>store.delete(key)},dispatchEvent(){}};
 globalThis.ImageData=class {constructor(data,width,height){Object.assign(this,{data,width,height});}};
 globalThis.Image=class {set src(url){decodes++;try {const v=decode(url);Object.assign(this,{naturalWidth:v.width,naturalHeight:v.height,width:v.width,height:v.height,pixels:v.pixels});queueMicrotask(()=>this.onload());}catch{queueMicrotask(()=>this.onerror());}}};
 globalThis.document={createElement:()=>{
   const canvas={width:0,height:0,pixels:[]};
   const context={fillRect(x,y,w,h){if(!canvas.pixels.length)canvas.pixels=new Uint8ClampedArray(canvas.width*canvas.height*4);for(let j=y;j<y+h;j++)for(let i=x;i<x+w;i++)canvas.pixels.set([0,0,0,255],(j*canvas.width+i)*4);},clearRect(){canvas.pixels=new Uint8ClampedArray(canvas.width*canvas.height*4);},
    drawImage(image,...args){
      const [sx,sy,sw,sh,dx,dy,width,height]=args.length===8?args:[0,0,image.width,image.height,args[0]??0,args[1]??0,args[2]??image.width,args[3]??image.height];
      if(!canvas.pixels.length) canvas.pixels=new Uint8ClampedArray(canvas.width*canvas.height*4);
      for(let y=Math.max(0,Math.floor(dy));y<Math.min(canvas.height,Math.ceil(dy+height));y++)for(let x=Math.max(0,Math.floor(dx));x<Math.min(canvas.width,Math.ceil(dx+width));x++) {
       if(x+.5<dx||x+.5>=dx+width||y+.5<dy||y+.5>=dy+height)continue;
       const at=(Math.min(image.height-1,Math.floor(sy+(y+.5-dy)/height*sh))*image.width+Math.min(image.width-1,Math.floor(sx+(x+.5-dx)/width*sw)))*4;
       canvas.pixels.set(image.pixels.slice(at,at+4),(y*canvas.width+x)*4);
      }
    },getImageData:()=>({data:new Uint8ClampedArray(canvas.pixels)}),putImageData(image){canvas.pixels=new Uint8ClampedArray(image.data);}};
   canvas.getContext=()=>context;canvas.toDataURL=()=>{encodes++;return encode(canvas.width,canvas.height,canvas.pixels);};return canvas;
 }};
 decodes=encodes=0;return store;
}
const missing=()=>{throw new Error('cloudflare_api_404_workspace_artifact_not_found');};
async function fixture(feature='canvas-partial-edit',bind=true,generated=false){
 setup();mediaPixels.clear();const original=encode(2,2,[3,5,9,0,21,31,41,255,61,71,81,255,91,101,111,255]),mask=encode(2,2,[0,0,0,255,0,0,0,255,0,0,0,0,0,0,0,0]);const requestId=crypto.randomUUID();
 const sourceObject={id:'parent',src:original,metadata:{imageId:'original',generation:1}},sourceIdentity=canvasBatch.canvasObjectProtectedIdentity(sourceObject),verifiedObjectSource=generated?undefined:await canvasBatch.resolveCanvasProtectedObjectSource(sourceObject,async source=>source,()=>{});
 const binding=await canvasBatch.prepareCanvasProtectedBatch({sourceIdentity,verifiedObjectSource,sourceImageUrl:original,maskDataUrl:mask,requestId,featureType:feature,brandId:'brand',scopeId:'alice',canvasProjectId:'project',parentObjectId:generated?null:'parent',generation:2,inputSignature:['edit'],assertCurrent:()=>{}});
 const plan={mode:contract.PROTECTED_IMAGE_EDIT_MODE,sourceWidth:2,sourceHeight:2,sourceSha256:await contract.protectedImageDigest(original),maskSha256:await contract.protectedImageDigest(mask),guideIndex:1,coveragePercent:50};
 const map={version:'protected-openai-contain-v1',digestScheme:'sha256-data-url-utf8-v1',stage:{width:2,height:2,primaryDigest:plan.sourceSha256,maskDigest:plan.maskSha256,guideDigest:'a'.repeat(64)},prepared:{width:2,height:2,primaryDigest:'b'.repeat(64),guideDigest:'c'.repeat(64),transform:{x:0,y:0,scaleX:1,scaleY:1}},candidate:{width:1024,height:1024},contain:{x:0,y:0,scale:512},projected:{primaryDigest:'d'.repeat(64),guideDigest:'e'.repeat(64)}};
 const native={version:'canvas-protected-openai-contain-v1',original:{width:2,height:2,digest:plan.sourceSha256,digestScheme:'sha256-data-url-utf8-v1'},stage:{width:2,height:2,primaryDigest:plan.sourceSha256,maskDigest:plan.maskSha256},frame:{x:0,y:0,width:2,height:2},printingSnapshotDigest:await contract.protectedImageDigest(JSON.stringify([])),mapping:map,candidateGeometry:{version:'openai-output-frame-v1',width:1024,height:1024},canvasBatch:binding};
 const prepared={body:{brandId:'brand',prompt:'edit',canvasProjectId:'project',parentObjectId:generated?null:'parent',generation:2,featureType:feature,count:4,canvasProtectedBatchBinding:binding,protectedEdit:plan,protectedOpenAIProjection:map,nativePrintFinalFrame:native},plan,sourceImageUrl:original,maskDataUrl:mask,canvasProtectedBatchBinding:binding};
 const model='gpt-image-1-mini';const receipt={success:true,requestId,state:'completed',recovery:'terminal',requiresProtectedComposite:true,persistenceStatus:'completed',requestedCandidateCount:4,persistedCandidateCount:4,jobId:`ai-${requestId}`,featureType:feature,provider:'openai',backendProvider:'openai-images-api',providerModel:model,resolvedProvider:{provider:'openai',backendProvider:'openai-images-api',model,action:'edit-image',requestId},protectedEdit:plan,metadata:{nativePrintFinalFrame:native,protectedOpenAIProjection:map},images:Array.from({length:4},(_,i)=>({candidateIndex:i,imageId:`ai-${requestId}-${i}`,jobId:`ai-${requestId}`,storagePath:`generated-images/ai-${requestId}-${i}`,provider:'openai',providerModel:model,modelUsed:model,width:1024,height:1024,imageUrl:encode(1024,1024,new Array(1024*1024).fill([120+i,150+i,180+i,255]).flat())}))};
 const lifecycle=bind?await canvasBatch.createCanvasProtectedBatchLifecycle(binding,prepared,{brandId:'brand',userId:'alice'},async()=>{}):undefined;return{binding,prepared,receipt,lifecycle,original,mask,sourceObject,sourceIdentity};
}
function transport(f,{failureIndex,unknownGet=false}={}){const remotes=new Map(),inputs=new Map(),events=[];let failure=failureIndex;
 const save=async input=>{const index=input.imageAI.candidateIndex;events.push(['save',index]);assert.equal(await canvasBatch.canvasBatchHasAllRaw(f.binding),true);if(inputs.has(index))assert.deepEqual(input,inputs.get(index));else inputs.set(index,structuredClone(input));if(index===failure)throw new Error('save_network_unknown');const id='wa-'+input.requestId,remote={success:true,remote:{jobId:id,imageId:id,storagePath:'generated-images/'+id},metadata:input.metadata};remotes.set(input.requestId,remote);mediaPixels.set('https://final.test/'+id,input.imageUrl);return remote;};
 const call=async(path,init)=>{assert(!init?.method||init.method==='GET');assert(!path.includes('provider-actions'),'provider generation forbidden');if(path.startsWith('/v1/media/read?')){const q=new URL('https://local.test'+path).searchParams;assert.equal(q.get('bucket'),'generated-images');assert.equal(q.get('expiresIn'),'3600');return {url:'https://final.test/'+q.get('path').split('/')[1]};}events.push(['get',path]);if(unknownGet)throw new Error('workspace_read_unknown');return remotes.get(path.split('/').at(-1))??missing();};return {save,call,inputs,events,remotes,setFailure:v=>failure=v};}
for(const feature of ['canvas-partial-edit','canvas-inpaint'])test(`${feature}: four raw retention precedes every save; exact protected RGBA and unique lineage/final/save IDs`,async()=>{
 const f=await fixture(feature),t=transport(f);const result=await openai.finalizeProtectedOpenAIEdit({...f,...t,assertCurrent:async()=>{}});canvasBatch.assertCanvasCanonicalBatchResult(result);assert.equal(await canvasBatch.completedCanvasProtectedBatch(f.binding),true);assert.equal(new Set(result.images.map(i=>i.imageId)).size,4);assert.equal(t.inputs.size,4);
 for(let i=0;i<4;i++){const input=t.inputs.get(i),pixels=decode(input.imageUrl).pixels;assert.deepEqual(pixels.slice(0,8),decode(f.original).pixels.slice(0,8));assert.deepEqual(pixels.slice(8),new Array(2).fill([120+i,150+i,180+i,255]).flat());assert.equal(input.sourceJobId,f.receipt.jobId);assert.equal(input.imageAI.candidateIndex,i);assert.equal(input.metadata.providerImageId,f.receipt.images[i].imageId);assert(!JSON.stringify(input.metadata).includes('data:image'));}
});
test('candidate1 save failure retains 0/2/3; actual API reload resumes only incomplete same bytes/core/UUID, zero provider and no reblend',async()=>{
 const f=await fixture(),t=transport(f,{failureIndex:1});await assert.rejects(openai.finalizeProtectedOpenAIEdit({...f,...t,assertCurrent:async()=>{}}),/batch_save_incomplete:1/);assert.equal(t.remotes.size,3);assert.equal(await canvasBatch.completedCanvasProtectedBatch(f.binding),false);const initial=structuredClone(t.inputs.get(1)),beforeEncode=encodes;
 const ts=await import('typescript'),source=await fs.readFile(new URL('../src/lib/cloudflareApi.ts',import.meta.url),'utf8'),ast=ts.createSourceFile('api.ts',source,ts.ScriptTarget.Latest,true);let node;const walk=n=>{if(ts.isMethodDeclaration(n)&&n.name.getText(ast)==='recoverProtectedCanvasBatchComposite')node=n;ts.forEachChild(n,walk);};walk(ast);
 const bindings={loadProtectedImageInput:async()=>({prepared:structuredClone(f.prepared),requestId:f.binding.requestId,clientRecoveryKey:'same-key'}),loadCanvasProtectedBatch:canvasBatch.loadCanvasProtectedBatch,canvasBatchHasAllRaw:canvasBatch.canvasBatchHasAllRaw,createCanvasProtectedBatchLifecycle:canvasBatch.createCanvasProtectedBatchLifecycle,finalizeProtectedOpenAIEdit:openai.finalizeProtectedOpenAIEdit,materializeMaterialPng:material.materializeMaterialPng,protectedImageDigest:contract.protectedImageDigest};
 const recover=new Function(...Object.keys(bindings),ts.transpile(`return async function(brandId,requestId,assertContext,expectedSourceImageUrl,expectedSourceIdentity) ${node.body.getText(ast)}`,{target:ts.ScriptTarget.ES2022}))(...Object.values(bindings));let generationCalls=0;const call=async(...args)=>{if(args[0].includes('image-ai')||args[0].includes('provider-actions')){generationCalls++;throw new Error('generation_forbidden');}return t.call(...args);};t.setFailure(undefined);t.events.length=0;
 const result=await recover.call({origin:'https://api.test',captureRequestContext:async()=>({userId:'alice',assertCurrent:async()=>{},call}),saveWorkspaceArtifact:t.save},'brand',f.binding.requestId,undefined,undefined,f.sourceIdentity);assert.equal(generationCalls,0);assert.equal(encodes,beforeEncode);assert.deepEqual(t.inputs.get(1),initial);assert.deepEqual(t.events.filter(e=>e[0]==='save'),[['save',1]]);canvasBatch.assertCanvasCanonicalBatchResult(result);assert.equal(result.clientRecoveryKey,'same-key');
});
test('uncertain GET cannot save/replay; identity failure in candidate3 validates all before any raw/save',async()=>{
 const f=await fixture();const t=transport(f,{unknownGet:true});await assert.rejects(openai.finalizeProtectedOpenAIEdit({...f,...t,assertCurrent:async()=>{}}),/batch_save_incomplete/);assert.equal(t.inputs.size,0);
 const other=await fixture();other.receipt.images[3].providerModel='foreign';let raw=0,saves=0;await assert.rejects(openai.finalizeProtectedOpenAIEdit({...other,lifecycle:{...other.lifecycle,onCandidate:async()=>{raw++;}},assertCurrent:async()=>{},call:missing,save:async()=>{saves++;}}),/candidate_identity_mismatch/);assert.equal(raw,0);assert.equal(saves,0);
});
test('raw retention failure means no final saves this pass; immutable completed provider receipt remains',async()=>{const f=await fixture();let raw=0,saves=0;const lifecycle={...f.lifecycle,onCandidate:async c=>{raw++;if(c.candidateIndex===2)throw new Error('raw_retention_failed');return f.lifecycle.onCandidate(c);}};await assert.rejects(openai.finalizeProtectedOpenAIEdit({...f,lifecycle,assertCurrent:async()=>{},call:missing,save:async()=>{saves++;}}),/raw_retention_failed/);assert.equal(raw,3);assert.equal(saves,0);assert.deepEqual((await canvasBatch.loadCanvasProtectedBatch(f.binding)).receipt,f.receipt);});
test('saved PNG mismatch and context change abort globally, cannot mark complete or handoff',async()=>{const f=await fixture(),t=transport(f);globalThis.fetch=async()=>new Response(Buffer.from(f.original.split(',')[1],'base64'));await assert.rejects(openai.finalizeProtectedOpenAIEdit({...f,...t,assertCurrent:async()=>{}}),/bytes_mismatch/);assert.equal(await canvasBatch.completedCanvasProtectedBatch(f.binding),false);assert.throws(()=>canvasBatch.assertCanvasCanonicalBatchResult(f.receipt),/proof_required/);});
test('Canvas caller preserves count4 and frozen pending key; generic resume rejects before generation and interrupted placement keeps dedup state',async()=>{const api=await fs.readFile(new URL('../src/lib/cloudflareApi.ts',import.meta.url),'utf8'),page=await fs.readFile(new URL('../src/pages/CanvasEditorPage.tsx',import.meta.url),'utf8');const resume=api.slice(api.indexOf('  async resumeProtectedImageEdit('),api.indexOf('  async getImageUsage('));assert(resume.indexOf('canvas_protected_save_only_recovery_required')<resume.indexOf('invokeDurableImageAction'));assert.equal((page.match(/generationProvider:'openai',idempotencyKey:requestId,canvasProtectedBatchBinding/g)??[]).length,2);assert(!page.includes('placement.placed.forEach(({ value: objectId }) => { if (createdIds.has(objectId)) useCanvasStore.getState().deleteObject(objectId);'));assert(page.includes('if(canvasBatch){assertCanvasCanonicalBatchResult(result)'));const manualSave=page.slice(page.indexOf('const savedRequestIds'),page.indexOf('const savedRequestIds')+1400);if(manualSave)assert(manualSave.includes('acknowledgeImageAction'));});

test('actual durable action incoming requiresProtectedComposite true clears only after four canonical proofs; save failure retains pending identity',async()=>{
 const f=await fixture(),t=transport(f);const globals=Object.fromEntries(['indexedDB','localStorage'].map(k=>[k,Object.getOwnPropertyDescriptor(globalThis,k)]));const {createPendingIndexedDbHarness}=await import('./verify-cloudflare-image-pending-store.test.mjs');Object.defineProperty(globalThis,'indexedDB',{value:createPendingIndexedDbHarness(),writable:true,configurable:true});Object.defineProperty(globalThis,'localStorage',{value:window.localStorage,writable:true,configurable:true});
 try{let providerCalls=0;const result=await image.invokeDurableImageAction({origin:'https://positive.test',userId:'alice',action:'edit-image',body:f.prepared.body,idempotencyKey:f.binding.requestId,assertCurrent:async()=>{},retainUntilAcknowledged:true,call:async(path,init)=>{providerCalls++;assert(path.includes('provider-actions')&&init.method==='POST');return f.receipt;},finalize:receipt=>openai.finalizeProtectedOpenAIEdit({...f,...t,receipt,assertCurrent:async()=>{}})});canvasBatch.assertCanvasCanonicalBatchResult(result);assert.equal(result.requiresProtectedComposite,false);assert(result.clientRecoveryKey);assert.equal(providerCalls,1);
 const failed=await fixture(),failedTransport=transport(failed,{failureIndex:1});Object.defineProperty(globalThis,'localStorage',{value:window.localStorage,writable:true,configurable:true});await assert.rejects(image.invokeDurableImageAction({origin:'https://failed.test',userId:'alice',action:'edit-image',body:failed.prepared.body,idempotencyKey:failed.binding.requestId,assertCurrent:async()=>{},retainUntilAcknowledged:true,call:async()=>failed.receipt,finalize:receipt=>openai.finalizeProtectedOpenAIEdit({...failed,...failedTransport,receipt,assertCurrent:async()=>{}})}),/batch_save_incomplete/);const key=await image.durableImageRecoveryKey('https://failed.test','alice','edit-image',failed.prepared.body);const pending=await vite.ssrLoadModule('/src/lib/cloudflareImagePendingStore.ts');assert.equal((await pending.readPendingIdentity(key)).requestId,failed.binding.requestId);
 }finally{for(const[k,v]of Object.entries(globals)){if(v)Object.defineProperty(globalThis,k,v);else delete globalThis[k];}}
});

test('four-proof ACK gate rejects missing placements, duplicates and unrelated canonical IDs',async()=>{const f=await fixture(),t=transport(f);const result=await openai.finalizeProtectedOpenAIEdit({...f,...t,assertCurrent:async()=>{}});const objects=result.images.map(c=>({metadata:{imageId:c.imageId,parentObjectId:f.binding.parentObjectId,generation:f.binding.generation,parameters:{candidateIndex:c.candidateIndex,imageAICompletion:{requestId:f.binding.requestId}}}}));assert.equal(await canvasBatch.canAcknowledgeCanvasProtectedBatch(f.binding,objects),true);assert.equal(await canvasBatch.canAcknowledgeCanvasProtectedBatch(f.binding,objects.slice(0,3)),false);assert.equal(await canvasBatch.canAcknowledgeCanvasProtectedBatch(f.binding,objects.map((o,i)=>i===1?{metadata:{...o.metadata,generation:9}}:o)),false);assert.equal(await canvasBatch.canAcknowledgeCanvasProtectedBatch(f.binding,[...objects.slice(0,3),objects[0]]),false);assert.equal(await canvasBatch.canAcknowledgeCanvasProtectedBatch(f.binding,objects.map((o,i)=>i===3?{metadata:{...o.metadata,imageId:'wa-foreign'}}:o)),false);});

test('actual Canvas invokeProviderAction caller connects durable preparation/projection and real durable action count4 before inference',async()=>{
 const f=await fixture('canvas-partial-edit',false),t=transport(f),ts=await import('typescript'),source=await fs.readFile(new URL('../src/lib/cloudflareApi.ts',import.meta.url),'utf8'),ast=ts.createSourceFile('api.ts',source,ts.ScriptTarget.Latest,true);let node;const walk=n=>{if(ts.isMethodDeclaration(n)&&n.name.getText(ast)==='invokeProviderAction')node=n;ts.forEachChild(n,walk);};walk(ast);
 const descriptors=Object.fromEntries(['indexedDB','localStorage'].map(k=>[k,Object.getOwnPropertyDescriptor(globalThis,k)])),{createPendingIndexedDbHarness}=await import('./verify-cloudflare-image-pending-store.test.mjs');Object.defineProperty(globalThis,'indexedDB',{value:createPendingIndexedDbHarness(),writable:true,configurable:true});Object.defineProperty(globalThis,'localStorage',{value:window.localStorage,writable:true,configurable:true});let entry,providers=0;
 const bindings={CLOUDFLARE_IMAGE_ACTIONS:new Set(['edit-image']),prepareProtectedCloudflareEdit:edit.prepareProtectedCloudflareEdit,canonicalCloudflareImageBody:body=>body,prepareCloudflareImageInput:async(_action,body)=>({...body,referenceTransforms:body.imageUrls.map((url,index)=>{const {width,height}=decode(url);return{index,sourceWidth:width,sourceHeight:height,width,height,resized:false,renderingTransform:{x:0,y:0,scaleX:1,scaleY:1}};})}),prepareProtectedOpenAIProjection:projectionPreparation.prepareProtectedOpenAIProjection,loadCanvasProtectedBatch:canvasBatch.loadCanvasProtectedBatch,validateNativePrintFinalFrame:(await vite.ssrLoadModule('/src/lib/nativePrintFinalFrame.ts')).validateNativePrintFinalFrame,createCanvasProtectedBatchLifecycle:canvasBatch.createCanvasProtectedBatchLifecycle,persistProtectedImageInput:async(scope,prepared,requestId,key)=>{entry=structuredClone({scope,prepared,requestId,key});assert.deepEqual((await canvasBatch.loadCanvasProtectedBatch(f.binding)).prepared,JSON.parse(JSON.stringify(prepared)));},deleteProtectedImageInput:async()=>assert.fail('no delete before Canvas save'),invokeDurableImageAction:image.invokeDurableImageAction,finalizeProtectedOpenAIEdit:openai.finalizeProtectedOpenAIEdit,finalizeProtectedCloudflareEdit:edit.finalizeProtectedCloudflareEdit};
 const invoke=new Function(...Object.keys(bindings),ts.transpile(`return async function(action,body,options={}) ${node.body.getText(ast)}`,{target:ts.ScriptTarget.ES2022}))(...Object.values(bindings));
 try{const call=async(path,init)=>{if(path.includes('provider-actions')){providers++;assert(entry);assert.equal(entry.prepared.body.count,4);const body=JSON.parse(init.body),map=projectionModule.protectedOpenAIProjectionProof(body.protectedOpenAIProjection);return {...f.receipt,protectedEdit:body.protectedEdit,metadata:{nativePrintFinalFrame:body.nativePrintFinalFrame,protectedOpenAIProjection:map}};}return t.call(path,init);};const result=await invoke.call({origin:'https://canvas-wire.test',captureRequestContext:async()=>({userId:'alice',assertCurrent:async()=>{},call}),saveWorkspaceArtifact:t.save},'edit-image',{brandId:'brand',prompt:'edit',featureType:f.binding.featureType,canvasProjectId:'project',parentObjectId:'parent',generation:2,generationProvider:'openai',imageUrls:[f.original],maskDataUrl:f.mask,count:4},{idempotencyKey:f.binding.requestId,canvasProtectedBatchBinding:f.binding});canvasBatch.assertCanvasCanonicalBatchResult(result);assert.equal(providers,1);assert.equal(entry.prepared.canvasProtectedBatchBinding.requestId,f.binding.requestId);assert.equal(result.requiresProtectedComposite,false);assert(result.clientRecoveryKey);}finally{for(const[k,v]of Object.entries(descriptors)){if(v)Object.defineProperty(globalThis,k,v);else delete globalThis[k];}}
});

test('actual Canvas source/document/auth context fence blocks stale placement; generic resume cannot enter durable generation for batch',async()=>{
 const ts=await import('typescript'),page=await fs.readFile(new URL('../src/pages/CanvasEditorPage.tsx',import.meta.url),'utf8'),ast=ts.createSourceFile('page.tsx',page,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);let context;const walk=n=>{if(ts.isVariableDeclaration(n)&&n.name.getText(ast)==='captureCanvasImageEditContext')context=n.initializer;ts.forEachChild(n,walk);};walk(ast);const auth={brandState:'ready',user:{id:'alice'},currentBrand:{id:'brand'}},store={currentProjectId:'project',objects:[{id:'parent',src:'same-source',metadata:{imageId:'original',generation:1}}]},route={current:'project'},epoch={current:0};const fence=(...v)=>v.join('|');const bindings={useAuthStore:{getState:()=>auth},useCanvasStore:{getState:()=>store},captureAuthBrandFence:fence,isAuthBrandFenceValid:(a,b)=>a===b,assertAuthBrandFence:(a,b)=>{if(a!==b)throw new Error('stale_auth');},imageEditRouteRef:route,imageEditEpochRef:epoch,canvasImageEditRenderCounterRef:{current:0},projectId:'project',canvasObjectProtectedIdentity:canvasBatch.canvasObjectProtectedIdentity};const capture=new Function(...Object.keys(bindings),ts.transpile('return '+context.getText(ast),{target:ts.ScriptTarget.ES2022}))(...Object.values(bindings));const guard=capture('parent');guard();store.currentProjectId='foreign';assert.throws(guard,/target_changed/);store.currentProjectId='project';auth.user.id='bob';assert.throws(guard,/stale_auth/);auth.user.id='alice';store.objects[0].metadata.generation=2;assert.throws(guard,/target_changed/);
 const api=await fs.readFile(new URL('../src/lib/cloudflareApi.ts',import.meta.url),'utf8'),apiAst=ts.createSourceFile('api.ts',api,ts.ScriptTarget.Latest,true);let resume;const find=n=>{if(ts.isMethodDeclaration(n)&&n.name.getText(apiAst)==='resumeProtectedImageEdit')resume=n;ts.forEachChild(n,find);};find(apiAst);let providerCalls=0;const method=new Function('loadProtectedImageInput','invokeDurableImageAction',ts.transpile(`return async function(brandId,requestId,assertContext,expectedSourceImageUrl,expectedSourceIdentity) ${resume.body.getText(apiAst)}`,{target:ts.ScriptTarget.ES2022}))(async()=>({prepared:{canvasProtectedBatchBinding:{version:1}}}),async()=>{providerCalls++;throw new Error('forbidden');});await assert.rejects(method.call({origin:'https://api.test',captureRequestContext:async()=>({userId:'alice',assertCurrent:async()=>{},call:async()=>{providerCalls++;throw new Error('forbidden');}})},'brand',crypto.randomUUID()),/canvas_protected_save_only_recovery_required/);assert.equal(providerCalls,0);
});

test('interrupted raw retention recovery GETs only existing completed request; refreshed URLs preserve original receipt and never POST generation',async()=>{
 const f=await fixture(),fresh=structuredClone(f.receipt);f.receipt.images[2].imageUrl='https://expired.test/raw';let saves=0;await assert.rejects(openai.finalizeProtectedOpenAIEdit({...f,assertCurrent:async()=>{},call:missing,save:async()=>{saves++;}}),/image_decode_failed/);assert.equal(saves,0);assert.equal(await canvasBatch.canvasBatchHasAllRaw(f.binding),false);const originalReceipt=structuredClone((await canvasBatch.loadCanvasProtectedBatch(f.binding)).receipt),t=transport(f);
 const ts=await import('typescript'),source=await fs.readFile(new URL('../src/lib/cloudflareApi.ts',import.meta.url),'utf8'),ast=ts.createSourceFile('api.ts',source,ts.ScriptTarget.Latest,true);let node;const walk=n=>{if(ts.isMethodDeclaration(n)&&n.name.getText(ast)==='recoverProtectedCanvasBatchComposite')node=n;ts.forEachChild(n,walk);};walk(ast);let gets=0,posts=0;const bindings={loadProtectedImageInput:async()=>({prepared:structuredClone(f.prepared),requestId:f.binding.requestId,clientRecoveryKey:'same-key'}),loadCanvasProtectedBatch:canvasBatch.loadCanvasProtectedBatch,canvasBatchHasAllRaw:canvasBatch.canvasBatchHasAllRaw,createCanvasProtectedBatchLifecycle:canvasBatch.createCanvasProtectedBatchLifecycle,finalizeProtectedOpenAIEdit:openai.finalizeProtectedOpenAIEdit,protectedImageDigest:contract.protectedImageDigest};const recover=new Function(...Object.keys(bindings),ts.transpile(`return async function(brandId,requestId,assertContext,expectedSourceImageUrl,expectedSourceIdentity) ${node.body.getText(ast)}`,{target:ts.ScriptTarget.ES2022}))(...Object.values(bindings));const call=async(path,init)=>{if(path.includes('provider-actions')||init?.method==='POST'){posts++;throw new Error('generation_forbidden');}if(path.startsWith('/v1/image-ai/requests/')){gets++;assert(path.endsWith(f.binding.requestId));return fresh;}return t.call(path,init);};const result=await recover.call({origin:'https://raw-recovery.test',captureRequestContext:async()=>({userId:'alice',assertCurrent:async()=>{},call}),saveWorkspaceArtifact:t.save},'brand',f.binding.requestId,undefined,undefined,f.sourceIdentity);assert.equal(posts,0);assert.equal(gets,1);canvasBatch.assertCanvasCanonicalBatchResult(result);assert.deepEqual((await canvasBatch.loadCanvasProtectedBatch(f.binding)).receipt,originalReceipt);
});
test('scope fence failure after a remote save aborts globally; finished batch never passes handoff proof',async()=>{const f=await fixture(),t=transport(f);let changed=false;await assert.rejects(openai.finalizeProtectedOpenAIEdit({...f,assertCurrent:async()=>{if(changed)throw new Error('stale_context');},save:async input=>{const saved=await t.save(input);changed=true;return saved;},call:t.call}),/stale_context/);assert.equal(t.inputs.size,1);assert.equal(await canvasBatch.completedCanvasProtectedBatch(f.binding),false);});

test('local identity preserves all draft state, is stable on repeat and keeps active snapshot on local bookmark reload despite empty project index',async()=>{
 setup();globalThis.localStorage=window.localStorage;const module=await vite.ssrLoadModule('/src/stores/canvasStore.ts'),store=module.useCanvasStore;const objects=[{id:'parent',type:'shape',x:12,y:24,width:50,height:70,fill:'#abc'}],history=[[],objects];store.setState({currentProjectId:null,currentProjectName:'Unsaved',projects:[],objects,selectedIds:['parent'],history,historyIndex:1,zoom:.7,panX:123,panY:-45,gridVisible:false,snapToGrid:false,gridSize:33});const before=store.getState(),id=before.ensureCurrentLocalProjectIdentity('brand'),after=store.getState();assert(id.startsWith('local-'));for(const key of ['objects','selectedIds','history','historyIndex','zoom','panX','panY','gridVisible','snapToGrid','gridSize','currentProjectName'])assert.deepEqual(after[key],before[key]);assert.equal(after.ensureCurrentLocalProjectIdentity('brand'),id);assert.equal(after.projects[0].objects.length,0);after.loadProject(id);for(const key of ['objects','history','historyIndex','zoom','panX','panY','selectedIds'])assert.deepEqual(store.getState()[key],before[key]);store.setState({history:[[]],historyIndex:0,zoom:.9,panX:321});store.getState().loadProject(id);assert.deepEqual(store.getState().history,[objects]);assert.equal(store.getState().zoom,.9);assert.equal(store.getState().panX,321);assert.throws(()=>store.getState().ensureCurrentLocalProjectIdentity('foreign'),/brand_mismatch/);store.getState().clearCanvas();const another=store.getState().ensureCurrentLocalProjectIdentity('brand');assert.notEqual(another,id);
 const persisted=JSON.parse(window.localStorage.getItem('heavy-chain-canvas')).state;assert.equal(persisted.currentProjectId,another);assert.equal(persisted.projects.find(p=>p.id===id).objects.length,0);delete globalThis.localStorage;
});
test('typed generated fallback retains exact scoped source artifact/key/digest; changed object or missing/mutated generated source rejects',async()=>{
 setup();const source=encode(2,2,new Array(4).fill([11,22,33,255]).flat()),mask=encode(2,2,new Array(4).fill([0,0,0,0]).flat());const binding=await canvasBatch.prepareCanvasProtectedBatch({sourceImageUrl:source,maskDataUrl:mask,featureType:'canvas-inpaint',brandId:'brand',scopeId:'alice',canvasProjectId:'local-document',parentObjectId:null,generation:1,inputSignature:'fallback',assertCurrent:()=>{}});assert.equal(binding.source.kind,'retained-generated');const batch=await canvasBatch.loadCanvasProtectedBatch(binding);assert.equal(batch.original.dataUrl,source);const retained=local.findWorkspaceArtifactPersisted('brand',binding.source.sourceArtifactId,'alice');assert(retained.ok&&retained.artifact);assert.equal(retained.artifact.imageUrl,source);assert.equal(binding.source.pngDigest,await contract.protectedImageDigest(source));await assert.rejects(canvasBatch.loadCanvasProtectedBatch({...binding,canvasProjectId:'different-document'}),/batch_identity_mismatch/);const bad={...retained.artifact,imageUrl:encode(2,2,new Array(4).fill([99,22,33,255]).flat())};local.saveWorkspaceArtifactPersisted(bad);await assert.rejects(canvasBatch.loadCanvasProtectedBatch(binding),/retained_source_identity_mismatch/);
 const object={id:'parent',src:'same',metadata:{imageId:'source',generation:1}},identity=canvasBatch.canvasObjectProtectedIdentity(object),objectBinding=await canvasBatch.prepareCanvasProtectedBatch({sourceImageUrl:source,maskDataUrl:mask,featureType:'canvas-partial-edit',brandId:'brand',scopeId:'alice',canvasProjectId:'local-other',parentObjectId:'parent',generation:2,sourceIdentity:identity,verifiedObjectSource:await canvasBatch.resolveCanvasProtectedObjectSource(object,async()=>source,()=>{}),inputSignature:'object',assertCurrent:()=>{}});await canvasBatch.assertCanvasBatchObjectSource(objectBinding,object);await assert.rejects(canvasBatch.assertCanvasBatchObjectSource(objectBinding,{...object,metadata:{...object.metadata,generation:2}}),/object_source_changed/);await assert.rejects(canvasBatch.assertCanvasBatchObjectSource(objectBinding,null),/object_source_changed/);
});
test('owned local route transition exempts only exact from/to identity; local identity cannot ACK and immutable alias requires scoped derived document proof',async()=>{
 const source=await fs.readFile(new URL('../src/pages/CanvasEditorPage.tsx',import.meta.url),'utf8');const handler=source.slice(source.indexOf('  const ensureProtectedCanvasDocumentContext='),source.indexOf('  // Invite modal state'));assert(handler.includes('ensureCurrentLocalProjectIdentity'));assert(handler.includes('transition=new Promise'));assert(handler.includes('await transition'));assert(handler.includes('targetId=>'));assert(!handler.includes('acknowledgeImageAction'));assert(!handler.includes('createProject('));const route=source.slice(source.indexOf("    if (!projectId || projectId === 'new')"),source.indexOf('    const localProject ='));assert(route.includes('owned.from===projectId'));assert(route.includes('owned.to===useCanvasStore.getState().currentProjectId'));assert(route.includes('owned.epoch===imageEditEpochRef.current'));assert(route.includes("if (projectId === 'new' && useCanvasStore.getState().currentProjectId) clearCanvas()"));assert(source.includes('image_recovery_canvas_alias_unproven'));assert(source.includes('canAcknowledgeCanvasProtectedBatch(completion.canvasBatch,readback.snapshot.objects)'));
});

test('actual new-route effect preserves draft only for matching owned identity transition; unrelated new clears normally',async()=>{
 const ts=await import('typescript'),source=await fs.readFile(new URL('../src/pages/CanvasEditorPage.tsx',import.meta.url),'utf8'),ast=ts.createSourceFile('page.tsx',source,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);let body;const walk=n=>{if(ts.isCallExpression(n)&&n.expression.getText(ast)==='useEffect'&&n.arguments[0]&&n.arguments[0].getText(ast).includes("if (!projectId || projectId === 'new')"))body=n.arguments[0].body;ts.forEachChild(n,walk);};walk(ast);const refs={remoteDocumentIdRef:{current:'old'},remoteRevisionRef:{current:1},remoteDocumentOwnerRef:{current:'alice'},canvasRecoveryScopeRef:{current:{}},canvasSourceProjectIdsRef:{current:['old']},confirmedCanvasFingerprintRef:{current:'old'},legacyCanvasCapturedRef:{current:true},ownedCanvasEditIdentityTransitionRef:{current:{id:'token',fromKey:'from-key',from:'new',to:'local-target',userId:'alice',brandId:'brand',epoch:2}},imageEditEpochRef:{current:2}};let clears=0;const bindings={...refs,canvasLocation:{key:'from-key',state:null},heavyWorkspaceReady:true,user:{id:'alice'},currentBrand:{id:'brand'},projectId:'new',useCanvasStore:{getState:()=>({currentProjectId:'local-target'})},setCanvasPersistenceStatus:()=>{},clearCanvas:()=>{clears++;}};const effect=new Function(...Object.keys(bindings),ts.transpile('return ()=>'+body.getText(ast),{target:ts.ScriptTarget.ES2022}))(...Object.values(bindings));effect();assert.equal(clears,0);for(const wrong of [{from:'other'},{fromKey:'other'},{to:'other'},{userId:'bob'},{brandId:'foreign'},{epoch:3}]){refs.ownedCanvasEditIdentityTransitionRef.current={id:'token',fromKey:'from-key',from:'new',to:'local-target',userId:'alice',brandId:'brand',epoch:2,...wrong};effect();}assert.equal(clears,6);refs.ownedCanvasEditIdentityTransitionRef.current=null;effect();assert.equal(clears,7);
});

test('retained-generated actual save-only recovery uses original artifact, rejects changed current display bytes before writes and generates zero candidates',async()=>{
 const f=await fixture('canvas-inpaint',true,true),t=transport(f,{failureIndex:1});await assert.rejects(openai.finalizeProtectedOpenAIEdit({...f,...t,assertCurrent:async()=>{}}),/save_incomplete/);const ts=await import('typescript'),source=await fs.readFile(new URL('../src/lib/cloudflareApi.ts',import.meta.url),'utf8'),ast=ts.createSourceFile('api.ts',source,ts.ScriptTarget.Latest,true);let node;const walk=n=>{if(ts.isMethodDeclaration(n)&&n.name.getText(ast)==='recoverProtectedCanvasBatchComposite')node=n;ts.forEachChild(n,walk);};walk(ast);const bindings={loadProtectedImageInput:async()=>({prepared:structuredClone(f.prepared),requestId:f.binding.requestId,clientRecoveryKey:'same-key'}),loadCanvasProtectedBatch:canvasBatch.loadCanvasProtectedBatch,canvasBatchHasAllRaw:canvasBatch.canvasBatchHasAllRaw,createCanvasProtectedBatchLifecycle:canvasBatch.createCanvasProtectedBatchLifecycle,finalizeProtectedOpenAIEdit:openai.finalizeProtectedOpenAIEdit,protectedImageDigest:contract.protectedImageDigest,materializeMaterialPng:material.materializeMaterialPng};const recover=new Function(...Object.keys(bindings),ts.transpile(`return async function(brandId,requestId,assertContext,expectedSourceImageUrl,expectedSourceIdentity) ${node.body.getText(ast)}`,{target:ts.ScriptTarget.ES2022}))(...Object.values(bindings));let generators=0,writes=0;const subject={origin:'https://generated-recovery.test',captureRequestContext:async()=>({userId:'alice',assertCurrent:async()=>{},call:async(path,init)=>{if(path.includes('image-ai')||path.includes('provider-actions')){generators++;throw new Error('generation_forbidden');}return t.call(path,init);}}),saveWorkspaceArtifact:async input=>{writes++;return t.save(input);}};t.setFailure(undefined);await assert.rejects(recover.call(subject,'brand',f.binding.requestId,undefined,encode(2,2,new Array(4).fill([9,9,9,255]).flat())),/recovery_source_changed/);assert.equal(writes,0);const result=await recover.call(subject,'brand',f.binding.requestId);canvasBatch.assertCanvasCanonicalBatchResult(result);assert.equal(generators,0);assert.equal(writes,1);assert.equal(result.canvasProtectedBatchBinding.source.sourceKey,f.binding.source.sourceKey);assert.equal(result.canvasProtectedBatchBinding.parentObjectId,null);
});

function sourceFenceFixture(){
 setup();const originalA=encode(2,2,new Array(4).fill([1,2,3,255]).flat()),originalB=encode(2,2,new Array(4).fill([41,51,61,255]).flat()),mask=encode(2,2,new Array(4).fill([0,0,0,0]).flat());
 const object={id:'parent',src:'https://fallback.test/source?token=one&variant=original',metadata:{storagePath:'generated-images/A',galleryStoragePath:'generated-images/B',imageId:'A',generation:1,sourceRevision:1,parameters:{sourceStoragePath:'generated-images/source'}}};
 const urls=new Map([['generated-images/A',originalA],['generated-images/B',originalB],[object.src,originalA]]),calls=[];
 const resolve=async locator=>{calls.push(locator);if(!urls.has(locator))throw new Error('source_unavailable');return urls.get(locator);};
 const prepare=verified=>canvasBatch.prepareCanvasProtectedBatch({sourceImageUrl:verified.originalPngDataUrl,verifiedObjectSource:verified,sourceIdentity:verified.objectDescriptor,maskDataUrl:mask,featureType:'canvas-partial-edit',brandId:'brand',scopeId:'alice',canvasProjectId:'project',parentObjectId:'parent',generation:2,inputSignature:'repair',assertCurrent:()=>{}});
 return{object,originalA,originalB,mask,urls,calls,resolve,prepare};
}
test('complete descriptor shares gallery-first ordered candidates and preserves meaningful URLs and all parameter/image aliases including src with storage',async()=>{
 const f=sourceFenceFixture(),parameters=f.object.metadata.parameters;Object.assign(parameters,{galleryStoragePath:'parameter-gallery',storagePath:'parameter-storage',remoteStoragePath:'remote',backendStoragePath:'backend',imageId:'param-image'});f.object.metadata.galleryImageId='gallery-id';f.object.metadata.galleryImageUrl='https://gallery.test/image?size=full';
 assert.deepEqual(canvasBatch.canvasObjectSourceCandidates(f.object),['generated-images/B','generated-images/A','parameter-gallery','parameter-storage','remote','generated-images/source','backend','generated-images/gallery-id','generated-images/param-image',f.object.src,'https://gallery.test/image?size=full']);
 const baseline=canvasBatch.canvasObjectProtectedIdentity(f.object);for(const [target,key,value]of [[f.object,'src','https://fallback.test/source?token=two'],[f.object.metadata,'galleryStoragePath','generated-images/C'],[parameters,'sourceStoragePath','changed'],[parameters,'imageId','other'],[f.object.metadata,'galleryImageId','other'],[f.object.metadata,'imageId','other']]){const old=target[key];target[key]=value;assert.notDeepEqual(canvasBatch.canvasObjectProtectedIdentity(f.object),baseline);target[key]=old;}
 const descriptorAgain=canvasBatch.canvasObjectProtectedIdentity({...f.object,metadata:{...f.object.metadata,sourceRevision:{b:2,a:1}}}),descriptorOrdered=canvasBatch.canvasObjectProtectedIdentity({...f.object,metadata:{...f.object.metadata,sourceRevision:{a:1,b:2}}});assert.deepEqual(descriptorAgain,descriptorOrdered);
});
test('gallery B actual PNG and locator bind despite storage A; preparation retains frozen verified bytes without another source resolution',async()=>{
 const f=sourceFenceFixture(),verified=await canvasBatch.resolveCanvasProtectedObjectSource(f.object,f.resolve,()=>{});assert.equal(verified.selectedSource,'generated-images/B');assert.equal(verified.originalPngDataUrl,f.originalB);assert.deepEqual(f.calls,['generated-images/B']);
 const binding=await f.prepare(verified),batch=await canvasBatch.loadCanvasProtectedBatch(binding);assert.equal(binding.source.identityDigest,verified.objectDescriptorDigest);assert.equal(batch.original.dataUrl,f.originalB);assert.equal(batch.original.digest,verified.originalPngDigest);assert.equal(batch.sourceProof.selectedSource,'generated-images/B');assert.equal(batch.sourceProof.version,'canvas-object-source-v1');assert(!('originalPngDataUrl'in batch.sourceProof));assert.deepEqual(f.calls,['generated-images/B']);
 const storedBefore=window.localStorage.getItem('heavy-chain-workspace-artifacts');await assert.rejects(f.prepare({...verified,originalPngDataUrl:f.originalA}),/verified_object_source_required/);assert.equal(window.localStorage.getItem('heavy-chain-workspace-artifacts'),storedBefore);
});
test('captured gallery change during resolution and context/scope change during PNG materialization stop before local persistence',async()=>{
 for(const mutation of ['gallery','scope','pixels']){const f=sourceFenceFixture();let active=true;const ImageBefore=globalThis.Image;const assertCurrent=()=>{if(!active)throw new Error('stale_scope');};if(mutation!=='gallery')globalThis.Image=class extends ImageBefore{set src(url){if(url===f.originalB){if(mutation==='scope')active=false;else f.object.src='changed-fallback';}super.src=url;}};
 try{await assert.rejects(canvasBatch.resolveCanvasProtectedObjectSource(f.object,async source=>{const result=await f.resolve(source);if(mutation==='gallery')f.object.metadata.galleryStoragePath='generated-images/C';return result;},assertCurrent),/object_source_changed|stale_scope/);assert.equal(window.localStorage.getItem('heavy-chain-workspace-artifacts'),null);}finally{globalThis.Image=ImageBefore;}}
});
test('valid initial fallback stays allowed; bound pinned failure cannot fallback to storage and same locator changed pixels rejects',async()=>{
 const f=sourceFenceFixture();f.urls.delete('generated-images/B');const fallback=await canvasBatch.resolveCanvasProtectedObjectSource(f.object,f.resolve,()=>{});assert.equal(fallback.selectedSource,'generated-images/A');assert.equal(fallback.originalPngDataUrl,f.originalA);assert.deepEqual(f.calls,['generated-images/B','generated-images/A']);
 f.urls.set('generated-images/B',f.originalB);f.calls.length=0;const verified=await canvasBatch.resolveCanvasProtectedObjectSource(f.object,f.resolve,()=>{}),binding=await f.prepare(verified);f.urls.delete('generated-images/B');f.calls.length=0;await assert.rejects(canvasBatch.verifyCanvasPinnedObjectSource(binding,f.object,f.resolve,()=>{}),/source_unavailable/);assert.deepEqual(f.calls,['generated-images/B']);f.urls.set('generated-images/B',f.originalA);f.calls.length=0;await assert.rejects(canvasBatch.verifyCanvasPinnedObjectSource(binding,f.object,f.resolve,()=>{}),/object_source_proof_mismatch/);assert.deepEqual(f.calls,['generated-images/B']);
});
test('object proof rejects legacy batch, alias changes, and src changes even with storage; original retained source remains intact',async()=>{
 const f=sourceFenceFixture(),binding=await f.prepare(await canvasBatch.resolveCanvasProtectedObjectSource(f.object,f.resolve,()=>{}));for(const mutate of [()=>f.object.src='changed',()=>f.object.metadata.parameters.sourceStoragePath='changed',()=>f.object.metadata.imageId='changed']){const before=structuredClone(f.object);mutate();await assert.rejects(canvasBatch.assertCanvasBatchObjectSource(binding,f.object),/object_source_changed/);Object.assign(f.object,before);}const batch=await canvasBatch.loadCanvasProtectedBatch(binding);assert.equal(batch.original.dataUrl,f.originalB);const artifact=local.findWorkspaceArtifactPersisted('brand',binding.batchStateArtifactId,'alice').artifact;delete artifact.metadata.canvasProtectedBatch.sourceProof;local.saveWorkspaceArtifactPersisted(artifact);await assert.rejects(canvasBatch.loadCanvasProtectedBatch(binding),/object_source_proof_required/);
});
async function pageFunction(name,bindings){const ts=await import('typescript'),source=await fs.readFile(new URL('../src/pages/CanvasEditorPage.tsx',import.meta.url),'utf8'),ast=ts.createSourceFile('page.tsx',source,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);let node;const walk=n=>{if(ts.isVariableDeclaration(n)&&n.name.getText(ast)===name)node=n.initializer;ts.forEachChild(n,walk);};walk(ast);assert(node,name);return new Function(...Object.keys(bindings),ts.transpile('return '+node.getText(ast),{target:ts.ScriptTarget.ES2022}))(...Object.values(bindings));}
test('actual partial caller sends verified gallery PNG; gallery mutation during resolution or preparation causes zero dispatch and no new local batch',async()=>{
 for(const phase of ['valid','resolution','preparation']){const f=sourceFenceFixture(),captured=JSON.stringify(canvasBatch.canvasObjectProtectedIdentity(f.object)),assertContext=()=>{if(JSON.stringify(canvasBatch.canvasObjectProtectedIdentity(f.object))!==captured)throw new Error('canvas_image_edit_target_changed');};let providers=0;const ImageBefore=globalThis.Image;if(phase==='preparation')globalThis.Image=class extends ImageBefore{set src(url){if(url===f.mask)f.object.src='changed-during-mask';super.src=url;}};
 const previewSource=await canvasBatch.resolveCanvasProtectedObjectSource(f.object,f.resolve,assertContext);const previewBindings={canvasImagePreviewRef:{current:{objectId:'parent',kind:'partial',source:previewSource,assertCurrent:assertContext}},assertCanvasPreviewSourceMatches:await pageFunction('assertCanvasPreviewSourceMatches',{})};
 const bindings={...previewBindings,partialEditingImage:'display-unused',currentBrand:{id:'brand'},validateLegalSafetyInput:()=>({blocked:false}),objects:[f.object],partialEditingObjectId:'parent',ensureProtectedCanvasDocumentContext:async()=>assertContext,buildLightchainEditMetadata:()=>({}),user:{id:'alice'},cloudflareDataPlane:{},partialEditAttemptRef:{current:{}},crypto,resolveCanvasProtectedObjectSource:canvasBatch.resolveCanvasProtectedObjectSource,resolveCanvasSourceLocator:async locator=>{const png=await f.resolve(locator);if(phase==='resolution')f.object.metadata.galleryStoragePath='generated-images/C';return png;},useCanvasStore:{getState:()=>({currentProjectId:'project',objects:[f.object]})},resolveGeneratedImageUrl:async()=>assert.fail('object must use verified source'),prepareCanvasProtectedBatch:canvasBatch.prepareCanvasProtectedBatch,editImageWithPrompt:async(png,_prompt,_brand,options)=>{providers++;assert.equal(png,f.originalB);const batch=await canvasBatch.loadCanvasProtectedBatch(options.canvasProtectedBatchBinding);assert.equal(batch.original.dataUrl,f.originalB);assert.equal(batch.sourceProof.selectedSource,'generated-images/B');throw new Error('dispatch_reached');},rightsConfirmed:true};
 try{const handler=await pageFunction('handlePartialEditSubmit',bindings);await assert.rejects(handler({prompt:'edit',maskDataUrl:f.mask}),phase==='valid'?/dispatch_reached/:/target_changed/);assert.equal(providers,phase==='valid'?1:0);if(phase!=='valid')assert.equal(window.localStorage.getItem('heavy-chain-workspace-artifacts'),null);}finally{globalThis.Image=ImageBefore;}}
});
test('actual page recovery pins original locator and PNG before save-only API; changed pixels/unavailable locator reject with zero recovery/provider calls',async()=>{
 for(const phase of ['valid','changed-pixels','unavailable','changed-src']){const f=sourceFenceFixture(),binding=await f.prepare(await canvasBatch.resolveCanvasProtectedObjectSource(f.object,f.resolve,()=>{}));if(phase==='changed-pixels')f.urls.set('generated-images/B',f.originalA);if(phase==='unavailable')f.urls.delete('generated-images/B');if(phase==='changed-src')f.object.src='new-src';f.calls.length=0;let recoveries=0;const assertContext=()=>{};const bindings={cloudflareDataPlane:{recoverProtectedCanvasBatchComposite:async(_brand,_request,_assert,png,descriptor)=>{recoveries++;assert.equal(png,f.originalB);assert.deepEqual(descriptor,canvasBatch.canvasObjectProtectedIdentity(f.object));throw new Error('save_only_reached');}},useCanvasStore:{getState:()=>({currentProjectId:'project',objects:[f.object]})},user:{id:'alice'},canvasObjectProtectedIdentity:canvasBatch.canvasObjectProtectedIdentity,captureCanvasImageEditContext:()=>assertContext,loadCanvasProtectedBatchForRequest:canvasBatch.loadCanvasProtectedBatchForRequest,loadCanvasProtectedBatch:canvasBatch.loadCanvasProtectedBatch,verifyCanvasObjectBatchSource:b=>canvasBatch.verifyCanvasPinnedObjectSource(b,f.object,f.resolve,assertContext)};
 const recover=await pageFunction('recoverCanvasImageEdit',bindings);await assert.rejects(recover({brandId:'brand',requestId:binding.requestId,canvasProjectId:'project',parentObjectId:'parent',featureType:'canvas-partial-edit'}),phase==='valid'?/save_only_reached/:/object_source_proof_mismatch|source_unavailable|object_source_changed/);assert.equal(recoveries,phase==='valid'?1:0);assert(!f.calls.includes('generated-images/A'));assert.equal((await canvasBatch.loadCanvasProtectedBatch(binding)).original.dataUrl,f.originalB);}
});
test('actual context capture rejects gallery, parameter image aliases and src mutation while storage path stays unchanged',async()=>{
 const f=sourceFenceFixture(),auth={brandState:'ready',user:{id:'alice'},currentBrand:{id:'brand'}},store={currentProjectId:'project',objects:[f.object]},fence=(...v)=>v.join('|');const capture=await pageFunction('captureCanvasImageEditContext',{useAuthStore:{getState:()=>auth},useCanvasStore:{getState:()=>store},captureAuthBrandFence:fence,isAuthBrandFenceValid:(a,b)=>a===b,assertAuthBrandFence:(a,b)=>{if(a!==b)throw new Error('stale_auth');},imageEditRouteRef:{current:'project'},imageEditEpochRef:{current:0},canvasImageEditRenderCounterRef:{current:0},projectId:'project',canvasObjectProtectedIdentity:canvasBatch.canvasObjectProtectedIdentity});
 for(const change of [o=>o.metadata.galleryStoragePath='generated-images/C',o=>o.metadata.parameters.remoteStoragePath='other',o=>o.metadata.parameters.imageId='other',o=>o.metadata.galleryImageId='other',o=>o.src='different-fallback']){const before=structuredClone(f.object),guard=capture('parent');guard();change(f.object);assert.throws(guard,/target_changed/);Object.assign(f.object,before);}
});
test('bound selected-locator proof cannot be substituted locally while the immutable binding stays unchanged',async()=>{
 const f=sourceFenceFixture(),binding=await f.prepare(await canvasBatch.resolveCanvasProtectedObjectSource(f.object,f.resolve,()=>{}));const artifact=local.findWorkspaceArtifactPersisted('brand',binding.batchStateArtifactId,'alice').artifact;artifact.metadata.canvasProtectedBatch.sourceProof.selectedSource='generated-images/A';local.saveWorkspaceArtifactPersisted(artifact);await assert.rejects(canvasBatch.loadCanvasProtectedBatch(binding),/object_source_proof_mismatch/);
});
test('actual partial placement blocks same pinned source changed PNG after completed result without another provider call',async()=>{
 const f=sourceFenceFixture(),results=await vite.ssrLoadModule('/src/lib/canvasImageEditResults.ts');let providers=0,placements=0;const assertContext=()=>{};
 const previewSource=await canvasBatch.resolveCanvasProtectedObjectSource(f.object,f.resolve,assertContext);const previewBindings={canvasImagePreviewRef:{current:{objectId:'parent',kind:'partial',source:previewSource,assertCurrent:assertContext}},assertCanvasPreviewSourceMatches:await pageFunction('assertCanvasPreviewSourceMatches',{})};
 const bindings={...previewBindings,partialEditingImage:'unused',currentBrand:{id:'brand'},validateLegalSafetyInput:()=>({blocked:false}),objects:[f.object],partialEditingObjectId:'parent',ensureProtectedCanvasDocumentContext:async()=>assertContext,buildLightchainEditMetadata:()=>({}),user:{id:'alice'},cloudflareDataPlane:{},partialEditAttemptRef:{current:{}},crypto,resolveCanvasProtectedObjectSource:canvasBatch.resolveCanvasProtectedObjectSource,resolveCanvasSourceLocator:f.resolve,useCanvasStore:{getState:()=>({currentProjectId:'project',objects:[f.object]})},resolveGeneratedImageUrl:async()=>assert.fail('no mutable URL preparation'),prepareCanvasProtectedBatch:canvasBatch.prepareCanvasProtectedBatch,editImageWithPrompt:async(_png,_prompt,_brand,options)=>{providers++;f.urls.set('generated-images/B',f.originalA);return{success:true,requiresProtectedComposite:false,requestedCandidateCount:4,persistedCandidateCount:4,persistenceStatus:'completed',canvasProtectedBatchBinding:options.canvasProtectedBatchBinding,images:Array.from({length:4},(_,i)=>({candidateIndex:i,imageId:`wa-canonical-${i}`,imageUrl:f.originalB,protectedRegionComposited:true,batchId:'batch',jobId:`wa-canonical-${i}`,persistenceStatus:'completed'}))};},rightsConfirmed:true,assertCanvasCanonicalBatchResult:canvasBatch.assertCanvasCanonicalBatchResult,normalizeCanvasImageEditCandidates:r=>r.images,loadCanvasImage:async()=>({}),settleCanvasImageEditCandidatesSequentially:results.settleCanvasImageEditCandidatesSequentially,verifyCanvasObjectBatchSource:b=>canvasBatch.verifyCanvasPinnedObjectSource(b,f.object,f.resolve,assertContext),findRecoveredCanvasCandidate:()=>null,addImageToCanvas:async()=>{placements++;return'id';}};
 const handler=await pageFunction('handlePartialEditSubmit',bindings);await assert.rejects(handler({prompt:'edit',maskDataUrl:f.mask}),/placement_incomplete/);assert.equal(providers,1);assert.equal(placements,0);assert.equal((await canvasBatch.loadCanvasProtectedBatchForRequest('brand','alice',bindings.partialEditAttemptRef.current.idempotencyKey)).original.dataUrl,f.originalB);
});

for(const phase of ['media','refresh-write','preflight-read'])test(`verified saved0 ${phase} failure is candidate-local; pending1 saves, durable pending stays, next save-only resume has zero provider/saved POST replay`,async()=>{
 const f=await fixture(),t=transport(f,{failureIndex:1});await assert.rejects(openai.finalizeProtectedOpenAIEdit({...f,...t,assertCurrent:async()=>{}}),/batch_save_incomplete:1/);t.setFailure(undefined);t.events.length=0;let media0=0,refresh0=0,generators=0;
 const candidate0=local.findWorkspaceArtifactPersisted('brand',`canvas-protected-candidate-${f.binding.requestId}-0`,'alice').artifact,state0Before=structuredClone(candidate0.metadata.canvasProtectedCandidate),pendingCore=structuredClone(t.inputs.get(1));const beforeEncode=encodes;
 const saved0Id='wa-'+await contract.protectedImageSaveRequestId(f.binding.requestId,0),baseSet=window.localStorage.setItem;
 const lifecycle={...f.lifecycle,getVerifiedSavedCandidate:async c=>{if(phase==='preflight-read'&&c.candidateIndex===0)throw new Error('local_candidate_read_unavailable');return f.lifecycle.getVerifiedSavedCandidate(c);},refreshVerifiedSavedCandidate:async(c,url)=>{if(c.candidateIndex===0){refresh0++;if(phase==='refresh-write'){window.localStorage.setItem=()=>{throw new Error('simulated_refresh_write_failed');};try{return await f.lifecycle.refreshVerifiedSavedCandidate(c,url);}finally{window.localStorage.setItem=baseSet;}}}return f.lifecycle.refreshVerifiedSavedCandidate(c,url);}};
 const call=async(path,init)=>{if(path.includes('provider-actions')||path.includes('image-ai')){generators++;throw new Error('provider_generation_forbidden');}if(path.startsWith('/v1/media/read?')&&new URL('https://local.test'+path).searchParams.get('path')===`generated-images/${saved0Id}`){media0++;if(phase==='media')throw new Error('media_read_unavailable');}return t.call(path,init);};
 await assert.rejects(openai.finalizeProtectedOpenAIEdit({...f,...t,lifecycle,call,assertCurrent:async()=>{}}),/^Error: canvas_protected_batch_save_incomplete:0$/);assert.equal(generators,0);assert.deepEqual(t.events.filter(e=>e[0]==='save'),[['save',1]]);assert.deepEqual(t.inputs.get(1),pendingCore);assert.equal(encodes,beforeEncode);assert.equal(media0,phase==='preflight-read'?0:1);assert.equal(refresh0,phase==='refresh-write'?1:0);
 const state0=local.findWorkspaceArtifactPersisted('brand',`canvas-protected-candidate-${f.binding.requestId}-0`,'alice').artifact.metadata.canvasProtectedCandidate;assert.deepEqual(state0,state0Before);assert.equal(local.findWorkspaceArtifactPersisted('brand',`canvas-protected-candidate-${f.binding.requestId}-1`,'alice').artifact.metadata.canvasProtectedCandidate.stage,'saved');assert.throws(()=>canvasBatch.assertCanvasCanonicalBatchResult(f.receipt),/proof_required/);assert.equal(await canvasBatch.canAcknowledgeCanvasProtectedBatch(f.binding,[]),false);
 // A durable action must retain its request on this incomplete pass even though peers finish.
 const globals=Object.fromEntries(['indexedDB','localStorage'].map(k=>[k,Object.getOwnPropertyDescriptor(globalThis,k)])),{createPendingIndexedDbHarness}=await import('./verify-cloudflare-image-pending-store.test.mjs');Object.defineProperty(globalThis,'indexedDB',{value:createPendingIndexedDbHarness(),writable:true,configurable:true});Object.defineProperty(globalThis,'localStorage',{value:window.localStorage,writable:true,configurable:true});
 try{await assert.rejects(image.invokeDurableImageAction({origin:'https://recovery-local.test',userId:'alice',action:'edit-image',body:f.prepared.body,idempotencyKey:f.binding.requestId,retainUntilAcknowledged:true,assertCurrent:async()=>{},call:async()=>f.receipt,finalize:receipt=>openai.finalizeProtectedOpenAIEdit({...f,...t,receipt,lifecycle,call,assertCurrent:async()=>{}})}),/batch_save_incomplete:0/);const key=await image.durableImageRecoveryKey('https://recovery-local.test','alice','edit-image',f.prepared.body),pending=await vite.ssrLoadModule('/src/lib/cloudflareImagePendingStore.ts');assert.equal((await pending.readPendingIdentity(key)).requestId,f.binding.requestId);}finally{for(const[k,v]of Object.entries(globals)){if(v)Object.defineProperty(globalThis,k,v);else delete globalThis[k];}}
 t.events.length=0;const ts=await import('typescript'),source=await fs.readFile(new URL('../src/lib/cloudflareApi.ts',import.meta.url),'utf8'),ast=ts.createSourceFile('api.ts',source,ts.ScriptTarget.Latest,true);let node;const walk=n=>{if(ts.isMethodDeclaration(n)&&n.name.getText(ast)==='recoverProtectedCanvasBatchComposite')node=n;ts.forEachChild(n,walk);};walk(ast);const bindings={loadProtectedImageInput:async()=>({prepared:structuredClone(f.prepared),requestId:f.binding.requestId,clientRecoveryKey:'same-key'}),loadCanvasProtectedBatch:canvasBatch.loadCanvasProtectedBatch,canvasBatchHasAllRaw:canvasBatch.canvasBatchHasAllRaw,createCanvasProtectedBatchLifecycle:canvasBatch.createCanvasProtectedBatchLifecycle,finalizeProtectedOpenAIEdit:openai.finalizeProtectedOpenAIEdit,protectedImageDigest:contract.protectedImageDigest};const recover=new Function(...Object.keys(bindings),ts.transpile(`return async function(brandId,requestId,assertContext,expectedSourceImageUrl,expectedSourceIdentity) ${node.body.getText(ast)}`,{target:ts.ScriptTarget.ES2022}))(...Object.values(bindings));const result=await recover.call({origin:'https://save-only-recovery.test',captureRequestContext:async()=>({userId:'alice',assertCurrent:async()=>{},call:async(path,init)=>{if(path.includes('image-ai')||path.includes('provider-actions')){generators++;throw new Error('provider_generation_forbidden');}return t.call(path,init);}}),saveWorkspaceArtifact:t.save},'brand',f.binding.requestId,undefined,undefined,f.sourceIdentity);canvasBatch.assertCanvasCanonicalBatchResult(result);assert.equal(generators,0);assert.deepEqual(t.events.filter(e=>e[0]==='save'),[]);assert.equal(encodes,beforeEncode);assert.equal(result.provider,'openai');assert.equal(result.providerModel,f.receipt.resolvedProvider.model);assert.equal(result.modelUsed,f.receipt.resolvedProvider.model);
});
test('early saved0 and late saved3 retained provider/model/modelUsed mutations globally reject before every media/save and remain unnormalized',async()=>{
 const f=await fixture(),t=transport(f,{failureIndex:1});await assert.rejects(openai.finalizeProtectedOpenAIEdit({...f,...t,assertCurrent:async()=>{}}),/batch_save_incomplete:1/);t.setFailure(undefined);let media=0,saves=0;const verifiedOrder=[];
 for(const index of [0,3])for(const field of ['provider','providerModel','modelUsed']){const artifact=local.findWorkspaceArtifactPersisted('brand',`canvas-protected-candidate-${f.binding.requestId}-${index}`,'alice').artifact,original=structuredClone(artifact);artifact.metadata.canvasProtectedCandidate.savedImage[field]='foreign-authority';local.saveWorkspaceArtifactPersisted(artifact);media=saves=0;verifiedOrder.length=0;const lifecycle={...f.lifecycle,getVerifiedSavedCandidate:async c=>{verifiedOrder.push(c.candidateIndex);assert.equal(await canvasBatch.canvasBatchHasAllRaw(f.binding),true);return f.lifecycle.getVerifiedSavedCandidate(c);}};
 await assert.rejects(openai.finalizeProtectedOpenAIEdit({...f,lifecycle,assertCurrent:async()=>{},call:async(...args)=>{media++;return t.call(...args);},save:async input=>{saves++;return t.save(input);}}),/saved_identity_mismatch/);assert.equal(media,0);assert.equal(saves,0);assert.deepEqual(verifiedOrder,index===0?[0]:[0,1,2,3]);assert.equal(local.findWorkspaceArtifactPersisted('brand',artifact.id,'alice').artifact.metadata.canvasProtectedCandidate.savedImage[field],'foreign-authority');local.saveWorkspaceArtifactPersisted(original);}
 const result=await openai.finalizeProtectedOpenAIEdit({...f,...t,assertCurrent:async()=>{}});for(let i=0;i<4;i++){const stored=local.findWorkspaceArtifactPersisted('brand',`canvas-protected-candidate-${f.binding.requestId}-${i}`,'alice').artifact.metadata.canvasProtectedCandidate.savedImage;for(const value of [stored,result.images[i],result]){assert.equal(value.provider,'openai');assert.equal(value.providerModel,f.receipt.resolvedProvider.model);assert.equal(value.modelUsed,f.receipt.resolvedProvider.model);}}
});
test('verified-saved media auth denial remains globally fatal and cannot continue pending1 writes',async()=>{
 const f=await fixture(),t=transport(f,{failureIndex:1});await assert.rejects(openai.finalizeProtectedOpenAIEdit({...f,...t,assertCurrent:async()=>{}}),/batch_save_incomplete:1/);t.setFailure(undefined);
 for(const message of ['auth_expired','cloudflare_api_401_session_expired','cloudflare_api_403_scope_forbidden']){let media=0,saves=0;await assert.rejects(openai.finalizeProtectedOpenAIEdit({...f,assertCurrent:async()=>{},call:async path=>{media++;assert(path.startsWith('/v1/media/read?'));throw new Error(message);},save:async()=>{saves++;throw new Error('must_not_save');}}),new RegExp(message));assert.equal(media,1);assert.equal(saves,0);}
});

async function previewHarness(f){
 const state={currentProjectId:'project',objects:[f.object],selectedIds:['parent']},auth={brandState:'ready',user:{id:'alice'},currentBrand:{id:'brand'}},route={current:'project'},epoch={current:0},ui={},errors=[];
 const refs={canvasImagePreviewRef:{current:null},canvasImagePreviewAttemptRef:{current:0},canvasImagePreviewMountedRef:{current:true}},setters=Object.fromEntries(['ShowPartialEditModal','PartialEditingImage','PartialEditingObjectId','ShowEditModal','EditingImage','EditingObjectId'].map(name=>['set'+name,value=>{ui[name]=value;}]));
 const fence=(...v)=>v.join('|'),capture=await pageFunction('captureCanvasImageEditContext',{useAuthStore:{getState:()=>auth},useCanvasStore:{getState:()=>state},captureAuthBrandFence:fence,isAuthBrandFenceValid:(a,b)=>a===b,assertAuthBrandFence:(a,b)=>{if(a!==b)throw new Error('stale_auth');},imageEditRouteRef:route,imageEditEpochRef:epoch,canvasImageEditRenderCounterRef:{current:0},projectId:'project',canvasObjectProtectedIdentity:canvasBatch.canvasObjectProtectedIdentity});
 const invalidate=await pageFunction('invalidateCanvasImagePreview',{...refs,...setters});let resolver=f.resolve;
 const open=await pageFunction('openCanvasImageEditPreview',{...refs,...setters,invalidateCanvasImagePreview:invalidate,useCanvasStore:{getState:()=>state},captureCanvasImageEditContext:capture,resolveCanvasProtectedObjectSource:canvasBatch.resolveCanvasProtectedObjectSource,resolveCanvasSourceLocator:locator=>resolver(locator),partialEditAttemptRef:{current:{}},inpaintAttemptRef:{current:{}},toast:{error:e=>errors.push(e)}});
 return{state,auth,route,epoch,refs,ui,errors,open,invalidate,setResolver:v=>resolver=v};
}
test('actual page preview materializes local lease to stable original native-size PNG, survives lease replacement without mutating source authority',async()=>{
 const f=sourceFenceFixture();f.object.src='local-canvas-asset://indexeddb-revision';f.object.metadata={generation:1};const before=structuredClone(f.object),h=await previewHarness(f),ImageBefore=globalThis.Image;let lease=0,currentLease,revoked=[];
 globalThis.Image=class extends ImageBefore{set src(url){if(url.startsWith('blob:')){if(revoked.includes(url))return queueMicrotask(()=>this.onerror());super.src=f.originalB;}else super.src=url;}};
 h.setResolver(async locator=>{assert.equal(locator,f.object.src);if(currentLease)revoked.push(currentLease);currentLease='blob:local-'+(++lease);return currentLease;});
 try{await h.open('parent','partial');assert.equal(h.ui.ShowPartialEditModal,true);assert.equal(h.ui.PartialEditingImage,f.originalB);assert.equal(h.refs.canvasImagePreviewRef.current.source.width,2);assert.equal(h.refs.canvasImagePreviewRef.current.source.height,2);const snapshot=h.refs.canvasImagePreviewRef.current;await h.open('parent','edit');assert.deepEqual(revoked,['blob:local-1']);assert.equal(h.ui.EditingImage,f.originalB);assert.equal(snapshot.source.originalPngDataUrl,f.originalB);assert.deepEqual(f.object,before);assert.equal(h.epoch.current,0);h.invalidate();assert.equal(h.refs.canvasImagePreviewRef.current,null);assert.equal(h.epoch.current,0);}finally{globalThis.Image=ImageBefore;}
});
test('actual page preview preserves gallery-first PNG and stale selection/close/superseding-open/route/auth/unmount cannot open a modal',async()=>{
 for(const phase of ['valid','selection','close','supersede','route','auth','unmount']){const f=sourceFenceFixture(),h=await previewHarness(f),before=structuredClone(f.object);let release,started;const ready=new Promise(r=>started=r),pause=new Promise(r=>release=r);h.setResolver(async locator=>{started();await pause;return f.resolve(locator);});const pending=h.open('parent','partial');await ready;if(phase==='selection')h.state.selectedIds=['other'];if(phase==='close')h.invalidate();if(phase==='supersede'){h.setResolver(f.resolve);await h.open('parent','edit');}if(phase==='route')h.route.current='other';if(phase==='auth')h.auth.user={id:'bob'};if(phase==='unmount')h.refs.canvasImagePreviewMountedRef.current=false;release();await pending;
 assert.equal(h.ui.ShowPartialEditModal,phase==='valid');if(phase==='valid'){assert.equal(h.ui.PartialEditingImage,f.originalB);assert.equal(h.refs.canvasImagePreviewRef.current.source.selectedSource,'generated-images/B');}if(phase==='supersede'){assert.equal(h.ui.ShowEditModal,true);assert.equal(h.refs.canvasImagePreviewRef.current.kind,'edit');}else if(phase!=='valid')assert.equal(h.refs.canvasImagePreviewRef.current,null);assert.deepEqual(f.object,before);assert.equal(window.localStorage.getItem('heavy-chain-workspace-artifacts'),null);}
});
test('preview comparison rejects changed locator/digest/PNG/native geometry and partial submit source change blocks before identity transition/preparation/provider',async()=>{
 const f=sourceFenceFixture(),h=await previewHarness(f);await h.open('parent','partial');const snapshot=h.refs.canvasImagePreviewRef.current,match=await pageFunction('assertCanvasPreviewSourceMatches',{});match(snapshot.source,structuredClone(snapshot.source));for(const changes of [{selectedSource:'generated-images/A'},{originalPngDigest:'f'.repeat(64)},{originalPngDataUrl:f.originalA},{width:3},{height:3},{objectDescriptorDigest:'f'.repeat(64)}])assert.throws(()=>match(snapshot.source,{...snapshot.source,...changes}),/preview_source_changed/);
 let transitions=0,preparations=0,providers=0;f.object.src='changed-before-submit';const bindings={partialEditingImage:snapshot.source.originalPngDataUrl,partialEditingObjectId:'parent',canvasImagePreviewRef:h.refs.canvasImagePreviewRef,assertCanvasPreviewSourceMatches:match,currentBrand:{id:'brand'},validateLegalSafetyInput:()=>({blocked:false}),objects:[f.object],ensureProtectedCanvasDocumentContext:async()=>{transitions++;return()=>{};},prepareCanvasProtectedBatch:async()=>{preparations++;},editImageWithPrompt:async()=>{providers++;}};const submit=await pageFunction('handlePartialEditSubmit',bindings);await assert.rejects(submit({prompt:'edit',maskDataUrl:f.mask}),/target_changed/);assert.equal(transitions,0);assert.equal(preparations,0);assert.equal(providers,0);
});
test('actual partial submit detects same-locator changed PNG after preview and allows owned preview closure without cancelling protected context',async()=>{
 for(const changed of [true,false]){const f=sourceFenceFixture(),h=await previewHarness(f);await h.open('parent','partial');const snapshot=h.refs.canvasImagePreviewRef.current;let preparations=0,providers=0;const beforeEpoch=h.epoch.current;if(changed)f.urls.set('generated-images/B',f.originalA);
 const bindings={partialEditingImage:snapshot.source.originalPngDataUrl,partialEditingObjectId:'parent',canvasImagePreviewRef:h.refs.canvasImagePreviewRef,assertCanvasPreviewSourceMatches:await pageFunction('assertCanvasPreviewSourceMatches',{}),currentBrand:{id:'brand'},user:{id:'alice'},cloudflareDataPlane:{},validateLegalSafetyInput:()=>({blocked:false}),objects:[f.object],ensureProtectedCanvasDocumentContext:async()=>{h.invalidate();return()=>{};},buildLightchainEditMetadata:()=>({}),partialEditAttemptRef:{current:{}},crypto,resolveCanvasProtectedObjectSource:canvasBatch.resolveCanvasProtectedObjectSource,resolveCanvasSourceLocator:f.resolve,useCanvasStore:{getState:()=>h.state},prepareCanvasProtectedBatch:async input=>{preparations++;assert.equal(input.sourceImageUrl,f.originalB);return canvasBatch.prepareCanvasProtectedBatch(input);},editImageWithPrompt:async()=>{providers++;throw new Error('dispatch_reached');},rightsConfirmed:true};const submit=await pageFunction('handlePartialEditSubmit',bindings);await assert.rejects(submit({prompt:'edit',maskDataUrl:f.mask}),changed?/preview_source_changed/:/dispatch_reached/);assert.equal(preparations,changed?0:1);assert.equal(providers,changed?0:1);assert.equal(h.epoch.current,beforeEpoch);}
});


test('canonical OpenAI Canvas grouping: new and verified-saved recovery share authoritative provider batch with four independent saved IDs',async()=>{
 const f=await fixture(),t=transport(f),results=await vite.ssrLoadModule('/src/lib/canvasImageEditResults.ts');
 assert.equal(f.receipt.batchId,undefined);assert.equal(f.receipt.maskTreatment,undefined);
 const first=await openai.finalizeProtectedOpenAIEdit({...f,...t,assertCurrent:async()=>{}});
 const verify=result=>{canvasBatch.assertCanvasCanonicalBatchResult(result);assert.equal(result.batchId,f.receipt.jobId);assert.equal(result.providerJobId,f.receipt.jobId);assert.equal(result.maskTreatment,undefined);for(const [i,c]of result.images.entries()){assert.equal(c.batchId,f.receipt.jobId);assert.equal(c.providerJobId,f.receipt.jobId);assert.equal(c.jobId,c.imageId);assert(c.imageId.startsWith('wa-'));assert.notEqual(c.jobId,f.receipt.jobId);assert.equal(c.candidateIndex,i);}const normalized=results.normalizeCanvasImageEditCandidates(result);assert.equal(normalized.length,4);assert.equal(new Set(normalized.map(c=>c.imageId)).size,4);for(const [i,c]of normalized.entries()){assert.equal(c.batchId,f.receipt.jobId);assert.equal(c.jobId,result.images[i].jobId);}};
 verify(first);assert.equal(t.inputs.size,4);t.events.length=0;let generation=0,saves=0;const beforeEncode=encodes;
 const recovered=await openai.finalizeProtectedOpenAIEdit({...f,assertCurrent:async()=>{},call:async(path,...rest)=>{if(path.includes('provider-actions')||path.includes('image-ai')){generation++;throw new Error('generation_forbidden');}return t.call(path,...rest);},save:async()=>{saves++;throw new Error('saved_post_forbidden');}});
 verify(recovered);assert.equal(generation,0);assert.equal(saves,0);assert.equal(encodes,beforeEncode);assert.deepEqual(t.events,[]);
 for(const mutate of [r=>{delete r.batchId;},r=>{r.batchId='foreign';},r=>{r.provider='foreign';},r=>{r.images[3].batchId='foreign';},r=>{r.images[3].providerJobId='foreign';},r=>{r.images[3].provider='foreign';},r=>{delete r.images[3].protectedRegionComposited;},r=>{r.requiresProtectedComposite=true;},r=>{delete r.canvasProtectedBatchBinding;},r=>{r.images[3].imageId=r.images[0].imageId;}]){const wrong=structuredClone(recovered);mutate(wrong);assert.deepEqual(results.normalizeCanvasImageEditCandidates(wrong),[]);}
});
