import assert from 'node:assert/strict';
import test from 'node:test';
import fs from 'node:fs/promises';
import ts from 'typescript';
const source=await fs.readFile(new URL('../src/pages/LightchainWorkbenchPage.tsx',import.meta.url),'utf8'),ast=ts.createSourceFile('page.tsx',source,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX),nodes=[];const walk=n=>{nodes.push(n);ts.forEachChild(n,walk);};walk(ast);
const effect=nodes.find(n=>ts.isCallExpression(n)&&n.expression.getText(ast)==='useEffect'&&n.arguments[0].getText(ast).includes('hydrateRemoteGallery'));
const evalEffect=b=>new Function('bindings',`with(bindings){${ts.transpile(`return (${effect.arguments[0].getText(ast)});`,{target:ts.ScriptTarget.ES2022})}}`)(new Proxy(b,{has:()=>true,get:(o,k)=>k===Symbol.unscopables?undefined:k in o?o[k]:globalThis[k]}));
const idle=()=>new Promise(r=>setImmediate(r));const hold=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};};
function fixture({client,sign}={}){const state={remote:null,errors:[]},b={currentBrand:{id:'brand'},emptyMaterialTabItems:{'generation-history':[]},cloudflareDataPlane:client===null?null:client??{listGeneratedImages:async()=>[{id:'image',brand_id:'brand',created_at:'2026-10-02',image_url:'',storage_path:'generated-images/image',feature_type:'ai-fitting'}]},asGeneratedImageListRow:x=>x,withSignedImageUrls:sign??(async rows=>rows.map(x=>({...x,image_url:'fresh-signed-url'}))),setRemoteMaterialTabItems:v=>state.remote=v,toast:{error:v=>state.errors.push(v)}};return {b,state,run:()=>evalEffect(b)()};}
test('local-only Workbench does not start unavailable remote Gallery hydration',async()=>{const f=fixture({client:null});f.run();await idle();assert.deepEqual(f.state.remote,{'generation-history':[]});assert.deepEqual(f.state.errors,[]);});
test('remote list or signing failure is handled, visible, and preserves local workspace inputs',async()=>{for(const failure of ['list','sign']){const f=fixture(failure==='list'?{client:{listGeneratedImages:async()=>{throw Error('offline');}}}:{sign:async()=>{throw Error('sign_failed');}});f.run();await idle();assert.deepEqual(f.state.remote,{'generation-history':[]});assert.equal(f.state.errors.length,1);assert.match(f.state.errors[0],/取得できません/);}});
test('cancelled late success/failure cannot promote remote rows or notify the new scope',async()=>{for(const failed of [false,true]){const h=hold(),f=fixture({client:{listGeneratedImages:()=>h.promise}});const cancel=f.run();cancel();failed?h.reject(Error('late')):h.resolve([{id:'image',created_at:'2026-10-02'}]);await idle();assert.equal(f.state.remote,null);assert.deepEqual(f.state.errors,[]);}});
test('successful read keeps canonical IDs and signed preview in remote generation list',async()=>{const f=fixture();f.run();await idle();const item=f.state.remote['generation-history'][0];assert.equal(item.sourceImageId,'image');assert.equal(item.sourceStoragePath,'generated-images/image');assert.equal(item.imageUrl,'fresh-signed-url');assert.equal(f.state.errors.length,0);});
