import assert from 'node:assert/strict';
import test,{after} from 'node:test';
import {createHash,randomUUID} from 'node:crypto';
import {deflateSync} from 'node:zlib';
import fs from 'node:fs/promises';
import sharp from 'sharp';
import ts from 'typescript';
import {createServer} from 'vite';
import {createPendingIndexedDbHarness} from './verify-cloudflare-image-pending-store.test.mjs';
const vite=await createServer({configFile:false,envFile:false,server:{middlewareMode:true},appType:'custom',logLevel:'silent',optimizeDeps:{noDiscovery:true,include:[]}});
const [bridge,batch,promotion,metadata,documents,recovery,contract,inputs,pending,image,local,material,openai,edit]=await Promise.all(['/src/lib/canvasProtectedSourcePromotionBridge.ts','/src/lib/canvasProtectedBatchComposite.ts','/src/lib/canvasSourcePromotion.ts','/src/features/canvasSourceMetadata.ts','/src/lib/canvasDocumentPersistence.ts','/src/lib/canvasDocumentSaveRecovery.ts','/src/lib/protectedImageEditContract.ts','/src/lib/cloudflareImageInputCache.ts','/src/lib/cloudflareImagePendingStore.ts','/src/lib/cloudflareImageAI.ts','/src/lib/localWorkspaceArtifacts.ts','/src/lib/materialProtectedComposite.ts','/src/lib/protectedOpenAIImageEdit.ts','/src/lib/cloudflareProtectedImageEdit.ts'].map(p=>vite.ssrLoadModule(p)));
const globals=Object.fromEntries(['window','localStorage','navigator','indexedDB','Image','ImageData','document','fetch'].map(k=>[k,Object.getOwnPropertyDescriptor(globalThis,k)]));
const nativeFetch=globalThis.fetch;
after(async()=>{for(const[k,v]of Object.entries(globals)){if(v)Object.defineProperty(globalThis,k,v);else delete globalThis[k];}await vite.close();});
const hash=bytes=>createHash('sha256').update(bytes).digest('hex');
const crc=bytes=>{let n=0xffffffff;for(const b of bytes){n^=b;for(let k=0;k<8;k++)n=(n>>>1)^((n&1)?0xedb88320:0);}return(n^0xffffffff)>>>0;};
function png(width,height,pixels){const chunk=(name,bytes)=>{const type=Buffer.from(name),out=Buffer.alloc(bytes.length+12);out.writeUInt32BE(bytes.length);type.copy(out,4);bytes.copy(out,8);out.writeUInt32BE(crc(Buffer.concat([type,bytes])),out.length-4);return out;};const head=Buffer.alloc(13);head.writeUInt32BE(width);head.writeUInt32BE(height,4);head[8]=8;head[9]=6;const rows=Buffer.alloc(height*(width*4+1));for(let y=0;y<height;y++)Buffer.from(pixels.slice(y*width*4,(y+1)*width*4)).copy(rows,y*(width*4+1)+1);return Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',head),chunk('IDAT',deflateSync(rows)),chunk('IEND',Buffer.alloc(0))]);}
const dataUrl=bytes=>'data:image/png;base64,'+Buffer.from(bytes).toString('base64');
function setup(){const map=new Map(),storage={map,getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)};globalThis.localStorage=storage;globalThis.window={localStorage:storage,dispatchEvent(){}};globalThis.indexedDB=createPendingIndexedDbHarness();Object.defineProperty(globalThis,'navigator',{value:{locks:{request:async(name,_options,callback)=>callback({name,mode:'exclusive'})}},configurable:true});globalThis.ImageData=class{constructor(data,width,height){Object.assign(this,{data,width,height});}};
 globalThis.Image=class{set src(url){void(async()=>{try{const bytes=url.startsWith('data:')?Buffer.from(url.split(',')[1],'base64'):Buffer.from(await(await(url.startsWith('blob:')?nativeFetch(url):fetch(url))).arrayBuffer());const {data,info}=await sharp(bytes).ensureAlpha().raw().toBuffer({resolveWithObject:true});Object.assign(this,{naturalWidth:info.width,naturalHeight:info.height,width:info.width,height:info.height,pixels:data});this.onload();}catch(error){this.onerror(error);}})();}};
 globalThis.document={createElement(){const canvas={width:0,height:0,pixels:[]};const ctx={clearRect(){canvas.pixels=new Uint8ClampedArray(canvas.width*canvas.height*4);},fillRect(x,y,w,h){if(!canvas.pixels.length)canvas.pixels=new Uint8ClampedArray(canvas.width*canvas.height*4);const v=this.fillStyle==='#fff'?[255,255,255,255]:[0,0,0,255];for(let j=y;j<y+h;j++)for(let i=x;i<x+w;i++)canvas.pixels.set(v,(j*canvas.width+i)*4);},drawImage(img,...args){if(!canvas.pixels.length)canvas.pixels=new Uint8ClampedArray(canvas.width*canvas.height*4);const [sx,sy,sw,sh,dx,dy,w,h]=args.length===8?args:[0,0,img.width,img.height,args[0]??0,args[1]??0,args[2]??img.width,args[3]??img.height];for(let y=Math.max(0,Math.floor(dy));y<Math.min(canvas.height,Math.ceil(dy+h));y++)for(let x=Math.max(0,Math.floor(dx));x<Math.min(canvas.width,Math.ceil(dx+w));x++){if(x+.5<dx||x+.5>=dx+w||y+.5<dy||y+.5>=dy+h)continue;const at=(Math.min(img.height-1,Math.floor(sy+(y+.5-dy)/h*sh))*img.width+Math.min(img.width-1,Math.floor(sx+(x+.5-dx)/w*sw)))*4;canvas.pixels.set(img.pixels.slice(at,at+4),(y*canvas.width+x)*4);}},getImageData:()=>({data:new Uint8ClampedArray(canvas.pixels)}),putImageData(v){canvas.pixels=new Uint8ClampedArray(v.data);}};canvas.getContext=()=>ctx;canvas.toDataURL=()=>dataUrl(png(canvas.width,canvas.height,canvas.pixels));return canvas;}};return storage;
}
async function actualFunction(file,name,bindings){const source=await fs.readFile(new URL(file,import.meta.url),'utf8'),ast=ts.createSourceFile(file,source,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);let found;const walk=n=>{if(ts.isVariableDeclaration(n)&&n.name.getText(ast)===name)found=n.initializer;if(ts.isMethodDeclaration(n)&&n.name.getText(ast)===name)found=n;ts.forEachChild(n,walk);};walk(ast);assert(found,name);const text=ts.isMethodDeclaration(found)?`async function(brandId,requestId,assertContext,expectedSourceImageUrl,expectedSourceIdentity) ${found.body.getText(ast)}`:found.getText(ast);return new Function(...Object.keys(bindings),ts.transpile('return '+text,{target:ts.ScriptTarget.ES2022}))(...Object.values(bindings));}
async function fixture(){const storage=setup(),raw=png(2,2,[3,5,9,255,21,31,41,255,61,71,81,255,91,101,111,128]),blob=new Blob([raw],{type:'image/png'}),sourceMetadata=await metadata.buildLocalUploadSourceMetadata(blob,{width:2,height:2}),object={id:'parent',type:'image',src:'local-canvas-asset://native-'+randomUUID(),x:17,y:25,width:2,height:2,rotation:3,scaleX:1,scaleY:1,opacity:.8,locked:false,visible:true,zIndex:0,metadata:{feature:'local-upload',generation:0,...sourceMetadata}},scope={origin:'https://bridge-api.test',userId:'alice',brandId:'brand'},localId='local-'+randomUUID();const original=await batch.resolveCanvasProtectedObjectSource(object,async()=>URL.createObjectURL(blob),()=>{}),mask=dataUrl(png(2,2,[0,0,0,255,0,0,0,255,0,0,0,0,0,0,0,0]));
 const binding=await batch.prepareCanvasProtectedBatch({sourceIdentity:original.objectDescriptor,verifiedObjectSource:original,sourceImageUrl:original.originalPngDataUrl,maskDataUrl:mask,requestId:randomUUID(),featureType:'canvas-partial-edit',brandId:scope.brandId,scopeId:scope.userId,canvasProjectId:localId,parentObjectId:object.id,generation:1,inputSignature:['actual'],assertCurrent:()=>{}});
 const stage=await edit.prepareProtectedCloudflareEdit({brandId:scope.brandId,imageUrls:[original.originalPngDataUrl],maskDataUrl:mask,generationProvider:'openai',featureType:binding.featureType,count:4,canvasProjectId:localId,parentObjectId:object.id,generation:1,prompt:'edit'}),plan=stage.plan,map={version:'protected-openai-contain-v1',digestScheme:'sha256-data-url-utf8-v1',stage:{width:2,height:2,primaryDigest:plan.sourceSha256,maskDigest:plan.maskSha256,guideDigest:await contract.protectedImageDigest(stage.body.imageUrls[1])},prepared:{width:2,height:2,primaryDigest:plan.sourceSha256,guideDigest:await contract.protectedImageDigest(stage.body.imageUrls[1]),transform:{x:0,y:0,scaleX:1,scaleY:1}},candidate:{width:1024,height:1024},contain:{x:0,y:0,scale:512},projected:{primaryDigest:'d'.repeat(64),guideDigest:'e'.repeat(64)}},native={version:'canvas-protected-openai-contain-v1',original:{width:2,height:2,digest:plan.sourceSha256,digestScheme:'sha256-data-url-utf8-v1'},stage:{width:2,height:2,primaryDigest:plan.sourceSha256,maskDigest:plan.maskSha256},frame:{x:0,y:0,width:2,height:2},printingSnapshotDigest:await contract.protectedImageDigest('[]'),mapping:map,candidateGeometry:{version:'openai-output-frame-v1',width:1024,height:1024},canvasBatch:binding},prepared={...stage,body:{...stage.body,canvasProtectedBatchBinding:binding,protectedOpenAIProjection:map,nativePrintFinalFrame:native},canvasProtectedBatchBinding:binding};
 await batch.bindCanvasProtectedPreparation(binding,prepared,async()=>{});const key=await image.durableImageRecoveryKey(scope.origin,scope.userId,'edit-image',prepared.body);await pending.rememberPendingIdentity(key,binding.requestId);await inputs.persistProtectedImageInput(scope,prepared,binding.requestId,key);
 let uploadPosts=0;const promotionRecord=await promotion.promoteCanvasLocalSource({scope,object,readCurrentObject:()=>object,assertCurrent:()=>{},getBlob:async()=>blob,readDimensions:async()=>({width:2,height:2}),blobDataUrl:async()=>dataUrl(raw),readRemote:async()=>{throw new Error('cloudflare_api_404_workspace_artifact_not_found');},saveRemote:async input=>{uploadPosts++;const id='wa-'+input.requestId;return{success:true,remote:{jobId:id,imageId:id,storagePath:'generated-images/'+id}};},signedRead:async path=>'https://bridge-media.test/'+path,fetchBytes:async()=>Uint8Array.from(raw).buffer});
 const aliased=promotion.applyCanvasSourcePromotionAlias(object,promotionRecord),snapshot=documents.buildCanvasDocumentSnapshot({projectId:localId,name:'Actual',objects:promotion.canvasSaveObjectsWithPromotedSources([aliased],scope),sourceProjectIds:[localId],view:{zoom:.7,panX:13,panY:19}}),hydrate=await actualFunction('../src/pages/CanvasEditorPage.tsx','restoreCanvasObjects',{}),hydrated=hydrate(snapshot),documentId=await recovery.initialCanvasDocumentId(scope,localId);
 recovery.retainCanvasSaveDraft(scope,documentId,{title:'Actual',snapshot},{ownerId:scope.userId,revision:0});let current=hydrated[0],mediaReads=0;const entry={requestId:binding.requestId,brandId:scope.brandId,canvasProjectId:localId,parentObjectId:object.id,generation:binding.generation,featureType:binding.featureType,prompt:'edit',createdAt:new Date().toISOString()},context={binding,scope,object:current,canvasProjectId:documentId,canvasProjectAliases:[localId],pending:entry};
 const options={...context,assertCurrent:()=>{},readCurrentObject:()=>current,signedRead:async path=>{assert.equal(path,promotionRecord.remote.storagePath);return 'https://bridge-media.test/'+path;},fetchMedia:async url=>{mediaReads++;assert.equal(url,'https://bridge-media.test/'+promotionRecord.remote.storagePath);return new Response(raw,{headers:{'content-type':'image/png'}});}};
 return{raw,blob,object,original,mask,binding,prepared,map,native,key,scope,localId,documentId,promotionRecord,snapshot,hydrated,aliased,entry,context,options,storage,uploadPosts,get mediaReads(){return mediaReads;},setCurrent:o=>{current=o;},current:()=>current};
}

test('actual promotion → serializer → page hydration bridge preserves immutable proof and matches raw/dataURL SHA256 separately; local remaining stays strict',async()=>{const f=await fixture(),before=JSON.stringify((await batch.loadCanvasProtectedBatch(f.binding)).sourceProof);assert.notEqual(hash(f.raw),await contract.protectedImageDigest(f.original.originalPngDataUrl));assert.equal(f.snapshot.localProjectId,f.localId);assert.equal(f.hydrated[0].src,f.promotionRecord.remote.storagePath);assert.equal(f.uploadPosts,1);assert.notEqual(f.object.src,f.hydrated[0].src);const localVerified=await batch.verifyCanvasPinnedObjectSource(f.binding,f.aliased,async()=>URL.createObjectURL(f.blob),()=>{});assert.equal(localVerified.originalPngDigest,f.original.originalPngDigest);const verified=await bridge.verifyCanvasProtectedSourcePromotionBridge(f.options);assert.deepEqual(verified,f.original);assert.equal(f.mediaReads,1);assert.equal(JSON.stringify((await batch.loadCanvasProtectedBatch(f.binding)).sourceProof),before);for(const key of ['id','x','y','width','height','rotation','scaleX','scaleY','opacity'])assert.equal(f.hydrated[0][key],f.object[key]);});
test('read-only diagnosis compares originals but reports both PNG checks unperformed; records/cache/pending remain byte-for-byte unchanged',async()=>{const f=await fixture(),storage=JSON.stringify([...f.storage.map]),db=globalThis.indexedDB.log.length,diagnostic=await bridge.inspectCanvasProtectedSourcePromotionBridge(f.context);assert.equal(diagnostic.status,'unproven_pixels');assert.equal(diagnostic.rawPngVerification,'unperformed');assert.equal(diagnostic.materializedPngVerification,'unperformed');assert.equal(f.mediaReads,0);assert.equal(JSON.stringify([...f.storage.map]),storage);assert(!globalThis.indexedDB.log.slice(db).some(e=>['put','delete'].includes(e.operation)));});
for(const kind of ['foreign-user','foreign-brand','foreign-origin','foreign-canvas','forged-alias','missing-cache-alias','foreign-object','wrong-remote','gallery','image-id','generation','changed-src','source-revision','source-identity','missing-record','dispatched-record','wrong-record-raw-sha','wrong-record-uuid','wrong-pending-request','wrong-pending-feature'])test(`${kind} rejects before signed media, provider GET/generation/save/cleanup`,async()=>{const f=await fixture(),options={...f.options,object:structuredClone(f.context.object),scope:{...f.scope},pending:{...f.entry}};f.setCurrent(options.object);
 if(kind==='foreign-user')options.scope.userId='bob';if(kind==='foreign-brand')options.scope.brandId='other';if(kind==='foreign-origin')options.scope.origin='https://other.test';if(kind==='foreign-canvas')options.canvasProjectId=randomUUID();if(kind==='forged-alias')options.canvasProjectAliases=['local-foreign'];if(kind==='missing-cache-alias'){const cache=recovery.readCanvasSaveRecovery(f.scope,f.documentId);cache.snapshot.sourceProjectIds=[];f.storage.setItem(recovery.canvasSaveRecoveryKey(f.scope,f.documentId),JSON.stringify(cache));}if(kind==='foreign-object')options.object.id='foreign';if(kind==='wrong-remote')options.object.metadata.parameters.remoteStoragePath='generated-images/wa-foreign';if(kind==='gallery')options.object.metadata.galleryStoragePath='generated-images/foreign';if(kind==='image-id')options.object.metadata.imageId='foreign';if(kind==='generation')options.object.metadata.generation=99;if(kind==='changed-src')options.object.src='generated-images/changed';if(kind==='source-revision')options.object.metadata.sourceRevision.revision='changed';if(kind==='source-identity')options.object.metadata.sourceIdentity.hash='f'.repeat(64);if(kind==='wrong-pending-request')options.pending.requestId=randomUUID();if(kind==='wrong-pending-feature')options.pending.featureType='canvas-inpaint';const recordKey=[...f.storage.map.keys()].find(k=>k.startsWith('heavy:canvas-source-promotion:'));
 if(kind==='missing-record')f.storage.removeItem(recordKey);if(kind.startsWith('dispatched-record')||kind.startsWith('wrong-record')){const record=JSON.parse(f.storage.getItem(recordKey));if(kind==='dispatched-record')record.stage='dispatched';if(kind==='wrong-record-raw-sha')record.binding.rawSha256='f'.repeat(64);if(kind==='wrong-record-uuid')record.binding.requestId=randomUUID();f.storage.setItem(recordKey,JSON.stringify(record));}
 const before=JSON.stringify([...f.storage.map]);let signed=0,providerGet=0,generation=0,save=0,cleanup=0;options.signedRead=async()=>{signed++;throw new Error('forbidden');};const run=async()=>{await bridge.verifyCanvasProtectedSourcePromotionBridge(options);providerGet++;generation++;save++;cleanup++;};await assert.rejects(run);assert.deepEqual([signed,providerGet,generation,save,cleanup],[0,0,0,0,0]);assert.equal(JSON.stringify([...f.storage.map]),before);
});
for(const kind of ['swapped-bytes','wrong-mime','media-failure','materialized-digest','wrong-dimensions','source-changed-during-media','scope-changed-during-media'])test(`${kind} rejects pixel proof before recovery and preserves pending/no writes`,async()=>{const f=await fixture(),options={...f.options},before=JSON.stringify([...f.storage.map]);let recovered=0;
 if(kind==='swapped-bytes')options.fetchMedia=async()=>new Response(png(2,2,new Uint8Array(16).fill(255)),{headers:{'content-type':'image/png'}});if(kind==='wrong-mime')options.fetchMedia=async()=>new Response(f.raw,{headers:{'content-type':'image/jpeg'}});if(kind==='media-failure')options.fetchMedia=async()=>{throw new Error('media_offline');};
 const originalImage=globalThis.Image;if(kind==='materialized-digest'||kind==='wrong-dimensions')globalThis.Image=class extends originalImage{set src(url){super.src=url;const loaded=this.onload;this.onload=()=>{if(url.startsWith('blob:')){if(kind==='materialized-digest')this.pixels[0]^=1;else{this.width=this.naturalWidth=1;}}loaded();};}};
 if(kind==='source-changed-during-media')options.fetchMedia=async()=>{f.setCurrent({...f.current(),src:'changed'});return new Response(f.raw,{headers:{'content-type':'image/png'}});};if(kind==='scope-changed-during-media'){let stale=false;options.fetchMedia=async()=>{stale=true;return new Response(f.raw,{headers:{'content-type':'image/png'}});};options.assertCurrent=()=>{if(stale)throw new Error('auth_changed');};}
 try{await assert.rejects((async()=>{await bridge.verifyCanvasProtectedSourcePromotionBridge(options);recovered++;})());assert.equal(recovered,0);assert.equal(JSON.stringify([...f.storage.map]),before);assert.equal((await pending.readPendingIdentity(f.key)).requestId,f.binding.requestId);}finally{globalThis.Image=originalImage;}
});

async function completedBatch(f){const media=new Map(),saved=new Map(),writes=[],operations=[];const receipt={success:true,requestId:f.binding.requestId,state:'completed',recovery:'terminal',requiresProtectedComposite:true,persistenceStatus:'completed',requestedCandidateCount:4,persistedCandidateCount:4,jobId:'ai-'+f.binding.requestId,featureType:f.binding.featureType,provider:'openai',backendProvider:'openai-images-api',providerModel:'gpt-image-1-mini',resolvedProvider:{provider:'openai',backendProvider:'openai-images-api',model:'gpt-image-1-mini',action:'edit-image',requestId:f.binding.requestId},protectedEdit:f.prepared.plan,metadata:{nativePrintFinalFrame:f.native,protectedOpenAIProjection:f.map},images:Array.from({length:4},(_,index)=>{const pixels=new Uint8ClampedArray(1024*1024*4);for(let at=0;at<pixels.length;at+=4)pixels.set([120+index,150,180,255],at);return{candidateIndex:index,provider:'openai',providerModel:'gpt-image-1-mini',modelUsed:'gpt-image-1-mini',imageId:`ai-${f.binding.requestId}-${index}`,jobId:'ai-'+f.binding.requestId,storagePath:`generated-images/ai-${f.binding.requestId}-${index}`,width:1024,height:1024,imageUrl:dataUrl(png(1024,1024,pixels))};})};
 globalThis.fetch=async url=>{operations.push(['media',String(url)]);const bytes=String(url)==='https://bridge-media.test/'+f.promotionRecord.remote.storagePath?f.raw:media.get(String(url));if(!bytes)throw new Error('unknown_url_forbidden');return new Response(bytes,{headers:{'content-type':'image/png'}});};
 const call=async(path,init)=>{operations.push(['call',path,init?.method??'GET']);if(path.startsWith('/v1/workspace-artifacts/')){const result=saved.get(path.split('/').at(-1));if(!result)throw new Error('cloudflare_api_404_workspace_artifact_not_found');return result;}if(path.startsWith('/v1/media/read?')){const query=new URLSearchParams(path.split('?')[1]);assert.equal(query.get('bucket'),'generated-images');assert.equal(query.get('expiresIn'),'3600');return{url:'https://bridge-final-media.test/'+query.get('path')};}throw new Error('provider_generation_or_read_forbidden');};
 const save=async input=>{writes.push(structuredClone(input));const id='wa-'+input.requestId,result={success:true,remote:{jobId:id,imageId:id,storagePath:'generated-images/'+id},metadata:structuredClone(input.metadata)};saved.set(input.requestId,result);media.set('https://bridge-final-media.test/'+result.remote.storagePath,Buffer.from(input.imageUrl.split(',')[1],'base64'));return result;};
 const lifecycle=await batch.createCanvasProtectedBatchLifecycle(f.binding,f.prepared,{brandId:f.scope.brandId,userId:f.scope.userId},async()=>{}),result=await openai.finalizeProtectedOpenAIEdit({prepared:f.prepared,receipt,assertCurrent:async()=>{},call,save,lifecycle});batch.assertCanvasCanonicalBatchResult(result);assert.equal(writes.length,4);
 const recover=await actualFunction('../src/lib/cloudflareApi.ts','recoverProtectedCanvasBatchComposite',{loadProtectedImageInput:inputs.loadProtectedImageInput,loadCanvasProtectedBatch:batch.loadCanvasProtectedBatch,canvasBatchHasAllRaw:batch.canvasBatchHasAllRaw,createCanvasProtectedBatchLifecycle:batch.createCanvasProtectedBatchLifecycle,finalizeProtectedOpenAIEdit:openai.finalizeProtectedOpenAIEdit,protectedImageDigest:contract.protectedImageDigest,materializeMaterialPng:material.materializeMaterialPng});
 const api={origin:f.scope.origin,captureRequestContext:async guard=>({userId:f.scope.userId,assertCurrent:async()=>{guard?.();},call}),saveWorkspaceArtifact:save,recoverProtectedCanvasBatchComposite:recover};return{api,result,writes,operations,saved,media};
}
async function pageRecovery(f,transport,options={}){const results=await vite.ssrLoadModule('/src/lib/canvasImageEditResults.ts'),state={currentProjectId:f.documentId,objects:[f.current()]},placed=new Map(),auth={user:{id:f.scope.userId},currentBrand:{id:f.scope.brandId}};let recoveryCalls=0,strictCalls=0,bridges=0;const guard=()=>{const current=state.objects.find(o=>o.id===f.object.id);if(!current||JSON.stringify(batch.canvasObjectProtectedIdentity(current))!==JSON.stringify(batch.canvasObjectProtectedIdentity(f.current())))throw new Error('canvas_image_edit_target_changed');};
 const api={...transport.api,recoverProtectedCanvasBatchComposite:async function(...args){recoveryCalls++;assert.equal(args[1],f.binding.requestId);assert.equal(args[3],f.original.originalPngDataUrl);assert.deepEqual(args[4],f.original.objectDescriptor);assert.notDeepEqual(args[4],batch.canvasObjectProtectedIdentity(f.hydrated[0]));return transport.api.recoverProtectedCanvasBatchComposite.apply(this,args);}};
 const bindings={cloudflareDataPlane:api,useCanvasStore:{getState:()=>state},useAuthStore:{getState:()=>auth},canvasSourceProjectIdsRef:{current:[f.localId]},initialCanvasDocumentId:recovery.initialCanvasDocumentId,user:auth.user,captureCanvasImageEditContext:()=>guard,loadCanvasProtectedBatchForRequest:batch.loadCanvasProtectedBatchForRequest,loadCanvasProtectedBatch:batch.loadCanvasProtectedBatch,canvasObjectProtectedIdentity:batch.canvasObjectProtectedIdentity,verifyCanvasObjectBatchSource:async b=>{strictCalls++;return batch.verifyCanvasPinnedObjectSource(b,state.objects[0],async()=>dataUrl(f.raw),guard);},verifyCanvasProtectedSourcePromotionBridge:async input=>{bridges++;return bridge.verifyCanvasProtectedSourcePromotionBridge(input);},resolveGeneratedImageUrl:async path=>'https://bridge-media.test/'+path,assertCanvasCanonicalBatchResult:batch.assertCanvasCanonicalBatchResult,normalizeCanvasImageEditCandidates:results.normalizeCanvasImageEditCandidates,findRecoveredCanvasCandidate:id=>placed.get(id),loadCanvasImage:async url=>{if(options.afterImageLoad)options.afterImageLoad(state,url);return{};},buildDerivedLightchainMetadata:()=>({}),addImageToCanvas:async(_url,_label,metadata)=>{const id=randomUUID();placed.set(metadata.imageId,id);return id;},...options.bindings};
 const actual=await actualFunction('../src/pages/CanvasEditorPage.tsx','recoverCanvasImageEdit',bindings);return{run:()=>actual(f.entry),state,placed,auth,get recoveryCalls(){return recoveryCalls;},get strictCalls(){return strictCalls;},get bridges(){return bridges;}};
}
test('actual page recovery passes immutable original proof to actual save-only API and re-verifies bridge after result/before each placement; exact four retained finals dedup with POST/generation/ACK0',async()=>{const f=await fixture(),t=await completedBatch(f),beforeBodies=JSON.stringify(t.writes),beforePending=await pending.readPendingIdentity(f.key),beforeBinding=JSON.stringify(f.binding),page=await pageRecovery(f,t);t.operations.length=0;await page.run();assert.equal(page.recoveryCalls,1);assert.equal(page.strictCalls,0);assert.equal(page.placed.size,4);assert.equal(page.bridges,10);const ids=[...page.placed.keys()];assert.deepEqual(ids,t.result.images.map(i=>i.imageId));assert.equal(JSON.stringify(t.writes),beforeBodies);assert.equal(t.operations.filter(e=>e[0]==='call'&&(e[1].includes('/image-ai/')||e[1].includes('/provider-actions/')||e[2]==='POST')).length,0);assert.deepEqual(await pending.readPendingIdentity(f.key),beforePending);assert.equal(JSON.stringify(f.binding),beforeBinding);await page.run();assert.equal(page.placed.size,4);assert.equal(page.bridges,16);assert.equal(t.writes.length,4);});
for(const kind of ['forged-alias','swapped-bytes','unallowed-gallery','scope','source-after-result','source-before-placement'])test(`actual page ${kind} fence blocks recovery or placement without generation/save/cleanup`,async()=>{const f=await fixture(),t=await completedBatch(f),page=await pageRecovery(f,t,kind==='source-before-placement'?{afterImageLoad:state=>{state.objects[0]={...state.objects[0],src:'changed-after-load'};}}:{});t.operations.length=0;const beforeWrites=t.writes.length;if(kind==='forged-alias')page.state.currentProjectId=randomUUID();if(kind==='swapped-bytes')globalThis.fetch=async()=>new Response(png(2,2,new Uint8Array(16).fill(255)),{headers:{'content-type':'image/png'}});if(kind==='unallowed-gallery')page.state.objects[0].metadata.galleryStoragePath='generated-images/other';if(kind==='scope')page.auth.currentBrand.id='foreign';if(kind==='source-after-result'){const original=t.api.recoverProtectedCanvasBatchComposite;t.api.recoverProtectedCanvasBatchComposite=async function(...args){const result=await original.apply(this,args);page.state.objects[0]={...page.state.objects[0],src:'changed-after-result'};return result;};}
 await assert.rejects(page.run());assert.equal(page.placed.size,0);if(['forged-alias','swapped-bytes','unallowed-gallery','scope'].includes(kind))assert.equal(page.recoveryCalls,0);assert.equal(t.writes.length,beforeWrites);assert.equal(t.operations.filter(e=>e[0]==='call'&&(e[1].includes('/image-ai/')||e[1].includes('/provider-actions/')||e[2]==='POST')).length,0);assert.equal((await pending.readPendingIdentity(f.key)).requestId,f.binding.requestId);
});

test('actual readonly probe TSX transforms; allowlist projection omits nested and unknown secrets, signed URL queries and PNG/dataURL bytes',async()=>{
 const transformed=await vite.transformRequest('/scripts/browser/canvas-protected-batch-react-probe.tsx');assert(transformed?.code.includes('promotedSourceDiagnostic'));
 const project=await actualFunction('./browser/canvas-protected-batch-react-probe.tsx','safeDiagnostic',{}),canaries=['API_KEY_CANARY','PASSWORD_CANARY','SECRET_CANARY','CREDENTIAL_CANARY','UNKNOWN_KEY_CANARY','SIGNED_QUERY_CANARY','PNG_BYTES_CANARY'];
 const descriptor={version:'canvas-object-descriptor-v1',objectId:'parent',imageId:'original',generation:0,sourceRevision:{algorithm:'sha-256',hash:'a'.repeat(64),revision:'sha256:'+'a'.repeat(64),width:160,height:120,sizeBytes:500,mimeType:'image/png',apiKey:canaries[0]},src:'generated-images/wa-original',galleryImageUrl:'https://media.test/file?signature='+canaries[5]+'#private',parameters:{remoteStoragePath:{apiKey:canaries[0],password:canaries[1],deep:{secret:canaries[2],credential:canaries[3],harmlessName:canaries[4]},image:'data:image/png;base64,'+canaries[6]},unexpected:{password:canaries[1]}},candidates:['generated-images/wa-original','data:image/png;base64,'+canaries[6],'blob:'+canaries[6]],credential:canaries[3]};
 const scope={origin:'https://api.test',userId:'alice',brandId:'brand',apiKey:canaries[0]},proof={version:'canvas-object-source-v1',objectDescriptor:descriptor,objectDescriptorDigest:'b'.repeat(64),selectedSource:'local-canvas-asset://original',originalPngDigest:'c'.repeat(64),width:160,height:120,unknownSecret:canaries[4],originalPngDataUrl:'data:image/png;base64,'+canaries[6]};
 const unsafe={status:'unproven_pixels',reason:'raw_and_materialized_png_checks_unperformed',currentDescriptor:descriptor,expectedDescriptor:structuredClone(descriptor),immutableSourceProof:proof,proof:structuredClone(proof),scope,promotion:{stage:'verified',binding:{scope,requestId:randomUUID(),localReference:proof.selectedSource,sourceIdentity:{kind:'local-upload',hash:'a'.repeat(64),password:canaries[1]},sourceRevision:descriptor.sourceRevision,rawSha256:'a'.repeat(64),sizeBytes:500,width:160,height:120,mimeType:'image/png',extraSecret:canaries[4]},remote:{jobId:'wa-original',imageId:'wa-original',storagePath:'generated-images/wa-original',apiKey:canaries[0]}},token:canaries[2],rawPngVerification:'verified',materializedPngVerification:'verified'};
 const before=JSON.stringify(unsafe),output=project(unsafe),serialized=JSON.stringify(output);assert.equal(JSON.stringify(unsafe),before);for(const secret of canaries)assert(!serialized.includes(secret),secret);for(const key of ['apiKey','password','secret','credential','harmlessName','extraSecret','unknownSecret','token'])assert(!serialized.includes('"'+key+'"'),key);assert(!serialized.includes('data:image'));assert(!serialized.includes('base64'));assert(!serialized.includes('blob:'));assert(!serialized.includes('signature'));
 assert.equal(output.currentDescriptor.galleryImageUrl,'https://media.test/file');assert.equal(output.currentDescriptor.parameters.remoteStoragePath,null);assert.equal(output.currentDescriptor.parameterKinds.remoteStoragePath,'object');assert.equal(output.immutableSourceProof.originalPngDigest,'c'.repeat(64));assert.equal(output.promotion.rawSha256,'a'.repeat(64));assert.equal(output.promotion.localReference,proof.selectedSource);assert.equal(output.comparisons.currentMatchesExpected,true);assert.equal(output.comparisons.returnedProofMatchesImmutable,true);assert.equal(output.comparisons.promotionMatchesScope,true);assert.equal(output.rawPngVerification,'unperformed');assert.equal(output.materializedPngVerification,'unperformed');
 // A difference in an omitted nested secret still changes the original compare.
 const changed=structuredClone(unsafe);changed.currentDescriptor.parameters.remoteStoragePath.deep.harmlessName='DIFFERENT_UNKNOWN_SECRET';const changedOutput=project(changed);assert.equal(changedOutput.comparisons.currentMatchesExpected,false);assert(!JSON.stringify(changedOutput).includes('DIFFERENT_UNKNOWN_SECRET'));assert.deepEqual(changedOutput.currentDescriptor,output.currentDescriptor);
});

test('actual readonly reporter projects real three-party proof/promotion/current descriptor and performs no PNG/provider/cache mutation',async()=>{
 const f=await fixture(),project=await actualFunction('./browser/canvas-protected-batch-react-probe.tsx','safeDiagnostic',{}),before=JSON.stringify([...f.storage.map]),inspection=await bridge.inspectCanvasProtectedSourcePromotionBridge(f.context),output=project({...inspection,currentDescriptor:batch.canvasObjectProtectedIdentity(f.current()),immutableSourceProof:(await batch.loadCanvasProtectedBatch(f.binding)).sourceProof,scope:f.scope});
 assert.equal(output.status,'unproven_pixels');assert.equal(output.reason,'raw_and_materialized_png_checks_unperformed');assert.equal(output.comparisons.currentMatchesOriginal,false);assert.equal(output.comparisons.currentMatchesExpected,true);assert.equal(output.comparisons.returnedProofMatchesImmutable,true);assert.equal(output.comparisons.promotionMatchesScope,true);assert.equal(output.comparisons.selectedSourceMatchesLocalReference,true);assert.equal(output.currentDescriptor.src,f.promotionRecord.remote.storagePath);assert.equal(output.immutableSourceProof.objectDescriptor.src,f.object.src);assert.equal(output.promotion.rawSha256,f.promotionRecord.binding.rawSha256);assert.equal(output.rawPngVerification,'unperformed');assert.equal(output.materializedPngVerification,'unperformed');assert.equal(f.mediaReads,0);assert.equal(JSON.stringify([...f.storage.map]),before);
});

test('actual page local alias remaining retains existing strict pinned-source path; bridge is not used and saved finals remain save-only',async()=>{const f=await fixture(),t=await completedBatch(f);f.setCurrent(f.aliased);const page=await pageRecovery(f,t);t.operations.length=0;await page.run();assert.equal(page.strictCalls,10);assert.equal(page.bridges,0);assert.equal(page.placed.size,4);assert.equal(page.recoveryCalls,1);assert.equal(t.writes.length,4);assert.equal(t.operations.filter(e=>e[0]==='call'&&(e[1].includes('/image-ai/')||e[1].includes('/provider-actions/')||e[2]==='POST')).length,0);assert.equal((await pending.readPendingIdentity(f.key)).requestId,f.binding.requestId);});
